// Generated by IqwanEngine
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Shield, Database, Users, CheckCircle2, ArrowRight, Activity, Layers, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

export const AboutSection: React.FC = () => {
  const [activePillar, setActivePillar] = useState<number>(0);

  const pillars = [
    {
      id: 0,
      title: "Integriti & Eksekusi Tulen",
      subtitle: "Tier-1 Liquidity Access Tanpa Konflik Kepentingan",
      icon: Shield,
      accentColor: "from-[#D4AF37] to-[#F59E0B]",
      tag: "TIADA DEALING DESK",
      description:
        "OWLFX dibina atas prinsip ketelusan mutlak. Kami beroperasi secara langsung melalui penyedia kecairan institusi antarabangsa menerusi akaun MIB Valetax. Tiada 'b-book manipulation', tiada lonjakan spread buatan, dan setiap pesanan dihantar terus ke pasaran antara bank (Interbank ECN).",
      points: [
        "Akaun ECN Raw Spread bermula 0.0 pip pada pasangan mata wang utama dan Gold.",
        "Pelaksanaan pantas dengan latensi pelayan kurang daripada 15 milisaat (Equinix NY4/LD4).",
        "Pemisahan dana trading (Segregated Client Funds) di bank berkanun gred AA."
      ]
    },
    {
      id: 1,
      title: "Indicator & Kod Algoritma",
      subtitle: "Code Struktur Pasaran Berasaskan Kepintaran Buatan",
      icon: Database,
      accentColor: "from-[#38BDF8] to-[#2563EB]",
      tag: "ORDER FLOW & ALGO",
      description:
        "Zaman dagangan berasaskan emosi dan firasat rawak telah berakhir. OWLFX menggabungkan pemprosesan data bervolum besar, model kebarangkalian Bayes, dan pengesanan zon Institutional Order Flow untuk membina indikator petunjuk yang memberi kelebihan statistik (statistical edge) kepada trader runcit.",
      points: [
        "Pengesanan zon Liquidity Sweep dan Fair Value Gap (FVG) secara automatik.",
        "Penapis volum pasaran masa nyata untuk menolak isyarat palsu semasa pasaran mendatar.",
        "Pengurusan nisbah risiko ganjaran minimum 1:3 untuk mengekalkan jangkaan positif."
      ]
    },
    {
      id: 2,
      title: "Ketelusan Komuniti & Self-Rebate",
      subtitle: "Ekosistem Win-Win untuk Trader dan IB",
      icon: Users,
      accentColor: "from-[#10B981] to-[#059669]",
      tag: "EKOSISTEM TELUS",
      description:
        "Bagi kami, kejayaan jangka panjang trader adalah teras perniagaan. Kami menstruktur semula sistem Introducing Broker konvensional dengan memulangkan sebahagian besar rebat komisen terus ke poket trader itu sendiri (Self-Rebate), disokong oleh jelajah kelas fizikal berkala di 14 negeri.",
      points: [
        "Pemulangan tunai rebat harian/mingguan yang boleh ditarik keluar serta-merta.",
        "Bimbingan fizikal bersemuka tanpa yuran tersembunyi melalui Roadtour Kebangsaan.",
        "Sokongan meja dagangan (Desk Support) pantas melalui WhatsApp dan Telegram komuniti."
      ]
    }
  ];

  return (
    <section id="about" className="py-24 relative overflow-hidden bg-[#06090e]/95 text-slate-200">
      {/* Ambient Lighting & High-Tech Matrix Overlay */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden -z-10">
        <div className="absolute -top-32 -left-32 w-[550px] h-[550px] bg-amber-500/15 rounded-full blur-[140px] animate-pulse" />
        <div className="absolute top-1/3 -right-32 w-[550px] h-[550px] bg-cyan-500/15 rounded-full blur-[140px] animate-pulse delay-1000" />
        <div className="absolute -bottom-32 left-1/4 w-[500px] h-[500px] bg-blue-600/10 rounded-full blur-[160px]" />
        <div
          className="absolute inset-0 opacity-25"
          style={{
            backgroundImage: 'radial-gradient(rgba(255, 255, 255, 0.15) 1px, transparent 1px)',
            backgroundSize: '32px 32px',
            maskImage: 'radial-gradient(ellipse 70% 60% at 50% 40%, #000 60%, transparent 100%)'
          }}
        />
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header (Static Clean Presentation) */}
        <div className="max-w-3xl mb-16">
          <div className="inline-flex items-center space-x-2 px-3 py-1.5 rounded-full bg-slate-900/90 border border-amber-500/30 text-amber-400 text-xs font-mono mb-4 shadow-lg shadow-amber-500/5">
            <Layers className="w-3.5 h-3.5" />
            <span className="tracking-wider">INSTITUTIONAL PEDIGREE & PHILOSOPHY</span>
          </div>

          <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-white tracking-tight leading-tight">
            Merapatkan Jurang Antara{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-amber-400 to-amber-500 drop-shadow-[0_0_20px_rgba(245,158,11,0.25)]">
              Trader Kecil
            </span>{' '}
            & Pasaran Institusi
          </h2>

          <p className="mt-4 text-base sm:text-lg text-slate-300/90 leading-relaxed font-normal">
            OWLFX diasaskan dengan satu visi yang jelas: memperkasa komuniti Trader di Asia Tenggara melalui capaian kepada alatan dagangan termaju, analitik kuantitatif pintar, serta sokongan modal bertaraf Wall Street — semuanya didokong oleh ekosistem MIB yang terbukti kukuh.
          </p>
        </div>

        {/* Three Institutional Glass Pillars (Static Icons - Zero Spinning) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {pillars.map((pillar) => {
            const Icon = pillar.icon;
            const isSelected = activePillar === pillar.id;

            return (
              <div
                key={pillar.id}
                id={`about-pillar-card-${pillar.id}`}
                onClick={() => setActivePillar(pillar.id)}
                className={`group relative rounded-2xl p-7 transition-all duration-300 cursor-pointer backdrop-blur-xl border select-none ${
                  isSelected
                    ? 'bg-[#0e1626]/80 border-amber-400/80 shadow-[0_20px_50px_rgba(0,0,0,0.6),0_0_25px_rgba(245,158,11,0.2)] -translate-y-2'
                    : 'bg-[#0a0f1d]/60 border-white/10 hover:border-amber-400/50 hover:bg-[#0e1626]/60 hover:-translate-y-1'
                }`}
              >
                {/* Top Badge & Static Icon */}
                <div className="flex items-center justify-between mb-8">
                  <div
                    className={`w-14 h-14 rounded-2xl flex items-center justify-center bg-gradient-to-br ${pillar.accentColor} text-slate-950 font-bold shadow-xl transition-transform duration-300 group-hover:scale-105`}
                  >
                    <Icon className="w-7 h-7" />
                  </div>
                  <span className="text-[10px] font-mono font-bold px-3 py-1.5 rounded-full bg-slate-900/90 border border-slate-800 text-slate-300 tracking-widest uppercase">
                    {pillar.tag}
                  </span>
                </div>

                {/* Content */}
                <h3 className="text-2xl font-bold text-white mb-2 group-hover:text-amber-300 transition-colors">
                  {pillar.title}
                </h3>
                <h4 className="text-xs font-mono text-slate-400 font-bold uppercase tracking-wider mb-5">
                  {pillar.subtitle}
                </h4>
                <p className="text-sm text-slate-300/80 leading-relaxed mb-8">
                  {pillar.description}
                </p>

                {/* Key Bullet Points */}
                <div className="pt-6 border-t border-slate-800/80 space-y-3">
                  {pillar.points.map((pt, idx) => (
                    <div key={idx} className="flex items-start space-x-3 text-xs text-slate-200">
                      <div className="p-0.5 rounded-full bg-amber-500/15 border border-amber-500/30 mt-0.5 shrink-0">
                        <CheckCircle2 className="w-3.5 h-3.5 text-amber-400" />
                      </div>
                      <span className="leading-relaxed">{pt}</span>
                    </div>
                  ))}
                </div>

                {/* Bottom Active Indicator Glow Bar */}
                <div
                  className={`mt-6 h-1 w-full rounded-full transition-all duration-500 ${
                    isSelected
                      ? 'bg-gradient-to-r from-amber-400 via-amber-300 to-amber-500 shadow-[0_0_12px_rgba(245,158,11,0.5)]'
                      : 'bg-white/5 group-hover:bg-white/15'
                  }`}
                />
              </div>
            );
          })}
        </div>

        {/* ========================================================================= */}
        {/* 4. "KOMITMEN STANDARD INSTITUSI GLOBAL" BOX WITH MOVING CHART DYNAMICS   */}
        {/* ========================================================================= */}
        <div className="mt-14 rounded-3xl bg-[#080d19]/90 backdrop-blur-2xl p-6 sm:p-9 border border-[#D4AF37]/35 shadow-[0_15px_40px_rgba(0,0,0,0.85),0_0_25px_rgba(212,175,55,0.12)] flex flex-col md:flex-row items-center justify-between gap-8 relative overflow-hidden">

          {/* Subtle Golden Horizon Accent */}
          <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-[#D4AF37]/70 to-transparent" />

          {/* Embedded Moving Market Trend & Candlestick Stream (Phone & PC Optimized) */}
          <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-25">
            {/* Dynamic Oscillating Candlestick Bars */}
            <div className="absolute inset-0 flex items-end justify-between px-4 pb-1 gap-1">
              {[30, 60, 45, 80, 50, 90, 40, 75, 55, 85, 65, 95, 40, 70, 50, 85, 60, 90, 45, 80, 55, 95, 50, 75].map((h, i) => (
                <motion.div
                  key={i}
                  className="w-[2px] rounded-t-sm"
                  style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
                  animate={{
                    height: [
                      `${Math.max(12, h * 0.25)}%`,
                      `${Math.min(90, h * 0.85)}%`,
                      `${Math.max(18, h * 0.35)}%`
                    ]
                  }}
                  transition={{
                    repeat: Infinity,
                    duration: 1.8 + (i % 4) * 0.25,
                    ease: 'easeInOut',
                    repeatType: 'reverse',
                    delay: i * 0.04
                  }}
                />
              ))}
            </div>

            {/* Continuous Moving Market Wave SVG */}
            <svg
              className="absolute inset-0 w-[200%] h-full stroke-[#D4AF37]/40"
              viewBox="0 0 600 60"
              preserveAspectRatio="none"
            >
              <motion.path
                d="M 0 35 Q 40 10, 80 25 T 160 20 T 240 40 T 320 15 T 400 35 T 480 15 T 560 30 T 640 25 T 720 35"
                fill="none"
                strokeWidth="1.6"
                strokeLinecap="round"
                strokeDasharray="4 2"
                animate={{ x: [0, -300] }}
                transition={{
                  repeat: Infinity,
                  duration: 5,
                  ease: 'linear'
                }}
              />
            </svg>

            {/* Linear Mask for Contrast & High Typography Readability */}
            <div className="absolute inset-0 bg-gradient-to-r from-[#080d19]/90 via-[#080d19]/70 to-[#080d19]/90" />
          </div>

          {/* Left Block: Static Icon + Description */}
          <div className="flex items-center space-x-5 relative z-10 w-full md:w-auto">
            <div className="p-4 rounded-2xl bg-amber-500/10 text-amber-400 border border-amber-500/20 shadow-[0_0_20px_rgba(245,158,11,0.15)] shrink-0">
              <Activity className="w-8 h-8" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h4 className="text-lg font-bold text-white tracking-tight">Komitmen Standard Institusi Global</h4>
                <Sparkles className="w-4 h-4 text-amber-400" />
              </div>
              <p className="text-xs sm:text-sm text-slate-300/80 max-w-md mt-1 font-medium leading-relaxed">
                Setiap peserta komuniti OWLFX dilindungi di bawah garis panduan pengurusan risiko profesional bertaraf antarabangsa.
              </p>
            </div>
          </div>

          {/* Right Block: Audit Status & Overpower Moving Candlestick CTA Button */}
          <div className="flex items-center space-x-6 shrink-0 relative z-10 w-full md:w-auto justify-between md:justify-end">
            <div className="text-right hidden sm:block">
              <span className="block text-[10px] font-mono text-slate-400 font-bold tracking-[0.2em] uppercase">SISTEM AUDIT</span>
              <span className="text-xs font-mono font-bold text-emerald-400 uppercase tracking-widest drop-shadow-[0_0_8px_rgba(52,211,153,0.4)]">
                ● Risk Compliance Aktif
              </span>
            </div>

            {/* Overpower Button with Embedded Moving Candlestick Wave */}
            <Link
              to="/group-support"
              className="group relative w-full sm:w-auto overflow-hidden rounded-xl bg-slate-950/90 border border-[#D4AF37]/30 hover:border-[#D4AF37]/80 px-6 py-3.5 flex items-center justify-center space-x-2.5 shadow-[0_0_18px_rgba(212,175,55,0.15)] hover:shadow-[0_0_26px_rgba(212,175,55,0.3)] transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] select-none"
            >
              {/* Internal Moving Candlestick Wave for Button */}
              <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-60 transition-opacity">
                <div className="absolute inset-0 flex items-end justify-between px-2 pb-1 gap-1">
                  {[35, 70, 45, 80, 50, 95, 40, 75, 55, 90].map((h, i) => (
                    <motion.div
                      key={i}
                      className="w-[2px] rounded-t-sm"
                      style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
                      animate={{
                        height: [
                          `${Math.max(15, h * 0.3)}%`,
                          `${Math.min(95, h * 0.95)}%`,
                          `${Math.max(20, h * 0.45)}%`
                        ]
                      }}
                      transition={{
                        repeat: Infinity,
                        duration: 1.5 + (i % 4) * 0.25,
                        ease: 'easeInOut',
                        repeatType: 'reverse',
                        delay: i * 0.05
                      }}
                    />
                  ))}
                </div>

                <svg
                  className="absolute inset-0 w-[200%] h-full stroke-amber-400"
                  viewBox="0 0 500 50"
                  preserveAspectRatio="none"
                >
                  <motion.path
                    d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
                    fill="none"
                    strokeWidth="1.8"
                    strokeLinecap="round"
                    strokeDasharray="4 2"
                    animate={{ x: [0, -250] }}
                    transition={{
                      repeat: Infinity,
                      duration: 4,
                      ease: 'linear'
                    }}
                  />
                </svg>

                <div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/60 to-slate-950/80" />
              </div>

              {/* Shimmer Specular Light Sweep */}
              <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/20 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

              <span className="relative z-10 text-xs font-mono font-bold uppercase tracking-wider text-slate-200 group-hover:text-white transition-colors">
                Lihat Rekod Prestasi
              </span>
              <ArrowRight className="relative z-10 w-4 h-4 text-[#D4AF37] group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
};
