// Generated by IqwanEngine
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { GraduationCap, Play, ArrowRight, Clock, Sparkles, X } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

interface BasicEducationSectionProps {}

export const BasicEducationSection: React.FC<BasicEducationSectionProps> = () => {
  const { t } = useLanguage();
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [activeEpisode, setActiveEpisode] = useState<number>(0);

  const episodes = [
    {
      id: 0,
      title: "TUTORIAL | Cara Daftar TradingView & Semak Username",
      duration: "2:58",
      youtubeId: "LroOIJXweVk",
      thumbnail: "https://i.imgur.com/Fkg4CSh.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara daftar / buka akaun TradingView ✅ Cara semak TradingView Username."
    },
    {
      id: 1,
      title: "TUTORIAL | Cara Akses Dashboard OWL Algo & Lengkapkan Borang Maklumat",
      duration: "2:08",
      youtubeId: "HILYMsIgM8Q",
      thumbnail: "https://i.imgur.com/EtM8ZTf.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara masuk ke Dashboard OWL Algo Indicator ✅ Cara lengkapkan borang maklumat yang diperlukan."
    },
    {
      id: 2,
      title: "TUTORIAL | Setup TradingView & OWL Algo Indicator — PHONE",
      duration: "29:00",
      youtubeId: "NAotGXx7kKY",
      thumbnail: "https://i.imgur.com/3acp3Ff.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Dalam video ini anda akan belajar cara setup TradingView menggunakan Phone."
    },
    {
      id: 3,
      title: "TUTORIAL | Cara Guna CHOCH BUY & SELL + Tandakan Zone",
      duration: "7:08",
      youtubeId: "X1mIeF8wc7s",
      thumbnail: "https://i.imgur.com/Ee6NjGB.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara kenal pasti CHOCH BUY ✅ Cara kenal pasti CHOCH SELL."
    },
    {
      id: 4,
      title: "TUTORIAL | Cara Guna BOS BUY & SELL + Tandakan Zone",
      duration: "7:25",
      youtubeId: "24llUiECGZs",
      thumbnail: "https://i.imgur.com/YnG9Dgd.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara kenal pasti BOS BUY ✅ Cara kenal pasti BOS SELL."
    },
    {
      id: 5,
      title: "TUTORIAL #07 | Cara Guna Support & Resistance + Tandakan Zone",
      duration: "4:47",
      youtubeId: "TMjjNMpVq0Q",
      thumbnail: "https://i.imgur.com/XGthI3f.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara kenal pasti Support ✅ Cara kenal pasti Resistance."
    },
  ];

  const currentEp = episodes[activeEpisode];

  const handleSelectEpisode = (index: number) => {
    setActiveEpisode(index);
    setIsPlaying(false);
  };

  return (
    <section id="education" className="py-24 relative bg-[#060B14] overflow-hidden">
      {/* Education Theme Ambient Glow */}
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-emerald-500/10 blur-[120px] rounded-full pointer-events-none -z-10" />
      <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-blue-600/10 blur-[120px] rounded-full pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-mono mb-4 shadow-[0_0_15px_rgba(16,185,129,0.15)]">
            <GraduationCap className="w-3.5 h-3.5 text-emerald-400" />
            <span>{t.education.badge}</span>
          </div>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-white tracking-tight">
            {t.education.title1}{' '}
            <span className="bg-gradient-to-r from-emerald-400 via-teal-300 to-blue-500 bg-clip-text text-transparent">
              {t.education.title2}
            </span>
          </h2>
          <p className="mt-4 text-slate-300 text-sm sm:text-base leading-relaxed">
            {t.education.description}
          </p>
        </div>

        {/* Step-by-Step Roadmap (3 Strategic Steps) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          {/* Step 1 */}
          <div className="p-6 rounded-2xl bg-[#0A101D]/75 backdrop-blur-xl border border-white/10 hover:border-[#D4AF37]/50 transition-all duration-500 hover:-translate-y-1.5 shadow-xl hover:shadow-[0_15px_30px_rgba(0,0,0,0.5)] relative group">
            <div className="flex items-center justify-between mb-4">
              <span className="px-2.5 py-1 rounded-md bg-[#D4AF37]/20 text-[#D4AF37] font-mono text-xs font-bold border border-[#D4AF37]/30">
                {t.education.step1Badge}
              </span>
              <span className="text-xs font-mono text-slate-500">{t.education.step1Time}</span>
            </div>
            <h3 className="text-lg font-bold text-white mb-2 group-hover:text-[#D4AF37] transition-colors">
              {t.education.step1Title}
            </h3>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-4">
              {t.education.step1Desc}
            </p>
            <div className="pt-3 border-t border-white/5 flex items-center justify-between text-xs font-mono text-slate-400">
              <span className="text-emerald-400 font-bold">{t.education.step1Perk}</span>
              <a
                href="/my/register"
                target="_blank"
                rel="noopener noreferrer"
                className="group/link text-[#D4AF37] hover:text-amber-300 font-bold flex items-center space-x-1 cursor-pointer transition-colors"
              >
                <span>{t.education.step1Action}</span>
                <ArrowRight className="w-3.5 h-3.5 group-hover/link:translate-x-1.5 transition-transform duration-300" />
              </a>
            </div>
          </div>

          {/* Step 2 */}
          <div className="p-6 rounded-2xl bg-[#0A101D]/75 backdrop-blur-xl border border-white/10 hover:border-[#38BDF8]/50 transition-all duration-500 hover:-translate-y-1.5 shadow-xl hover:shadow-[0_15px_30px_rgba(0,0,0,0.5)] relative group">
            <div className="flex items-center justify-between mb-4">
              <span className="px-2.5 py-1 rounded-md bg-[#2563EB]/20 text-[#60A5FA] font-mono text-xs font-bold border border-[#2563EB]/30">
                {t.education.step2Badge}
              </span>
              <span className="text-xs font-mono text-slate-500">{t.education.step2Time}</span>
            </div>
            <h3 className="text-lg font-bold text-white mb-2 group-hover:text-[#38BDF8] transition-colors">
              {t.education.step2Title}
            </h3>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-4">
              {t.education.step2Desc}
            </p>
            <div className="pt-3 border-t border-white/5 flex items-center justify-between text-xs font-mono text-slate-400">
              <span className="text-sky-400 font-bold">{t.education.step2Perk}</span>
              <span className="text-slate-500">Auto Pinned</span>
            </div>
          </div>

          {/* Step 3 */}
          <div className="p-6 rounded-2xl bg-[#0A101D]/75 backdrop-blur-xl border border-white/10 hover:border-emerald-500/50 transition-all duration-500 hover:-translate-y-1.5 shadow-xl hover:shadow-[0_15px_30px_rgba(0,0,0,0.5)] relative group">
            <div className="flex items-center justify-between mb-4">
              <span className="px-2.5 py-1 rounded-md bg-emerald-500/20 text-emerald-400 font-mono text-xs font-bold border border-emerald-500/30">
                {t.education.step3Badge}
              </span>
              <span className="text-xs font-mono text-slate-500">{t.education.step3Time}</span>
            </div>
            <h3 className="text-lg font-bold text-white mb-2 group-hover:text-emerald-400 transition-colors">
              {t.education.step3Title}
            </h3>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-4">
              {t.education.step3Desc}
            </p>
            <div className="pt-3 border-t border-white/5 flex items-center justify-between text-xs font-mono text-slate-400">
              <span className="text-emerald-400 font-bold">{t.education.step3Perk}</span>
              <span className="text-slate-500">Drawdown &lt; 5%</span>
            </div>
          </div>
        </div>

        {/* Modern Video Player Container */}
        <div className="rounded-3xl bg-[#090E1D] border border-white/10 p-6 sm:p-8 shadow-2xl overflow-hidden">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            {/* Interactive Player Screen */}
            <div className="lg:col-span-8">
              <div className="relative rounded-2xl overflow-hidden border border-white/10 shadow-2xl aspect-video bg-black group select-none">
                {isPlaying ? (
                  <div className="w-full h-full relative">
                    <iframe
                      className="w-full h-full absolute inset-0 border-0"
                      src={`https://www.youtube-nocookie.com/embed/${currentEp.youtubeId}?autoplay=1&rel=0&modestbranding=1&controls=1&iv_load_policy=3`}
                      title={currentEp.title}
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                      allowFullScreen
                    />
                    {/* Close / Return to poster button */}
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        setIsPlaying(false);
                      }}
                      className="absolute top-4 right-4 z-30 px-3.5 py-1.5 rounded-xl bg-slate-900/90 hover:bg-slate-800 text-slate-200 hover:text-white border border-white/20 text-xs font-mono flex items-center space-x-1.5 shadow-xl transition-all cursor-pointer"
                    >
                      <X className="w-4 h-4 text-rose-400" />
                      <span>Tutup Video</span>
                    </button>
                  </div>
                ) : (
                  <div
                    className="relative w-full h-full cursor-pointer"
                    onClick={() => setIsPlaying(true)}
                  >
                    <img
                      src={currentEp.thumbnail}
                      alt={currentEp.title}
                      className="w-full h-full object-cover brightness-90 group-hover:scale-105 transition-all duration-700"
                    />

                    {/* Dark gradient overlay */}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-black/20" />

                    {/* Center Quantum Pulse Trigger Play Button */}
                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
                      <div className="absolute -inset-3 rounded-full bg-emerald-400/30 animate-ping pointer-events-none" />
                      <div className="relative w-20 h-20 sm:w-24 sm:h-24 rounded-full bg-gradient-to-tr from-emerald-600 via-emerald-500 to-cyan-400 text-slate-950 flex items-center justify-center shadow-[0_0_35px_rgba(16,185,129,0.5)] group-hover:scale-110 active:scale-95 transition-all duration-300">
                        <Play className="w-9 h-9 fill-slate-950 ml-1" />
                      </div>
                    </div>

                    {/* Video Info Watermark Header */}
                    <div className="absolute top-4 left-4 right-4 flex items-center justify-between z-10 pointer-events-none">
                      <div className="flex items-center space-x-2">
                        <span className="px-2.5 py-1 rounded bg-black/70 backdrop-blur-md text-[11px] font-mono text-[#D4AF37] border border-white/10">
                          OWLFX MASTERCLASS // 4K STREAM
                        </span>
                        <span className="text-xs font-mono text-white/90 drop-shadow px-2 py-0.5 rounded bg-black/50">
                          {currentEp.duration}
                        </span>
                      </div>
                    </div>

                    {/* Bottom Video Poster Overlay Details */}
                    <div className="absolute bottom-4 left-4 right-4 z-10 pointer-events-none">
                      <h4 className="text-base sm:text-lg font-bold text-white drop-shadow-md">
                        {currentEp.title}
                      </h4>
                      <p className="text-xs text-slate-300 drop-shadow mt-1 line-clamp-1">
                        {currentEp.description}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Episode Selector / Masterclass Playlist */}
            <div className="lg:col-span-4 space-y-4">
              <div className="flex items-center justify-between pb-2 border-b border-white/10">
                <span className="text-xs font-mono text-[#D4AF37] font-bold uppercase tracking-wider">
                  E-BOOK (Cara Memahami Dan Pendaftaran OWLALGO)
                </span>
                <span className="text-xs font-mono text-slate-400">Terperinci</span>
              </div>

              <div className="space-y-2.5">
                {episodes.map((ep, idx) => {
                  const isActive = activeEpisode === idx;
                  return (
                    <button
                      key={ep.id}
                      type="button"
                      onClick={() => handleSelectEpisode(idx)}
                      className={`w-full p-3.5 sm:p-4 rounded-xl text-left transition-all border flex items-center space-x-3 cursor-pointer ${
                        isActive
                          ? 'bg-slate-800/90 border-emerald-500 text-white shadow-[0_0_20px_rgba(16,185,129,0.15)]'
                          : 'bg-slate-900/60 border-white/5 text-slate-400 hover:text-slate-200 hover:bg-slate-850'
                      }`}
                    >
                      <div
                        className={`p-2.5 rounded-lg shrink-0 flex items-center justify-center ${
                          isActive
                            ? 'bg-emerald-500 text-slate-950 font-bold'
                            : 'bg-slate-800 text-slate-400'
                        }`}
                      >
                        {isActive && isPlaying ? (
                          /* Mini Soundwave Equalizer Bars */
                          <div className="flex items-end space-x-0.5 h-3.5 w-3.5">
                            <motion.span
                              className="w-1 bg-slate-950 rounded-t"
                              animate={{ height: ['40%', '100%', '60%'] }}
                              transition={{ repeat: Infinity, duration: 0.6 }}
                            />
                            <motion.span
                              className="w-1 bg-slate-950 rounded-t"
                              animate={{ height: ['80%', '30%', '100%'] }}
                              transition={{ repeat: Infinity, duration: 0.4 }}
                            />
                            <motion.span
                              className="w-1 bg-slate-950 rounded-t"
                              animate={{ height: ['50%', '90%', '40%'] }}
                              transition={{ repeat: Infinity, duration: 0.5 }}
                            />
                          </div>
                        ) : (
                          <Play className="w-3.5 h-3.5 fill-current ml-0.5" />
                        )}
                      </div>

                      <div className="min-w-0 flex-1">
                        <div className="text-xs font-bold text-white truncate">{ep.title}</div>
                        <div className="text-[10px] font-mono text-slate-400 flex items-center space-x-2 mt-1">
                          <Clock className="w-3 h-3 text-emerald-400" />
                          <span>{ep.duration}</span>
                          {isActive && (
                            <span className="text-emerald-400 font-bold">
                              • {isPlaying ? 'Sedang Dimainkan' : 'Sedia Ditonton'}
                            </span>
                          )}
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>

              {/* Ultra-Luxury Liquid Metal CTA Button with Moving Candlestick Wave */}
              <div className="pt-4">
                <a
                  id="education-cta-masterclass-btn"
                  href="/masterclass_registration"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="group relative overflow-hidden px-5 py-4 rounded-2xl text-white font-extrabold text-xs tracking-wider uppercase bg-gradient-to-r from-emerald-600 via-teal-500 to-blue-600 border border-emerald-400/40 flex items-center justify-center space-x-2.5 cursor-pointer shadow-[0_10px_25px_rgba(16,185,129,0.25)] hover:shadow-[0_15px_35px_rgba(16,185,129,0.45)] hover:scale-[1.02] active:scale-[0.98] transition-all select-none"
                >
                  {/* Dynamic Candlestick Bars Wave in Background */}
                  <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-50 transition-opacity">
                    <div className="absolute inset-0 flex items-end justify-between px-3 pb-1 gap-1">
                      {[40, 75, 45, 85, 55, 95, 35, 80, 50, 90, 60, 75, 45, 85].map((h, i) => (
                        <motion.div
                          key={i}
                          className="w-[2px] rounded-t-sm"
                          style={{ backgroundColor: i % 2 === 0 ? '#A7F3D0' : '#FECDD3' }}
                          animate={{
                            height: [
                              `${Math.max(15, h * 0.3)}%`,
                              `${Math.min(95, h * 0.95)}%`,
                              `${Math.max(20, h * 0.45)}%`
                            ]
                          }}
                          transition={{
                            repeat: Infinity,
                            duration: 1.5 + (i % 4) * 0.25,
                            ease: 'easeInOut',
                            repeatType: 'reverse',
                            delay: i * 0.05
                          }}
                        />
                      ))}
                    </div>

                    {/* Continuous Moving Market Line Wave */}
                    <svg
                      className="absolute inset-0 w-[200%] h-full stroke-emerald-200"
                      viewBox="0 0 500 50"
                      preserveAspectRatio="none"
                    >
                      <motion.path
                        d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
                        fill="none"
                        strokeWidth="1.6"
                        strokeLinecap="round"
                        strokeDasharray="4 2"
                        animate={{ x: [0, -250] }}
                        transition={{
                          repeat: Infinity,
                          duration: 4,
                          ease: 'linear'
                        }}
                      />
                    </svg>
                  </div>

                  {/* Shimmer Light Sweep */}
                  <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/30 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

                  <Sparkles className="relative z-10 w-4 h-4 text-white shrink-0" />
                  <span className="relative z-10 drop-shadow-sm font-bold">
                    {t.education.btnMasterclass}
                  </span>
                  <ArrowRight className="relative z-10 w-4 h-4 text-emerald-200 group-hover:translate-x-1.5 transition-transform duration-300 shrink-0" />
                </a>
                <p className="text-[11px] text-center text-slate-400 mt-2 font-mono">
                  {t.education.masterclassSub}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
