// Generated by IqwanEngine
import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { GraduationCap, Play, ArrowRight, Clock, Sparkles, X, Download, BookOpen, ChevronRight, Check } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

// =========================================================
// KOMPONEN: SlideDownloadButton (Untuk E-Book)
// =========================================================
interface SlideDownloadButtonProps {
  title: string;
  fileUrl: string;
  fileName: string;
}

const SlideDownloadButton: React.FC<SlideDownloadButtonProps> = ({ title, fileUrl, fileName }) => {
  const [dragProgress, setDragProgress] = useState<number>(0);
  const [isCompleted, setIsCompleted] = useState<boolean>(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const isDragging = useRef<boolean>(false);

  const startDrag = () => {
    if (isCompleted) return;
    isDragging.current = true;
  };

  const onDrag = (clientX: number) => {
    if (!isDragging.current || !containerRef.current || isCompleted) return;
    const rect = containerRef.current.getBoundingClientRect();
    const knobWidth = 48; // Lebar tombol (48px)
    const maxDrag = rect.width - knobWidth - 8;
    const currentPos = clientX - rect.left - knobWidth / 2;
    const progress = Math.min(Math.max(currentPos / maxDrag, 0), 1);

    setDragProgress(progress * 100);

    if (progress >= 0.95) {
      triggerDownload();
    }
  };

  const stopDrag = () => {
    if (!isDragging.current) return;
    isDragging.current = false;
    if (!isCompleted) {
      setDragProgress(0);
    }
  };

  const triggerDownload = () => {
    isDragging.current = false;
    setIsCompleted(true);
    setDragProgress(100);

    const link = document.createElement("a");
    link.href = fileUrl;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setTimeout(() => {
      setIsCompleted(false);
      setDragProgress(0);
    }, 2500);
  };

  return (
    <div
      ref={containerRef}
      onMouseMove={(e) => onDrag(e.clientX)}
      onMouseUp={stopDrag}
      onMouseLeave={stopDrag}
      onTouchMove={(e) => onDrag(e.touches[0].clientX)}
      onTouchEnd={stopDrag}
      className="group/slider relative flex items-center w-full sm:w-72 h-14 p-1 rounded-2xl bg-gradient-to-b from-[#121826] to-[#0A0E17] border border-[#D4AF37]/30 shadow-[0_4px_20px_rgba(0,0,0,0.5)] hover:shadow-[0_4px_25px_rgba(212,175,55,0.15)] hover:border-[#D4AF37]/60 transition-all duration-300 select-none overflow-hidden cursor-pointer"
    >
      <div
        className="absolute inset-y-0 left-0 bg-gradient-to-r from-[#B8860B]/20 via-[#D4AF37]/40 to-amber-300/50 transition-all duration-75 rounded-xl pointer-events-none"
        style={{ width: `${Math.max(dragProgress, 5)}%` }}
      />

      <div className="absolute inset-0 flex items-center justify-center pointer-events-none px-6">
        <div className="flex items-center space-x-2 transition-opacity duration-200">
          <BookOpen className="w-4 h-4 text-[#D4AF37] group-hover/slider:scale-110 transition-transform duration-300" />
          <span className="text-xs sm:text-sm font-bold tracking-wide text-slate-300 group-hover/slider:text-white transition-colors duration-300">
            {isCompleted ? "DOWNLOADING..." : title}
          </span>
          {!isCompleted && (
            <div className="flex items-center -space-x-1 text-slate-600 group-hover/slider:text-[#D4AF37] transition-colors duration-300">
              <ChevronRight className="w-3.5 h-3.5 animate-pulse" />
              <ChevronRight className="w-3.5 h-3.5 animate-pulse delay-150" />
            </div>
          )}
        </div>
      </div>

      <div
        onMouseDown={startDrag}
        onTouchStart={startDrag}
        style={{
          transform: `translateX(${(dragProgress / 100) * ((containerRef.current?.offsetWidth || 288) - 56)}px)`,
          transition: isDragging.current ? "none" : "transform 0.3s ease-out",
        }}
        className={`relative z-10 flex items-center justify-center w-12 h-12 rounded-xl cursor-grab active:cursor-grabbing shadow-[0_2px_10px_rgba(0,0,0,0.6)] border transition-all duration-300 ${
          isCompleted
            ? "bg-emerald-500 border-emerald-300 text-white"
            : "bg-gradient-to-br from-[#F5D77F] via-[#D4AF37] to-[#8C6B1C] border-[#FFF5C0]/60 text-slate-950 group-hover/slider:shadow-[0_0_20px_rgba(212,175,55,0.7)]"
        }`}
      >
        {isCompleted ? (
          <Check className="w-5 h-5 stroke-[3] scale-110 transition-transform duration-300" />
        ) : (
          <Download
            className={`w-5 h-5 transition-transform duration-300 ease-out ${
              dragProgress > 0
                ? "-rotate-90 scale-110"
                : "group-hover/slider:-rotate-90 group-hover/slider:scale-110"
            }`}
          />
        )}
      </div>
    </div>
  );
};
// =========================================================

interface BasicEducationSectionProps {}

export const BasicEducationSection: React.FC<BasicEducationSectionProps> = () => {
  const { t } = useLanguage();
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [activeEpisode, setActiveEpisode] = useState<number>(0);

  const episodes = [
    {
      id: 0,
      title: "TUTORIAL | Cara Daftar TradingView & Semak Username",
      duration: "2:58",
      youtubeId: "LroOIJXweVk",
      thumbnail: "https://i.imgur.com/Fkg4CSh.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara daftar / buka akaun TradingView ✅ Cara semak TradingView Username."
    },
    {
      id: 1,
      title: "TUTORIAL | Cara Akses Dashboard OWL Algo & Lengkapkan Borang Maklumat",
      duration: "2:08",
      youtubeId: "HILYMsIgM8Q",
      thumbnail: "https://i.imgur.com/EtM8ZTf.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara masuk ke Dashboard OWL Algo Indicator ✅ Cara lengkapkan borang maklumat yang diperlukan."
    },
    {
      id: 2,
      title: "TUTORIAL | Setup TradingView & OWL Algo Indicator — PHONE",
      duration: "29:00",
      youtubeId: "NAotGXx7kKY",
      thumbnail: "https://i.imgur.com/3acp3Ff.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Dalam video ini anda akan belajar cara setup TradingView menggunakan Phone."
    },
    {
      id: 3,
      title: "TUTORIAL | Cara Guna CHOCH BUY & SELL + Tandakan Zone",
      duration: "7:08",
      youtubeId: "X1mIeF8wc7s",
      thumbnail: "https://i.imgur.com/Ee6NjGB.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara kenal pasti CHOCH BUY ✅ Cara kenal pasti CHOCH SELL."
    },
    {
      id: 4,
      title: "TUTORIAL | Cara Guna BOS BUY & SELL + Tandakan Zone",
      duration: "7:25",
      youtubeId: "24llUiECGZs",
      thumbnail: "https://i.imgur.com/YnG9Dgd.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara kenal pasti BOS BUY ✅ Cara kenal pasti BOS SELL."
    },
    {
      id: 5,
      title: "TUTORIAL #07 | Cara Guna Support & Resistance + Tandakan Zone",
      duration: "4:47",
      youtubeId: "TMjjNMpVq0Q",
      thumbnail: "https://i.imgur.com/XGthI3f.jpeg?auto=format&fit=crop&w=1000&q=80",
      description: "✅ Cara kenal pasti Support ✅ Cara kenal pasti Resistance."
    },
  ];

  const currentEp = episodes[activeEpisode];

  const handleSelectEpisode = (index: number) => {
    if (activeEpisode !== index) {
      setActiveEpisode(index);
      setIsPlaying(false);
    }
  };

  return (
    <section id="education" className="py-24 relative bg-[#060B14] overflow-hidden">
      {/* Education Theme Ambient Glow */}
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-emerald-500/10 blur-[120px] rounded-full pointer-events-none -z-10" />
      <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-blue-600/10 blur-[120px] rounded-full pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-mono mb-4 shadow-[0_0_15px_rgba(16,185,129,0.15)]">
            <GraduationCap className="w-3.5 h-3.5 text-emerald-400" />
            <span>{t.education.badge}</span>
          </div>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-white tracking-tight">
            {t.education.title1}{' '}
            <span className="bg-gradient-to-r from-emerald-400 via-teal-300 to-blue-500 bg-clip-text text-transparent">
              {t.education.title2}
            </span>
          </h2>
          <p className="mt-4 text-slate-300 text-sm sm:text-base leading-relaxed">
            {t.education.description}
          </p>
        </div>

        {/* Step-by-Step Roadmap (3 Strategic Steps) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          {/* Step 1 */}
          <div className="p-6 rounded-2xl bg-[#0A101D]/75 backdrop-blur-xl border border-white/10 hover:border-[#D4AF37]/50 transition-all duration-500 hover:-translate-y-1.5 shadow-xl hover:shadow-[0_15px_30px_rgba(0,0,0,0.5)] relative group">
            <div className="flex items-center justify-between mb-4">
              <span className="px-2.5 py-1 rounded-md bg-[#D4AF37]/20 text-[#D4AF37] font-mono text-xs font-bold border border-[#D4AF37]/30">
                {t.education.step1Badge}
              </span>
              <span className="text-xs font-mono text-slate-500">{t.education.step1Time}</span>
            </div>
            <h3 className="text-lg font-bold text-white mb-2 group-hover:text-[#D4AF37] transition-colors">
              {t.education.step1Title}
            </h3>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-4">
              {t.education.step1Desc}
            </p>
            <div className="pt-3 border-t border-white/5 flex items-center justify-between text-xs font-mono text-slate-400">
              <span className="text-emerald-400 font-bold">{t.education.step1Perk}</span>
              <a
                href="/my/register"
                target="_blank"
                rel="noopener noreferrer"
                className="group/link text-[#D4AF37] hover:text-amber-300 font-bold flex items-center space-x-1 cursor-pointer transition-colors"
              >
                <span>{t.education.step1Action}</span>
                <ArrowRight className="w-3.5 h-3.5 group-hover/link:translate-x-1.5 transition-transform duration-300" />
              </a>
            </div>
          </div>

          {/* Step 2 */}
          <div className="p-6 rounded-2xl bg-[#0A101D]/75 backdrop-blur-xl border border-white/10 hover:border-[#38BDF8]/50 transition-all duration-500 hover:-translate-y-1.5 shadow-xl hover:shadow-[0_15px_30px_rgba(0,0,0,0.5)] relative group">
            <div className="flex items-center justify-between mb-4">
              <span className="px-2.5 py-1 rounded-md bg-[#2563EB]/20 text-[#60A5FA] font-mono text-xs font-bold border border-[#2563EB]/30">
                {t.education.step2Badge}
              </span>
              <span className="text-xs font-mono text-slate-500">{t.education.step2Time}</span>
            </div>
            <h3 className="text-lg font-bold text-white mb-2 group-hover:text-[#38BDF8] transition-colors">
              {t.education.step2Title}
            </h3>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-4">
              {t.education.step2Desc}
            </p>
            <div className="pt-3 border-t border-white/5 flex items-center justify-between text-xs font-mono text-slate-400">
              <span className="text-sky-400 font-bold">{t.education.step2Perk}</span>
              <button
                type="button"
                onClick={() => {
                  document.getElementById('ebook-section')?.scrollIntoView({
                    behavior: 'smooth',
                    block: 'center' // Meletakkan elemen betul-betul di tengah paparan skrin
                  });
                }}
                className="group/link text-slate-500 hover:text-sky-400 font-bold flex items-center space-x-1 cursor-pointer transition-colors"
              >
                <span>Go to E-Book</span>
                <ArrowRight className="w-3.5 h-3.5 group-hover/link:translate-x-1.5 transition-transform duration-300" />
              </button>
            </div>
          </div>

          {/* Step 3 */}
          <div className="p-6 rounded-2xl bg-[#0A101D]/75 backdrop-blur-xl border border-white/10 hover:border-emerald-500/50 transition-all duration-500 hover:-translate-y-1.5 shadow-xl hover:shadow-[0_15px_30px_rgba(0,0,0,0.5)] relative group">
            <div className="flex items-center justify-between mb-4">
              <span className="px-2.5 py-1 rounded-md bg-emerald-500/20 text-emerald-400 font-mono text-xs font-bold border border-emerald-500/30">
                {t.education.step3Badge}
              </span>
              <span className="text-xs font-mono text-slate-500">{t.education.step3Time}</span>
            </div>
            <h3 className="text-lg font-bold text-white mb-2 group-hover:text-emerald-400 transition-colors">
              {t.education.step3Title}
            </h3>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-4">
              {t.education.step3Desc}
            </p>
            <div className="pt-3 border-t border-white/5 flex items-center justify-between text-xs font-mono text-slate-400">
              <span className="text-emerald-400 font-bold">{t.education.step3Perk}</span>
              <span className="text-slate-500">Drawdown &lt; 5%</span>
            </div>
          </div>
        </div>

        {/* ========================================================= */}
        {/* PREMIUM UPGRADE: Modern Video Player Container */}
        {/* ========================================================= */}
        <div className="rounded-3xl bg-gradient-to-b from-[#090E1D] to-[#060A14] border border-white/10 p-5 sm:p-8 shadow-2xl overflow-hidden relative">

          {/* Subtle Background Accent */}
          <div className="absolute -top-40 -right-40 w-96 h-96 bg-emerald-500/10 blur-[100px] rounded-full pointer-events-none" />

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8 items-start relative z-10">

            {/* Bahagian Kiri: Tajuk (Kotak Merah) & Video Utama */}
            <div className="lg:col-span-8 flex flex-col gap-5 lg:gap-6">

              {/* DI SINI: Header Utama Video Dimasukkan ke dalam Lajur Kiri */}
              <div className="relative z-10 border-b border-white/5 pb-4 lg:pb-5">
                <div className="inline-flex items-center space-x-2 px-3 py-1.5 rounded-md bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-[10px] sm:text-xs font-mono font-bold mb-3 shadow-[0_0_15px_rgba(16,185,129,0.1)]">
                  <GraduationCap className="w-3.5 h-3.5" />
                  <span>PANDUAN OWLALGO</span>
                </div>
                <h3 className="text-2xl sm:text-3xl md:text-4xl font-extrabold text-white tracking-tight mb-2">
                  Video Panduan Pendaftaran & Pengenalan Platform
                </h3>
                <p className="text-sm sm:text-base text-slate-400 max-w-3xl leading-relaxed">
                  Ketahui langkah demi langkah bermula dari proses pendaftaran sehingga anda mahir mengendalikan platform. Tonton video tutorial di bawah untuk bermula.
                </p>
              </div>

              {/* Interactive Player Screen */}
              <div className="relative rounded-2xl overflow-hidden border border-white/10 shadow-[0_10px_40px_rgba(0,0,0,0.8)] aspect-video bg-black group select-none ring-1 ring-white/5">
                <AnimatePresence mode="wait">
                  {isPlaying ? (
                    <motion.div
                      key="iframe-player"
                      initial={{ opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.95 }}
                      transition={{ duration: 0.4, ease: "easeOut" }}
                      className="w-full h-full relative"
                    >
                      <iframe
                        className="w-full h-full absolute inset-0 border-0"
                        src={`https://www.youtube-nocookie.com/embed/${currentEp.youtubeId}?autoplay=1&rel=0&modestbranding=1&controls=1&iv_load_policy=3`}
                        title={currentEp.title}
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                      />
                      {/* Close / Return to poster button */}
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          setIsPlaying(false);
                        }}
                        className="absolute top-4 right-4 z-30 px-3.5 py-2 rounded-xl bg-slate-900/90 hover:bg-rose-500/20 text-slate-200 hover:text-white border border-white/20 hover:border-rose-500/50 text-xs font-mono flex items-center space-x-1.5 shadow-xl transition-all duration-300 cursor-pointer backdrop-blur-md group/close"
                      >
                        <X className="w-4 h-4 text-rose-400 group-hover/close:rotate-90 transition-transform duration-300" />
                        <span>Tutup Video</span>
                      </button>
                    </motion.div>
                  ) : (
                    <motion.div
                      key={`poster-${currentEp.id}`}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      transition={{ duration: 0.5 }}
                      className="relative w-full h-full cursor-pointer"
                      onClick={() => setIsPlaying(true)}
                    >
                      <img
                        src={currentEp.thumbnail}
                        alt={currentEp.title}
                        className="w-full h-full object-cover brightness-75 group-hover:brightness-90 group-hover:scale-105 transition-all duration-700"
                      />

                      {/* Dark gradient overlay */}
                      <div className="absolute inset-0 bg-gradient-to-t from-[#060A14] via-[#060A14]/40 to-transparent opacity-90" />

                      {/* Center Quantum Pulse Trigger Play Button */}
                      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
                        {/* Multi-Ring Pulse Effect */}
                        <div className="absolute -inset-4 rounded-full bg-emerald-400/20 animate-[ping_2s_cubic-bezier(0,0,0.2,1)_infinite] pointer-events-none" />
                        <div className="absolute -inset-8 rounded-full bg-emerald-400/10 animate-[ping_3s_cubic-bezier(0,0,0.2,1)_infinite] pointer-events-none" />

                        <div className="relative w-16 h-16 sm:w-20 sm:h-20 md:w-24 md:h-24 rounded-full bg-gradient-to-tr from-emerald-600 via-emerald-500 to-cyan-400 text-slate-950 flex items-center justify-center shadow-[0_0_35px_rgba(16,185,129,0.5)] group-hover:shadow-[0_0_50px_rgba(16,185,129,0.7)] group-hover:scale-110 active:scale-95 transition-all duration-300 backdrop-blur-sm border border-emerald-300/50">
                          <Play className="w-8 h-8 md:w-9 md:h-9 fill-slate-950 ml-1.5 drop-shadow-md" />
                        </div>
                      </div>

                      {/* Video Info Watermark Header */}
                      <div className="absolute top-4 left-4 sm:top-5 sm:left-5 right-4 sm:right-5 flex items-center justify-between z-10 pointer-events-none">
                        <div className="flex items-center space-x-3">
                          <span className="px-2.5 py-1.5 sm:px-3 sm:py-1.5 rounded-lg bg-black/70 backdrop-blur-md text-[9px] sm:text-[11px] font-mono text-[#D4AF37] border border-[#D4AF37]/30 shadow-lg tracking-wider">
                            OWLFX MASTERCLASS
                          </span>
                          <span className="text-[10px] sm:text-xs font-mono text-white/90 drop-shadow flex items-center space-x-1.5 bg-black/50 px-2 py-1.5 sm:px-2.5 rounded-lg border border-white/10 backdrop-blur-md">
                            <Clock className="w-3.5 h-3.5 text-emerald-400" />
                            <span>{currentEp.duration}</span>
                          </span>
                        </div>
                      </div>

                      {/* Bottom Video Poster Overlay Details */}
                      <div className="absolute bottom-5 left-5 right-5 sm:bottom-6 sm:left-6 sm:right-6 z-10 pointer-events-none">
                        <motion.h4
                          initial={{ y: 20, opacity: 0 }}
                          animate={{ y: 0, opacity: 1 }}
                          transition={{ delay: 0.2 }}
                          className="text-lg sm:text-xl md:text-2xl font-bold text-white drop-shadow-lg leading-tight"
                        >
                          {currentEp.title}
                        </motion.h4>
                        <motion.p
                          initial={{ y: 20, opacity: 0 }}
                          animate={{ y: 0, opacity: 1 }}
                          transition={{ delay: 0.3 }}
                          className="text-xs sm:text-sm text-slate-300 drop-shadow mt-2 max-w-2xl line-clamp-2"
                        >
                          {currentEp.description}
                        </motion.p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>

            {/* Bahagian Kanan: Episode Selector / Masterclass Playlist (Kotak Kuning) */}
            <div className="lg:col-span-4 flex flex-col h-full mt-4 lg:mt-0">
              <div className="flex items-center justify-between pb-3 mb-4 border-b border-white/10 shrink-0">
                <span className="text-[11px] sm:text-xs font-mono text-[#D4AF37] font-bold uppercase tracking-wider flex items-center gap-2">
                  <Play className="w-3 h-3" /> E-BOOK (Pendaftaran OWLALGO)
                </span>
                <span className="text-[10px] sm:text-xs font-mono text-slate-400 bg-white/5 px-2 py-1 rounded">Tutorial</span>
              </div>

              {/* Scrollable Playlist Container (Ditingkatkan max-height supaya memanjang ke bawah) */}
              <div className="flex-1 overflow-y-auto max-h-[450px] lg:max-h-[550px] space-y-3 pr-2 [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-track]:bg-white/5 [&::-webkit-scrollbar-track]:rounded-full [&::-webkit-scrollbar-thumb]:bg-slate-700 hover:[&::-webkit-scrollbar-thumb]:bg-emerald-500/50 [&::-webkit-scrollbar-thumb]:rounded-full transition-colors">
                {episodes.map((ep, idx) => {
                  const isActive = activeEpisode === idx;
                  return (
                    <motion.button
                      key={ep.id}
                      type="button"
                      whileHover={{ scale: 1.01, x: 2 }}
                      whileTap={{ scale: 0.98 }}
                      onClick={() => handleSelectEpisode(idx)}
                      className={`w-full p-3.5 sm:p-4 rounded-xl text-left transition-all border flex items-start space-x-3 cursor-pointer group relative overflow-hidden ${
                        isActive
                          ? 'bg-gradient-to-r from-emerald-900/40 to-slate-800/90 border-emerald-500/50 shadow-[0_0_20px_rgba(16,185,129,0.1)]'
                          : 'bg-slate-900/60 border-white/5 hover:border-white/10 hover:bg-slate-800/80'
                      }`}
                    >
                      {/* Active Indicator Line */}
                      {isActive && (
                        <motion.div
                          layoutId="activePlaylistGlow"
                          className="absolute left-0 top-0 bottom-0 w-1 bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,1)]"
                        />
                      )}

                      <div
                        className={`mt-0.5 p-2 rounded-lg shrink-0 flex items-center justify-center transition-colors ${
                          isActive
                            ? 'bg-emerald-500 text-slate-950 shadow-[0_0_15px_rgba(16,185,129,0.4)]'
                            : 'bg-slate-800 text-slate-400 group-hover:bg-slate-700 group-hover:text-white'
                        }`}
                      >
                        {isActive && isPlaying ? (
                          <div className="flex items-end space-x-0.5 h-3.5 w-3.5">
                            <motion.span className="w-1 bg-slate-950 rounded-t" animate={{ height: ['40%', '100%', '60%'] }} transition={{ repeat: Infinity, duration: 0.6 }} />
                            <motion.span className="w-1 bg-slate-950 rounded-t" animate={{ height: ['80%', '30%', '100%'] }} transition={{ repeat: Infinity, duration: 0.4 }} />
                            <motion.span className="w-1 bg-slate-950 rounded-t" animate={{ height: ['50%', '90%', '40%'] }} transition={{ repeat: Infinity, duration: 0.5 }} />
                          </div>
                        ) : (
                          <Play className="w-3.5 h-3.5 fill-current ml-0.5" />
                        )}
                      </div>

                      <div className="min-w-0 flex-1">
                        <div className={`text-xs sm:text-sm font-bold line-clamp-2 transition-colors ${isActive ? 'text-white' : 'text-slate-300 group-hover:text-white'}`}>
                          {ep.title}
                        </div>
                        <div className="text-[10px] sm:text-xs font-mono text-slate-400 flex items-center space-x-2 mt-1.5">
                          <span className={`flex items-center space-x-1 ${isActive ? 'text-emerald-400' : ''}`}>
                            <Clock className="w-3 h-3" />
                            <span>{ep.duration}</span>
                          </span>
                          {isActive && (
                            <span className="text-emerald-400 font-bold opacity-80">
                              • {isPlaying ? 'Sedang Dimainkan' : 'Sedia Ditonton'}
                            </span>
                          )}
                        </div>
                      </div>
                    </motion.button>
                  );
                })}
              </div>

              {/* Ultra-Luxury Liquid Metal CTA Button with Moving Candlestick Wave */}
              <div className="pt-5 mt-auto shrink-0 border-t border-white/5">
                <a
                  id="education-cta-masterclass-btn"
                  href="/masterclass_registration"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="group relative overflow-hidden px-5 py-4 rounded-2xl text-white font-extrabold text-xs tracking-wider uppercase bg-gradient-to-r from-emerald-600 via-teal-500 to-blue-600 border border-emerald-400/40 flex items-center justify-center space-x-2.5 cursor-pointer shadow-[0_10px_25px_rgba(16,185,129,0.25)] hover:shadow-[0_15px_35px_rgba(16,185,129,0.45)] hover:-translate-y-1 active:scale-[0.98] active:translate-y-0 transition-all duration-300 select-none"
                >
                  <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-50 transition-opacity">
                    <div className="absolute inset-0 flex items-end justify-between px-3 pb-1 gap-1">
                      {[40, 75, 45, 85, 55, 95, 35, 80, 50, 90, 60, 75, 45, 85].map((h, i) => (
                        <motion.div
                          key={i}
                          className="w-[2px] rounded-t-sm"
                          style={{ backgroundColor: i % 2 === 0 ? '#A7F3D0' : '#FECDD3' }}
                          animate={{ height: [`${Math.max(15, h * 0.3)}%`, `${Math.min(95, h * 0.95)}%`, `${Math.max(20, h * 0.45)}%`] }}
                          transition={{ repeat: Infinity, duration: 1.5 + (i % 4) * 0.25, ease: 'easeInOut', repeatType: 'reverse', delay: i * 0.05 }}
                        />
                      ))}
                    </div>
                    <svg className="absolute inset-0 w-[200%] h-full stroke-emerald-200" viewBox="0 0 500 50" preserveAspectRatio="none">
                      <motion.path d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30" fill="none" strokeWidth="1.6" strokeLinecap="round" strokeDasharray="4 2" animate={{ x: [0, -250] }} transition={{ repeat: Infinity, duration: 4, ease: 'linear' }} />
                    </svg>
                  </div>
                  <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/30 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

                  <Sparkles className="relative z-10 w-4 h-4 text-white shrink-0" />
                  <span className="relative z-10 drop-shadow-sm font-bold">{t.education.btnMasterclass}</span>
                  <ArrowRight className="relative z-10 w-4 h-4 text-emerald-200 group-hover:translate-x-1.5 transition-transform duration-300 shrink-0" />
                </a>
                <p className="text-[10px] text-center text-slate-500 mt-3 font-mono">
                  {t.education.masterclassSub}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* ========================================================= */}
        {/* SECTION: E-BOOK OWLALGO */}
        {/* ========================================================= */}
        <div id="ebook-section" className="mt-8 rounded-3xl bg-[#090E1D]/90 backdrop-blur-xl border border-white/10 hover:border-[#D4AF37]/30 transition-colors duration-500 p-6 sm:p-8 shadow-2xl overflow-hidden relative group">
          <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-[#D4AF37]/10 blur-[120px] rounded-full pointer-events-none -z-10 transition-opacity duration-700 opacity-50 group-hover:opacity-100" />
          <div className="absolute bottom-0 left-0 w-full h-[2px] bg-gradient-to-r from-transparent via-[#D4AF37]/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-8 relative z-10">
            <div className="flex-1">
              <div className="inline-flex items-center space-x-2 px-3 py-1.5 rounded-md bg-[#D4AF37]/10 border border-[#D4AF37]/30 text-[#D4AF37] text-xs font-mono font-bold mb-3 shadow-[0_0_15px_rgba(212,175,55,0.1)] group-hover:bg-[#D4AF37]/20 transition-colors duration-300">
                <BookOpen className="w-3.5 h-3.5" />
                <span>MATERIAL VIP OWLFX</span>
              </div>
              <h3 className="text-2xl sm:text-3xl font-extrabold text-white mb-2 tracking-tight">
                E-BOOK{" "}
                <span className="relative inline-block bg-[linear-gradient(110deg,#BF953F,30%,#FFFFFF,50%,#AA771C,70%,#E2E8F0)] bg-[length:200%_100%] bg-clip-text text-transparent animate-[shine_4s_ease-in-out_infinite] drop-shadow-[0_0_12px_rgba(255,255,255,0.4)]">
                  OWLALGO
                </span>
              </h3>
              <p className="text-slate-400 text-sm sm:text-base max-w-2xl leading-relaxed">
                Tingkatkan kemahiran analisis anda melalui e-book panduan rasmi OwlAlgo. Pelajari langkah demi langkah dari pemahaman asas sehingga cara mengenal pasti signal dan setup berkualiti tinggi.
              </p>
            </div>

            <div className="flex flex-col w-full lg:w-auto shrink-0 gap-3 mt-4 lg:mt-0">
              <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 w-full justify-center">
                <SlideDownloadButton
                  title="E-BOOK: INTRODUCTION"
                  fileUrl="/INTRODUCTION EBOOK OWL ALGO.pdf"
                  fileName="INTRODUCTION EBOOK OWL ALGO.pdf"
                />
                <SlideDownloadButton
                  title="E-BOOK: EDUCATION"
                  fileUrl="/EDUCATION EBOOK OWL ALGO.pdf"
                  fileName="EDUCATION EBOOK OWL ALGO.pdf"
                />
              </div>

              <div className="w-full flex items-center justify-center space-x-2 text-[10px] sm:text-xs text-slate-400 font-mono px-4 py-2.5 rounded-xl bg-white/[0.03] border border-white/5 backdrop-blur-md mt-1">
                <Sparkles className="w-3.5 h-3.5 text-[#D4AF37] animate-pulse shrink-0" />
                <span className="text-center">
                  Slide tombol download ke kanan <span className="text-[#D4AF37] font-bold mx-0.5">(&rarr;)</span> untuk muat turun/download e-book.
                </span>
              </div>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
};
