// Generated by IqwanEngine
import React from 'react';
import { CommunityLinks } from '../types';
import { Send, MessageCircle, Video, Youtube, Instagram, Lock, ArrowUp, Activity } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

interface CommunityFooterSectionProps {
  communityLinks: CommunityLinks;
  onOpenAdmin: () => void;
}

interface MovingCandlestickFooterButtonProps {
  id?: string;
  href: string;
  label: string;
  icon: React.ReactNode;
  variant: 'gold' | 'cyan';
}

/**
 * Clean Borderless Institutional Footer Button with Embedded Moving Candlestick/Wave Chart
 * Exterior conic-border wrapper and border-cyan-500/40 completely eliminated per specification.
 */
function FooterCandlestickButton({ id, href, label, icon, variant }: MovingCandlestickFooterButtonProps) {
  const isGold = variant === 'gold';
  const strokeColor = isGold ? '#F59E0B' : '#06B6D4';

  return (
    <a
      id={id}
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="group relative overflow-hidden rounded-2xl transition-all duration-500 hover:scale-[1.03] active:scale-[0.97] cursor-pointer block select-none border-none outline-none focus:outline-none"
    >
      <div
        className={`relative px-6 py-3.5 rounded-2xl flex items-center justify-center space-x-2.5 overflow-hidden shadow-[0_10px_30px_rgba(0,0,0,0.7)] border-none outline-none ${
          isGold
            ? 'bg-gradient-to-r from-amber-500 via-amber-400 to-[#D4AF37] text-slate-950 font-black'
            : 'bg-gradient-to-r from-slate-950 via-slate-900 to-slate-950 text-white font-bold'
        }`}
      >
        {/* Dynamic Candlestick Bars Wave in Background */}
        <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-60 transition-opacity">
          <div className="absolute inset-0 flex items-end justify-between px-3 pb-1 gap-1">
            {[40, 75, 45, 85, 55, 95, 35, 80, 50, 90, 60, 75].map((h, i) => (
              <motion.div
                key={i}
                className="w-[2px] rounded-t-sm"
                style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
                animate={{
                  height: [
                    `${Math.max(15, h * 0.3)}%`,
                    `${Math.min(95, h * 0.95)}%`,
                    `${Math.max(20, h * 0.45)}%`
                  ]
                }}
                transition={{
                  repeat: Infinity,
                  duration: 1.5 + (i % 4) * 0.25,
                  ease: 'easeInOut',
                  repeatType: 'reverse',
                  delay: i * 0.05
                }}
              />
            ))}
          </div>

          {/* Dynamic Continuous Moving Market Line Wave */}
          <svg
            className="absolute inset-0 w-[200%] h-full stroke-current"
            style={{ color: strokeColor }}
            viewBox="0 0 500 50"
            preserveAspectRatio="none"
          >
            <motion.path
              d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
              fill="none"
              strokeWidth="1.8"
              strokeLinecap="round"
              strokeDasharray="4 2"
              animate={{ x: [0, -250] }}
              transition={{
                repeat: Infinity,
                duration: 4,
                ease: 'linear'
              }}
            />
          </svg>

          <div
            className={`absolute inset-0 ${
              isGold
                ? 'bg-gradient-to-r from-amber-400/80 via-amber-300/60 to-amber-500/90'
                : 'bg-gradient-to-r from-slate-950/90 via-cyan-950/50 to-slate-950/90'
            }`}
          />
        </div>

        {/* Shimmer Specular Light Sweep */}
        <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/30 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

        {/* Button Content */}
        <div className="relative z-10 flex items-center justify-center">
          {icon}
        </div>
        <span className="relative z-10 font-mono text-xs tracking-wider uppercase drop-shadow-sm">
          {label}
        </span>
      </div>
    </a>
  );
}

export const CommunityFooterSection: React.FC<CommunityFooterSectionProps> = ({
  communityLinks,
  onOpenAdmin,
}) => {
  const { t } = useLanguage();

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const telegramUrl = communityLinks.telegramVip || "https://t.me/OWLfxPublicChannel";
  const whatsAppUrl = communityLinks.whatsAppCareline || "http://wasap.my/+60102263677/(Website)Hai,%20saya%20nak%20tahu%20lebih%20mendalam%20tentang%20OWLFX";
  const tiktokUrl = communityLinks.tiktok || "https://www.tiktok.com/@wan.owlfx";
  const youtubeUrl = communityLinks.youtube || "https://www.youtube.com/@owlfx.official";
  const instagramUrl = communityLinks.instagram || "https://www.instagram.com/wan.owlfx";

  return (
    <footer id="community" className="relative bg-[#04060A] text-slate-400 border-t border-white/10 pt-20 pb-12 overflow-hidden selection:bg-[#D4AF37] selection:text-black">
      {/* Background Volumetric Core Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[850px] h-[250px] bg-[#D4AF37]/5 blur-[140px] rounded-full pointer-events-none" />
      <div className="absolute bottom-1/4 -right-32 w-[500px] h-[500px] bg-cyan-500/5 blur-[160px] rounded-full pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">

        {/* ======================================================================= */}
        {/* 1. TOP QUANTUM CTA BANNER                                               */}
        {/* ======================================================================= */}
        <div className="rounded-3xl bg-gradient-to-r from-[#080d1e] via-[#0f172a] to-[#080d1e] border border-[#D4AF37]/40 p-8 sm:p-12 mb-16 shadow-[0_20px_50px_rgba(0,0,0,0.8),0_0_30px_rgba(212,175,55,0.15)] relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-8">

          {/* Ambient Laser Horizon inside Banner */}
          <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-[#D4AF37] to-transparent shadow-[0_0_10px_#D4AF37]" />

          <div className="space-y-3 text-center md:text-left">
            <div className="inline-flex items-center space-x-2 px-3.5 py-1 rounded-full text-xs font-mono font-bold bg-[#D4AF37]/15 text-[#D4AF37] border border-[#D4AF37]/40 shadow-[0_0_12px_rgba(212,175,55,0.2)]">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
              <span>{t.footer.badge}</span>
            </div>
            <h3 className="text-2xl sm:text-3xl md:text-4xl font-black text-white tracking-tight uppercase">
              {t.footer.headline1}{' '}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-amber-400 to-[#D4AF37] drop-shadow-[0_0_20px_rgba(212,175,55,0.3)]">
                {t.footer.headline2}
              </span>
            </h3>
            <p className="text-sm text-slate-300 max-w-xl font-medium leading-relaxed">
              {t.footer.desc}
            </p>
          </div>

          {/* Dedicated Action Button Cluster with Moving Candlestick Charts (Clean Borderless) */}
          <div className="flex flex-col sm:flex-row gap-4 shrink-0 w-full sm:w-auto">
            <FooterCandlestickButton
              id="footer-join-vip-btn"
              href={telegramUrl}
              label={t.footer.btnVipCommunity}
              icon={
                <Send className="w-4 h-4 text-slate-950 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform duration-300" />
              }
              variant="gold"
            />
            <FooterCandlestickButton
              id="footer-whatsapp-admin-btn"
              href={whatsAppUrl}
              label={t.footer.btnWhatsAppAdmin}
              icon={
                <MessageCircle className="w-4 h-4 text-emerald-400 group-hover:scale-125 transition-transform duration-300" />
              }
              variant="cyan"
            />
          </div>
        </div>

        {/* ======================================================================= */}
        {/* 2. NAVIGATION DOCK & 360° CONTINUOUS ROTATING SOCIAL HUBS                */}
        {/* ======================================================================= */}
        <div className="mb-16">
          <div className="text-center mb-8">
            <h4 className="text-xs font-mono uppercase tracking-[0.25em] text-[#D4AF37] font-extrabold flex items-center justify-center gap-2">
              <Activity className="w-3.5 h-3.5 text-amber-400 animate-pulse" />
              <span>Quick Navigation Matrix</span>
            </h4>
          </div>

          <div className="flex flex-wrap justify-center gap-3 mb-14">
            <Link to="/about-us" className="px-4 py-2 rounded-xl bg-slate-900/80 border border-white/10 text-xs font-mono font-semibold hover:text-[#D4AF37] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all">About Us</Link>
            <Link to="/ib-development" className="px-4 py-2 rounded-xl bg-slate-900/80 border border-white/10 text-xs font-mono font-semibold hover:text-[#D4AF37] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all">IB Development</Link>
            <Link to="/owlalgo" className="px-4 py-2 rounded-xl bg-slate-900/80 border border-white/10 text-xs font-mono font-semibold hover:text-[#D4AF37] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all">OwlAlgo</Link>
            <Link to="/roadtour" className="px-4 py-2 rounded-xl bg-slate-900/80 border border-white/10 text-xs font-mono font-semibold hover:text-[#D4AF37] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all">Roadtour</Link>
            <Link to="/group-support" className="px-4 py-2 rounded-xl bg-slate-900/80 border border-white/10 text-xs font-mono font-semibold hover:text-[#D4AF37] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all">Group Support</Link>
            <Link to="/education" className="px-4 py-2 rounded-xl bg-slate-900/80 border border-white/10 text-xs font-mono font-semibold hover:text-[#D4AF37] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all">Education</Link>
            <Link to="/contact" className="px-4 py-2 rounded-xl bg-slate-900/80 border border-white/10 text-xs font-mono font-semibold hover:text-[#D4AF37] hover:border-[#D4AF37]/50 hover:bg-[#D4AF37]/10 transition-all">Contact Us</Link>
          </div>

          <div className="text-center mb-8">
            <h4 className="text-xs font-mono uppercase tracking-[0.25em] text-[#D4AF37] font-extrabold">
              {t.footer.socialHeading}
            </h4>
            <p className="text-xs text-slate-400 mt-1 font-medium">
              {t.footer.socialSub}
            </p>
          </div>

          {/* Social Links Grid with 360° Continuous Rotating Gyro Pods */}
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4">

            {/* Telegram */}
            <a
              id="footer-social-telegram"
              href={telegramUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="group p-5 rounded-2xl bg-slate-950/80 border border-white/10 hover:border-[#38BDF8]/60 transition-all duration-300 flex flex-col items-center text-center shadow-lg hover:shadow-[0_0_20px_rgba(56,189,248,0.2)] hover:scale-[1.03] active:scale-[0.98]"
            >
              <div className="w-12 h-12 rounded-2xl bg-sky-950/80 border border-sky-500/30 text-sky-400 flex items-center justify-center mb-3 group-hover:border-sky-400 transition-colors shadow-inner">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ repeat: Infinity, duration: 10, ease: 'linear' }}
                  className="flex items-center justify-center"
                >
                  <Send className="w-5 h-5" />
                </motion.div>
              </div>
              <span className="text-xs font-bold text-white group-hover:text-sky-400 transition-colors">Telegram VIP</span>
              <span className="text-[10px] font-mono text-slate-500 mt-0.5">OWLfxPublicChannel</span>
            </a>

            {/* WhatsApp Careline */}
            <a
              id="footer-social-whatsapp"
              href={whatsAppUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="group p-5 rounded-2xl bg-slate-950/80 border border-white/10 hover:border-emerald-500/60 transition-all duration-300 flex flex-col items-center text-center shadow-lg hover:shadow-[0_0_20px_rgba(16,185,129,0.2)] hover:scale-[1.03] active:scale-[0.98]"
            >
              <div className="w-12 h-12 rounded-2xl bg-emerald-950/80 border border-emerald-500/30 text-emerald-400 flex items-center justify-center mb-3 group-hover:border-emerald-400 transition-colors shadow-inner">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ repeat: Infinity, duration: 10, ease: 'linear' }}
                  className="flex items-center justify-center"
                >
                  <MessageCircle className="w-5 h-5" />
                </motion.div>
              </div>
              <span className="text-xs font-bold text-white group-hover:text-emerald-400 transition-colors">WhatsApp Careline</span>
              <span className="text-[10px] font-mono text-slate-500 mt-0.5">Hubungi Kami 24/7</span>
            </a>

            {/* TikTok */}
            <a
              id="footer-social-tiktok"
              href={tiktokUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="group p-5 rounded-2xl bg-slate-950/80 border border-white/10 hover:border-pink-500/60 transition-all duration-300 flex flex-col items-center text-center shadow-lg hover:shadow-[0_0_20px_rgba(236,72,153,0.2)] hover:scale-[1.03] active:scale-[0.98]"
            >
              <div className="w-12 h-12 rounded-2xl bg-pink-950/80 border border-pink-500/30 text-pink-400 flex items-center justify-center mb-3 group-hover:border-pink-400 transition-colors shadow-inner">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ repeat: Infinity, duration: 10, ease: 'linear' }}
                  className="flex items-center justify-center"
                >
                  <Video className="w-5 h-5" />
                </motion.div>
              </div>
              <span className="text-xs font-bold text-white group-hover:text-pink-400 transition-colors">TikTok Rasmi</span>
              <span className="text-[10px] font-mono text-slate-500 mt-0.5">@wan.owlfx</span>
            </a>

            {/* YouTube */}
            <a
              id="footer-social-youtube"
              href={youtubeUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="group p-5 rounded-2xl bg-slate-950/80 border border-white/10 hover:border-red-500/60 transition-all duration-300 flex flex-col items-center text-center shadow-lg hover:shadow-[0_0_20px_rgba(239,68,68,0.2)] hover:scale-[1.03] active:scale-[0.98]"
            >
              <div className="w-12 h-12 rounded-2xl bg-red-950/80 border border-red-500/30 text-red-400 flex items-center justify-center mb-3 group-hover:border-red-400 transition-colors shadow-inner">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ repeat: Infinity, duration: 10, ease: 'linear' }}
                  className="flex items-center justify-center"
                >
                  <Youtube className="w-5 h-5" />
                </motion.div>
              </div>
              <span className="text-xs font-bold text-white group-hover:text-red-400 transition-colors">YouTube Channel</span>
              <span className="text-[10px] font-mono text-slate-500 mt-0.5">@owlfx.official</span>
            </a>

            {/* Instagram */}
            <a
              id="footer-social-instagram"
              href={instagramUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="group p-5 rounded-2xl bg-slate-950/80 border border-white/10 hover:border-[#D4AF37]/60 transition-all duration-300 flex flex-col items-center text-center shadow-lg hover:shadow-[0_0_20px_rgba(212,175,55,0.2)] hover:scale-[1.03] active:scale-[0.98] col-span-2 sm:col-span-1"
            >
              <div className="w-12 h-12 rounded-2xl bg-amber-950/80 border border-amber-500/30 text-[#D4AF37] flex items-center justify-center mb-3 group-hover:border-[#D4AF37] transition-colors shadow-inner">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ repeat: Infinity, duration: 10, ease: 'linear' }}
                  className="flex items-center justify-center"
                >
                  <Instagram className="w-5 h-5" />
                </motion.div>
              </div>
              <span className="text-xs font-bold text-white group-hover:text-[#D4AF37] transition-colors">Instagram Media</span>
              <span className="text-[10px] font-mono text-slate-500 mt-0.5">@wan.owlfx</span>
            </a>
          </div>
        </div>

        {/* ======================================================================= */}
        {/* 3. CORPORATE LEGAL & BADGES ROW                                         */}
        {/* ======================================================================= */}
        <div className="pt-8 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-6 text-xs font-mono">
          <div className="flex items-center space-x-3">
            <div className="flex items-center space-x-2 px-3 py-1.5 rounded-xl bg-slate-900/90 border border-white/10">
              <picture className="block">
                <source srcSet="/OWLFXpng.webp" type="image/webp" />
                <img
                  src="/OWLFXpng.png"
                  alt="OWLFX Logo"
                  width="16"
                  height="16"
                  loading="lazy"
                  decoding="async"
                  className="w-4 h-4 object-contain drop-shadow-[0_0_8px_rgba(212,175,55,0.3)]"
                  onError={(e) => {
                    const target = e.currentTarget;
                    if (!target.src.endsWith('OWLFXpng.png')) {
                      target.src = '/OWLFXpng.png';
                    }
                  }}
                />
              </picture>
              <span className="text-white font-bold">{t.footer.securedBy}</span>
            </div>
            <span className="text-slate-600">•</span>
            <span className="text-slate-400">{t.footer.ecosystemTag}</span>
          </div>

          <div className="text-center md:text-right text-slate-400 max-w-xl">
            <p>© 2026 OWLFX Institutional Trading Architecture. Hak Cipta Terpelihara.</p>
            <p className="text-[10px] text-slate-500 mt-1 leading-relaxed">
              {t.footer.disclaimer}
            </p>
          </div>

          <div className="flex items-center space-x-3">
            <button
              id="footer-admin-portal-btn"
              type="button"
              onClick={onOpenAdmin}
              className="text-slate-500 hover:text-[#D4AF37] flex items-center space-x-1.5 transition-colors cursor-pointer group"
              title="Akses Pentadbir"
            >
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ repeat: Infinity, duration: 8, ease: 'linear' }}
                className="flex items-center justify-center text-slate-400 group-hover:text-amber-400"
              >
                <Lock className="w-3.5 h-3.5" />
              </motion.div>
              <span>Admin Portal</span>
            </button>

            <button
              id="footer-scroll-top-btn"
              type="button"
              onClick={scrollToTop}
              className="p-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-300 hover:text-white border border-white/10 transition-colors cursor-pointer shadow-md group"
              title="Kembali ke Atas"
            >
              <ArrowUp className="w-4 h-4 group-hover:-translate-y-0.5 transition-transform" />
            </button>
          </div>
        </div>

      </div>
    </footer>
  );
};
