// Generated by IqwanEngine
import React, { useMemo } from 'react';
import { motion } from 'framer-motion';
import {
  ArrowRight,
  Info,
  Users,
  Cpu,
  Map,
  Shield,
  GraduationCap,
  Phone
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { HeroSection } from './HeroSection';
import { useLanguage } from '../context/LanguageContext';

interface TeaserCardItem {
  id: string;
  title: string;
  description: string;
  icon: React.ReactNode;
  link: string;
  color: string;
  border: string;
  glowColor: string;
  accentColor: string;
  btnText: string;
}

export function HomePage() {
  const { t } = useLanguage();

  const teaserCards: TeaserCardItem[] = useMemo(() => [
    {
      id: 'about',
      title: t.nav.about,
      description: 'Discover our philosophy and commitment to excellence in the financial world.',
      icon: <Info className="w-6 h-6" />,
      link: '/about-us',
      color: 'from-blue-500/10 via-cyan-500/5 to-transparent',
      border: 'border-cyan-500/30',
      glowColor: 'rgba(6, 182, 212, 0.25)',
      accentColor: '#06B6D4',
      btnText: 'Ketahui Lanjut'
    },
    {
      id: 'ib-dev',
      title: t.nav.ibDevelopment,
      description: 'Join our global partner network in Malaysia and Indonesia for sustainable growth.',
      icon: <Users className="w-6 h-6" />,
      link: '/ib-development',
      color: 'from-amber-500/10 via-yellow-500/5 to-transparent',
      border: 'border-amber-500/30',
      glowColor: 'rgba(245, 158, 11, 0.25)',
      accentColor: '#F59E0B',
      btnText: 'Sertai IB'
    },
    {
      id: 'algo',
      title: t.nav.owlAlgo,
      description: 'Advanced algorithmic trading tools designed for precision and consistency.',
      icon: <Cpu className="w-6 h-6" />,
      link: '/owlalgo',
      color: 'from-purple-500/10 via-indigo-500/5 to-transparent',
      border: 'border-purple-500/30',
      glowColor: 'rgba(168, 85, 247, 0.25)',
      accentColor: '#A855F7',
      btnText: 'Akses Algo'
    },
    {
      id: 'roadtour',
      title: t.nav.roadtour,
      description: 'Relive our journey across 14 states sharing knowledge and opportunities.',
      icon: <Map className="w-6 h-6" />,
      link: '/roadtour',
      color: 'from-emerald-500/10 via-teal-500/5 to-transparent',
      border: 'border-emerald-500/30',
      glowColor: 'rgba(16, 185, 129, 0.25)',
      accentColor: '#10B981',
      btnText: 'Lihat Galeri'
    },
    {
      id: 'support',
      title: t.nav.groupSupport,
      description: 'Exclusive VIP signals and a dedicated community for serious traders.',
      icon: <Shield className="w-6 h-6" />,
      link: '/group-support',
      color: 'from-red-500/10 via-orange-500/5 to-transparent',
      border: 'border-red-500/30',
      glowColor: 'rgba(239, 68, 68, 0.25)',
      accentColor: '#EF4444',
      btnText: 'Sertai Komuniti'
    },
    {
      id: 'education',
      title: t.nav.education,
      description: 'Master the markets with our structured curriculum from basics to advanced.',
      icon: <GraduationCap className="w-6 h-6" />,
      link: '/education',
      color: 'from-blue-600/10 via-indigo-600/5 to-transparent',
      border: 'border-blue-600/30',
      glowColor: 'rgba(37, 99, 235, 0.25)',
      accentColor: '#3B82F6',
      btnText: 'Mula Belajar'
    },
    {
      id: 'community',
      title: t.nav.community,
      description: 'Get in touch with our team for support, inquiries, or collaboration.',
      icon: <Phone className="w-6 h-6" />,
      link: '/contact',
      color: 'from-gray-500/10 via-slate-500/5 to-transparent',
      border: 'border-gray-500/30',
      glowColor: 'rgba(148, 163, 184, 0.25)',
      accentColor: '#94A3B8',
      btnText: 'Hubungi Kami'
    }
  ], [t]);

  return (
    <div className="flex flex-col selection:bg-[#D4AF37] selection:text-black">
      {/* Primary Hero Section */}
      <HeroSection
        onExploreAlgo={() => {
          const el = document.getElementById('showcase');
          if (el) el.scrollIntoView({ behavior: 'smooth' });
        }}
      />

      {/* Institutional Showcase Section */}
      <section id="showcase" className="py-24 px-4 sm:px-6 lg:px-8 relative z-10 overflow-hidden">
        {/* Ambient Backlight Flare */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[500px] bg-amber-500/5 rounded-full blur-[160px] pointer-events-none -z-10" />

        <div className="max-w-7xl mx-auto">
          {/* Header Title Section */}
          <div className="text-center mb-16">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-4xl md:text-5xl font-black bg-gradient-to-r from-white via-slate-200 to-slate-400 bg-clip-text text-transparent mb-4 uppercase tracking-tight"
            >
              Executive Showcase Hub
            </motion.h2>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 }}
              className="text-slate-400 max-w-2xl mx-auto text-sm sm:text-base font-medium"
            >
              Explore the OWLFX ecosystem. Choose a department to begin your journey.
            </motion.p>
          </div>

          {/* Institutional Grid Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {teaserCards.map((card, index) => (
              <motion.div
                key={card.id}
                initial={{ opacity: 0, y: 25 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.08, duration: 0.45 }}
                className="h-full"
              >
                <Link to={card.link} className="group block h-full select-none">
                  <div
                    className={`h-full p-8 rounded-3xl bg-gradient-to-br ${card.color} bg-slate-950/85 backdrop-blur-2xl border ${card.border} hover:border-[#D4AF37]/60 transition-all duration-500 hover:scale-[1.02] hover:shadow-[0_20px_50px_rgba(0,0,0,0.8)] flex flex-col justify-between relative overflow-hidden`}
                  >
                    {/* Background Radial Spot */}
                    <div
                      className="absolute -top-12 -right-12 w-36 h-36 rounded-full blur-[60px] opacity-20 group-hover:opacity-40 transition-opacity pointer-events-none"
                      style={{ backgroundColor: card.accentColor }}
                    />

                    <div>
                      {/* 360-DEGREE CONTINUOUS ROTATING ICON POD */}
                      <div className="relative w-14 h-14 rounded-2xl bg-slate-900/90 border border-white/10 flex items-center justify-center mb-6 text-[#D4AF37] shadow-[0_0_20px_rgba(0,0,0,0.5)] group-hover:border-[#D4AF37]/50 transition-colors">
                        <motion.div
                          animate={{ rotate: 360 }}
                          transition={{
                            repeat: Infinity,
                            duration: 10,
                            ease: 'linear'
                          }}
                          whileHover={{
                            scale: 1.15,
                            transition: { duration: 0.3 }
                          }}
                          className="flex items-center justify-center w-full h-full text-[#D4AF37]"
                        >
                          {card.icon}
                        </motion.div>

                        {/* Orbiting Micro-Glow Pulse */}
                        <div className="absolute inset-0 rounded-2xl bg-amber-400/10 blur-md opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />
                      </div>

                      {/* Content Details */}
                      <h3 className="text-2xl font-bold text-white mb-3 tracking-tight group-hover:text-[#D4AF37] transition-colors">
                        {card.title}
                      </h3>
                      <p className="text-slate-400 text-sm leading-relaxed mb-8">
                        {card.description}
                      </p>
                    </div>

                    {/* DYNAMIC MOVING CHART BUTTON */}
                    <div className="pt-2">
                      <TradingChartButton
                        label={card.btnText}
                        accentColor={card.accentColor}
                      />
                    </div>
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}

interface TradingChartButtonProps {
  label: string;
  accentColor: string;
}

/**
 * High-precision Trading Chart Button
 * Features:
 * 1. Looping moving waveform / candlestick oscillation inside the button canvas
 * 2. Neon boundary glow and animated directional arrow
 * 3. Neat layout preservation without visual text clutter
 */
function TradingChartButton({ label, accentColor }: TradingChartButtonProps) {
  return (
    <div className="relative w-full h-12 rounded-xl bg-slate-950/90 border border-white/10 group-hover:border-[#D4AF37]/50 overflow-hidden flex items-center justify-between px-4 transition-all duration-300 shadow-[inset_0_1px_1px_rgba(255,255,255,0.08)] group-hover:shadow-[0_0_20px_rgba(212,175,55,0.15)]">

      {/* 1. EMBEDDED MOVING CANDLESTICK & TREND WAVE ANIMATION */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-35 group-hover:opacity-65 transition-opacity">
        {/* Dynamic Candlestick Bars Wave */}
        <div className="absolute inset-0 flex items-end justify-between px-3 pb-1 gap-1">
          {[35, 65, 45, 80, 55, 90, 40, 75, 50, 85, 60, 95, 70, 45, 80, 60].map((height, i) => (
            <motion.div
              key={i}
              className="w-[3px] rounded-t-sm"
              style={{
                backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444'
              }}
              animate={{
                height: [
                  `${Math.max(15, height * 0.3)}%`,
                  `${Math.min(95, height * 0.9)}%`,
                  `${Math.max(20, height * 0.45)}%`
                ]
              }}
              transition={{
                repeat: Infinity,
                duration: 1.8 + (i % 5) * 0.3,
                ease: 'easeInOut',
                repeatType: 'reverse',
                delay: i * 0.08
              }}
            />
          ))}
        </div>

        {/* Dynamic Continuous Moving Market Line Wave */}
        <svg
          className="absolute inset-0 w-[200%] h-full stroke-current"
          style={{ color: accentColor }}
          viewBox="0 0 500 50"
          preserveAspectRatio="none"
        >
          <motion.path
            d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
            fill="none"
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeDasharray="4 2"
            animate={{
              x: [0, -250]
            }}
            transition={{
              repeat: Infinity,
              duration: 4.5,
              ease: 'linear'
            }}
          />
        </svg>

        {/* Soft Linear Gradient Overlay for High Text Readability */}
        <div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/60 to-slate-950/80" />
      </div>

      {/* 2. BUTTON TEXT & LABELS */}
      <span className="relative z-10 font-mono text-xs font-bold tracking-wider uppercase text-slate-200 group-hover:text-white transition-colors">
        {label}
      </span>

      {/* 3. DYNAMIC ARROW VECTOR */}
      <div className="relative z-10 flex items-center text-[#D4AF37] group-hover:text-amber-400 group-hover:translate-x-1 transition-all duration-300">
        <ArrowRight className="w-4 h-4" />
      </div>

      {/* 4. PASSING SPECULAR SCANNING RAY */}
      <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/15 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />
    </div>
  );
}
