// Generated by IqwanEngine
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { IBRegionData, Region } from '../types';
import { IB_REGIONS_DATA } from '../data/initialData';
import {
  Briefcase,
  ArrowUpRight,
  CheckCircle,
  ZoomIn,
  TrendingUp,
  DollarSign,
  Users,
  Zap
} from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { ShimmerImage } from './ShimmerImage';
import { useScrollReveal } from '../hooks/useScrollReveal';

interface IBDevelopmentSectionProps {
  currentRegion?: Region;
  ibData?: Record<'MY' | 'ID', IBRegionData>;
  onOpenLightbox: (images: { url: string; caption?: string; title?: string }[], index: number) => void;
}

interface MovingCandlestickButtonProps {
  id?: string;
  href: string;
  label: string;
  flag: string;
  variant: 'blue' | 'crimson';
}

/**
 * Reusable Overpower Institutional Button with Embedded Moving Candlestick/Wave Chart
 */
function IBCandlestickButton({ id, href, label, flag, variant }: MovingCandlestickButtonProps) {
  const isBlue = variant === 'blue';
  const strokeColor = isBlue ? '#38BDF8' : '#F43F5E';

  return (
    <a
      id={id}
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="group relative overflow-hidden rounded-2xl p-[1.5px] transition-all duration-500 hover:scale-[1.03] active:scale-[0.97] cursor-pointer block select-none"
    >
      {/* Dynamic Animated Conic Laser Border */}
      <span
        className={`absolute inset-0 animate-[spin_3.5s_linear_infinite] ${
          isBlue
            ? 'bg-[conic-gradient(from_0deg_at_50%_50%,#1e3a8a_0%,#38bdf8_50%,#d4af37_100%)]'
            : 'bg-[conic-gradient(from_0deg_at_50%_50%,#881337_0%,#f43f5e_50%,#d4af37_100%)]'
        }`}
      />

      <div
        className={`relative px-8 py-4 rounded-2xl flex items-center justify-center space-x-3 overflow-hidden shadow-[0_10px_30px_rgba(0,0,0,0.7)] ${
          isBlue
            ? 'bg-gradient-to-r from-blue-950 via-[#1E3A8A] to-slate-950 border border-blue-400/30'
            : 'bg-gradient-to-r from-rose-950 via-[#991B1B] to-slate-950 border border-rose-400/30'
        }`}
      >
        {/* Dynamic Candlestick Bars Wave in Background */}
        <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-60 transition-opacity">
          <div className="absolute inset-0 flex items-end justify-between px-3 pb-1 gap-1">
            {[45, 75, 50, 85, 60, 95, 40, 70, 55, 90, 65, 80, 50, 90].map((h, i) => (
              <motion.div
                key={i}
                className="w-[2px] rounded-t-sm"
                style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
                animate={{
                  height: [
                    `${Math.max(15, h * 0.3)}%`,
                    `${Math.min(95, h * 0.95)}%`,
                    `${Math.max(20, h * 0.45)}%`
                  ]
                }}
                transition={{
                  repeat: Infinity,
                  duration: 1.5 + (i % 4) * 0.25,
                  ease: 'easeInOut',
                  repeatType: 'reverse',
                  delay: i * 0.06
                }}
              />
            ))}
          </div>

          {/* Dynamic Moving Market Polyline Wave */}
          <svg
            className="absolute inset-0 w-[200%] h-full stroke-current"
            style={{ color: strokeColor }}
            viewBox="0 0 500 50"
            preserveAspectRatio="none"
          >
            <motion.path
              d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
              fill="none"
              strokeWidth="1.8"
              strokeLinecap="round"
              strokeDasharray="4 2"
              animate={{ x: [0, -250] }}
              transition={{
                repeat: Infinity,
                duration: 4,
                ease: 'linear'
              }}
            />
          </svg>

          <div
            className={`absolute inset-0 ${
              isBlue
                ? 'bg-gradient-to-r from-blue-950/80 via-blue-900/60 to-slate-950/90'
                : 'bg-gradient-to-r from-rose-950/80 via-rose-900/60 to-slate-950/90'
            }`}
          />
        </div>

        {/* Shimmer Specular Light Sweep */}
        <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/20 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

        {/* Content Elements */}
        <span className="relative z-10 text-xl group-hover:scale-125 transition-transform duration-300 drop-shadow-md">
          {flag}
        </span>
        <span className="relative z-10 font-mono font-black text-sm tracking-wider uppercase text-white drop-shadow-sm">
          {label}
        </span>
        <div className="relative z-10 p-1 rounded-lg bg-white/10 group-hover:bg-white/20 transition-colors text-amber-300">
          <ArrowUpRight className="w-4 h-4 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform duration-300" />
        </div>
      </div>
    </a>
  );
}

export const IBDevelopmentSection: React.FC<IBDevelopmentSectionProps> = ({
  currentRegion = 'MY',
  ibData,
  onOpenLightbox,
}) => {
  const { t } = useLanguage();
  const [selectedRegion, setSelectedRegion] = useState<Region>(currentRegion || 'MY');
  const containerRef = useScrollReveal();

  const regionData: IBRegionData =
    (ibData && ibData[selectedRegion]) ||
    IB_REGIONS_DATA[selectedRegion] ||
    IB_REGIONS_DATA.MY;

  const activitiesList = regionData?.activities || [];

  const handleActivityClick = (index: number) => {
    if (!activitiesList || activitiesList.length === 0) return;
    const formatted = activitiesList.map((act) => ({
      url: act.imageUrl || act.url || '',
      caption: `[IB ${regionData.region || selectedRegion}] ${act.title || act.caption || 'Aktiviti IB'} — ${act.location || 'OWLFX Event'} (${act.date || '2026'})`,
      title: act.title || act.caption || 'Aktiviti Rasmi IB',
    }));
    onOpenLightbox(formatted, index);
  };

  const activeIBStat = regionData?.stats?.activeIB || (selectedRegion === 'MY' ? '420+ Master & Sub-IB' : '280+ Mitra IB Nusantara');
  const totalVolumeStat = regionData?.stats?.totalVolume || (selectedRegion === 'MY' ? '$18.4M+ Lot Sebulan' : '$12.8M+ Volume Bulanan');
  const monthlyRebateStat = regionData?.stats?.monthlyRebate || (selectedRegion === 'MY' ? 'RM 1,250,000+' : 'Rp 3.8 Miliar+');
  const tierCommissionStat = regionData?.stats?.tierCommission || (selectedRegion === 'MY' ? 'Hingga $15 / Lot' : 'Hingga $16 / Lot');
  const registrationLink = regionData?.registerLink || regionData?.registrationUrl || (selectedRegion === 'MY' ? '/my/ib_development' : '/id/ib_development');

  return (
    <section
      id="ib-development"
      ref={containerRef}
      className="py-24 relative bg-[#06090e] border-t border-white/5 overflow-hidden selection:bg-[#D4AF37] selection:text-black"
    >
      {/* Background Volumetric Glow Elements */}
      <div
        className={`absolute top-1/3 -left-32 w-[600px] h-[600px] rounded-full blur-[170px] pointer-events-none transition-colors duration-700 -z-10 ${
          selectedRegion === 'MY' ? 'bg-blue-600/10' : 'bg-red-600/10'
        }`}
      />
      <div className="absolute bottom-1/4 -right-32 w-[550px] h-[550px] bg-amber-500/5 rounded-full blur-[160px] pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Section Header with 360° Continuous Rotating Briefcase */}
        <div className="text-center max-w-3xl mx-auto mb-14">
          <div className="inline-flex items-center space-x-2.5 px-4 py-1.5 rounded-full bg-[#D4AF37]/10 border border-[#D4AF37]/30 text-[#D4AF37] text-xs font-mono mb-4 shadow-[0_0_20px_rgba(212,175,55,0.15)]">
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ repeat: Infinity, duration: 12, ease: 'linear' }}
              className="flex items-center justify-center text-[#D4AF37]"
            >
              <Briefcase className="w-4 h-4" />
            </motion.div>
            <span className="font-bold tracking-wider uppercase">{t.ib.badge}</span>
          </div>

          <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight uppercase">
            {t.ib.title1}{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-amber-400 to-[#D4AF37] drop-shadow-[0_0_25px_rgba(245,158,11,0.3)]">
              {t.ib.title2}
            </span>
          </h2>
          <p className="mt-4 text-slate-400 text-sm sm:text-base leading-relaxed font-medium">
            {t.ib.description}
          </p>
        </div>

        {/* Dual Region Tab System with Moving Candlestick Wave Feedback */}
        <div className="flex justify-center mb-12">
          <div
            id="ib-region-tab-container"
            className="inline-flex p-1.5 rounded-3xl bg-slate-950/80 border border-white/10 shadow-[0_15px_35px_rgba(0,0,0,0.8)] backdrop-blur-2xl"
          >
            {/* Malaysia Tab */}
            <button
              id="ib-tab-malaysia"
              type="button"
              onClick={() => setSelectedRegion('MY')}
              className={`relative group px-7 py-3.5 rounded-2xl font-mono font-black text-xs uppercase tracking-widest transition-all duration-300 flex items-center space-x-3 cursor-pointer overflow-hidden ${
                selectedRegion === 'MY'
                  ? 'bg-blue-600/30 text-white border border-blue-500/80 shadow-[0_0_25px_rgba(37,99,235,0.4)]'
                  : 'text-slate-400 hover:text-white hover:bg-white/5 border border-transparent'
              }`}
            >
              {selectedRegion === 'MY' && (
                <div className="absolute inset-0 pointer-events-none opacity-25">
                  <div className="absolute inset-0 flex items-end justify-between px-2 pb-0.5 gap-0.5">
                    {[40, 70, 50, 85, 60, 95].map((h, i) => (
                      <motion.div
                        key={i}
                        className="w-[2px] bg-sky-400 rounded-t-sm"
                        animate={{ height: [`${h * 0.3}%`, `${h * 0.9}%`, `${h * 0.4}%`] }}
                        transition={{ repeat: Infinity, duration: 1.5 + i * 0.2, repeatType: 'reverse' }}
                      />
                    ))}
                  </div>
                </div>
              )}
              <span className="text-lg group-hover:scale-110 transition-transform">🇲🇾</span>
              <span className="relative z-10">{t.ib.tabMY}</span>
            </button>

            {/* Indonesia Tab */}
            <button
              id="ib-tab-indonesia"
              type="button"
              onClick={() => setSelectedRegion('ID')}
              className={`relative group px-7 py-3.5 rounded-2xl font-mono font-black text-xs uppercase tracking-widest transition-all duration-300 flex items-center space-x-3 cursor-pointer overflow-hidden ${
                selectedRegion === 'ID'
                  ? 'bg-red-600/30 text-white border border-red-500/80 shadow-[0_0_25px_rgba(220,38,38,0.4)]'
                  : 'text-slate-400 hover:text-white hover:bg-white/5 border border-transparent'
              }`}
            >
              {selectedRegion === 'ID' && (
                <div className="absolute inset-0 pointer-events-none opacity-25">
                  <div className="absolute inset-0 flex items-end justify-between px-2 pb-0.5 gap-0.5">
                    {[40, 70, 50, 85, 60, 95].map((h, i) => (
                      <motion.div
                        key={i}
                        className="w-[2px] bg-rose-400 rounded-t-sm"
                        animate={{ height: [`${h * 0.3}%`, `${h * 0.9}%`, `${h * 0.4}%`] }}
                        transition={{ repeat: Infinity, duration: 1.5 + i * 0.2, repeatType: 'reverse' }}
                      />
                    ))}
                  </div>
                </div>
              )}
              <span className="text-lg group-hover:scale-110 transition-transform">🇮🇩</span>
              <span className="relative z-10">{t.ib.tabID}</span>
            </button>
          </div>
        </div>

        {/* Region Content Container */}
        <div
          id={`ib-region-content-${selectedRegion}`}
          className="rounded-3xl bg-[#080d19]/90 border border-white/10 p-6 sm:p-10 shadow-[0_20px_50px_rgba(0,0,0,0.8)] backdrop-blur-2xl transition-all duration-300 relative overflow-hidden"
        >
          {/* Subtle regional light spot */}
          <div
            className={`absolute top-0 right-0 w-96 h-96 rounded-full blur-[140px] pointer-events-none transition-colors duration-700 ${
              selectedRegion === 'MY' ? 'bg-blue-600/10' : 'bg-red-600/10'
            }`}
          />

          {/* Regional Header & Stats Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center pb-8 border-b border-white/10 mb-8 relative z-10">
            <div className="lg:col-span-7 space-y-4">
              <span
                className={`inline-block px-3.5 py-1 rounded-full text-xs font-mono font-bold ${
                  selectedRegion === 'MY'
                    ? 'bg-blue-950/80 text-sky-400 border border-blue-500/40'
                    : 'bg-rose-950/80 text-red-400 border border-red-500/40'
                }`}
              >
                {regionData.badge || (selectedRegion === 'MY' ? '🇲🇾 Rasmi Malaysia Ecosystem' : '🇮🇩 Resmi Indonesia Ecosystem')}
              </span>

              <h3 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
                {regionData.title}
              </h3>

              <p className="text-sm text-slate-300 leading-relaxed font-medium">
                {regionData.description}
              </p>

              <div className="flex flex-wrap gap-4 text-xs font-mono text-slate-300 pt-2">
                <div className="flex items-center space-x-2">
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ repeat: Infinity, duration: 8, ease: 'linear' }}
                  >
                    <CheckCircle className="w-4 h-4 text-emerald-400" />
                  </motion.div>
                  <span>{t.ib.partnerSupport1}</span>
                </div>
                <div className="flex items-center space-x-2">
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ repeat: Infinity, duration: 8, ease: 'linear' }}
                  >
                    <CheckCircle className="w-4 h-4 text-emerald-400" />
                  </motion.div>
                  <span>{t.ib.partnerSupport2}</span>
                </div>
                <div className="flex items-center space-x-2">
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ repeat: Infinity, duration: 8, ease: 'linear' }}
                  >
                    <CheckCircle className="w-4 h-4 text-emerald-400" />
                  </motion.div>
                  <span>{t.ib.partnerSupport3}</span>
                </div>
              </div>
            </div>

            {/* Institutional Stats Metrics Quad */}
            <div className="lg:col-span-5 grid grid-cols-2 gap-3.5">
              <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5 flex flex-col justify-between">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">
                    {selectedRegion === 'MY' ? 'IB & MITRA AKTIF' : 'MITRA AKTIF'}
                  </span>
                  <Users className="w-3.5 h-3.5 text-cyan-400" />
                </div>
                <span className="text-lg sm:text-xl font-black font-mono text-white">
                  {activeIBStat}
                </span>
              </div>

              <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5 flex flex-col justify-between">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">VOLUM BULANAN</span>
                  <TrendingUp className="w-3.5 h-3.5 text-amber-400" />
                </div>
                <span className="text-lg sm:text-xl font-black font-mono text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-[#D4AF37]">
                  {totalVolumeStat}
                </span>
              </div>

              <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5 flex flex-col justify-between">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">REBAT DISEDIAKAN</span>
                  <DollarSign className="w-3.5 h-3.5 text-emerald-400" />
                </div>
                <span className="text-lg sm:text-xl font-black font-mono text-emerald-400">
                  {monthlyRebateStat}
                </span>
              </div>

              <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5 flex flex-col justify-between">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">TIER KOMISEN</span>
                  <Zap className="w-3.5 h-3.5 text-sky-400" />
                </div>
                <span className="text-lg sm:text-xl font-black font-mono text-sky-400">
                  {tierCommissionStat}
                </span>
              </div>
            </div>
          </div>

          {/* Regional Activity Album & Official Coverage */}
          <div className="mb-10 relative z-10">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h4 className="text-base font-bold text-white tracking-wide">
                  Liputan Rasmi & Aktiviti IB {selectedRegion === 'MY' ? 'Malaysia' : 'Indonesia'}
                </h4>
                <p className="text-xs text-slate-400">
                  Bengkel kepimpinan, malam pengiktirafan, dan kit barangan rasmi (Official Merchandise).
                </p>
              </div>
              <span className="text-xs font-mono text-[#D4AF37] hidden sm:inline">
                Klik gambar untuk zum (Lightbox HD)
              </span>
            </div>

            {activitiesList.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {activitiesList.map((act, idx) => (
                  <div
                    key={`ib-${selectedRegion}-${act.id || idx}`}
                    id={`ib-act-card-${act.id || idx}`}
                    onClick={() => handleActivityClick(idx)}
                    className="group rounded-2xl overflow-hidden bg-slate-900/90 border border-white/10 hover:border-[#D4AF37] transition-all cursor-pointer shadow-lg flex flex-col justify-between"
                  >
                    <div className="relative h-44 overflow-hidden">
                      <ShimmerImage
                        src={act.imageUrl || act.url || ''}
                        alt={act.title || act.caption || 'Aktiviti IB'}
                        fallbackSrc="https://drive.google.com/file/d/1tm2SG-Y3tJya5AjgYDkOipVLD3VyxZRX/view?usp=drive_link"
                        containerClassName="relative w-full h-full"
                        imageClassName="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
                        badgeLabel={`IB ${selectedRegion === 'MY' ? 'MALAYSIA' : 'INDONESIA'}`}
                        loading="lazy"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent pointer-events-none" />

                      <span className="absolute top-2.5 left-2.5 px-2 py-0.5 rounded-md text-[10px] font-mono font-bold bg-black/80 text-[#D4AF37] border border-[#D4AF37]/40 z-20">
                        {act.category || 'Program'}
                      </span>

                      <span className="absolute bottom-2 left-2 text-[10px] font-mono text-slate-300 z-20">
                        {act.date || '2026'} • {act.location || 'Wilayah'}
                      </span>

                      <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-black/40 z-20">
                        <div className="p-2.5 rounded-full bg-[#D4AF37] text-slate-950 shadow-xl">
                          <ZoomIn className="w-4 h-4" />
                        </div>
                      </div>
                    </div>

                    <div className="p-4">
                      <h5 className="font-bold text-sm text-white mb-1.5 group-hover:text-[#D4AF37] transition-colors line-clamp-1">
                        {act.title || act.caption}
                      </h5>
                      <p className="text-xs text-slate-400 leading-relaxed line-clamp-2">
                        {act.description || act.caption}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="rounded-2xl border border-white/10 bg-slate-950/80 p-8 text-center flex flex-col items-center justify-center space-y-3">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ repeat: Infinity, duration: 10, ease: 'linear' }}
                >
                  <Briefcase className="w-10 h-10 text-[#D4AF37]/70" />
                </motion.div>
                <h5 className="text-sm font-bold text-white font-mono uppercase tracking-wider">
                  Aktiviti Wilayah {selectedRegion === 'MY' ? 'Malaysia' : 'Indonesia'} Akan Dikemaskini
                </h5>
                <p className="text-xs text-slate-400 max-w-md">
                  Dokumentasi acara dan galeri foto sedang disunting oleh pihak pengurusan OWLFX. Pendaftaran mitra IB kekal dibuka seperti biasa.
                </p>
              </div>
            )}
          </div>

          {/* DEDICATED OVERPOWER CANDLESTICK ACTION BUTTONS AT BOTTOM OF ALBUM */}
          <div className="pt-6 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between gap-5 relative z-10">
            <div className="text-center sm:text-left">
              <span className="text-xs font-mono text-slate-400 block tracking-wider">
                PAUTAN PROTOKOL: <span className="text-amber-400 font-mono font-bold">{registrationLink}</span>
              </span>
              <p className="text-xs text-slate-400 mt-0.5">
                Penyertaan pantas disokong oleh meja meja pengurusan institusi 24/7.
              </p>
            </div>

            {selectedRegion === 'MY' ? (
              <IBCandlestickButton
                id="ib-action-btn-malaysia"
                href={registrationLink}
                label={regionData.buttonText || t.ib.btnRegisterMY}
                flag="🇲🇾"
                variant="blue"
              />
            ) : (
              <IBCandlestickButton
                id="ib-action-btn-indonesia"
                href={registrationLink}
                label={regionData.buttonText || t.ib.btnRegisterID}
                flag="🇮🇩"
                variant="crimson"
              />
            )}
          </div>
        </div>
      </div>
    </section>
  );
};
