// Generated by IqwanEngine
import React, { useEffect, useRef, useState } from 'react';
import { Navbar } from './Navbar';
import { CommunityFooterSection } from './CommunityFooterSection';
import { ShieldCheck, Activity, Cpu, TrendingUp, Zap } from 'lucide-react';
import { CommunityLinks } from '../types';

interface LayoutProps {
  children: React.ReactNode;
  onOpenAdmin: () => void;
  communityLinks: CommunityLinks;
  securityToast: { show: boolean; message: string };
}

interface Particle {
  x: number;
  y: number;
  size: number;
  speedX: number;
  speedY: number;
  opacity: number;
  twinkleSpeed: number;
  color: string;
  depth: number;
}

interface OrderBlockNode {
  x: number;
  y: number;
  width: number;
  height: number;
  opacity: number;
  pulsePhase: number;
  isBullish: boolean;
}

export function Layout({ children, onOpenAdmin, communityLinks, securityToast }: LayoutProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [fps, setFps] = useState<number>(60);
  const [marketPhase, setMarketPhase] = useState<'ACCUMULATION' | 'MANIPULATION' | 'EXPANSION'>('EXPANSION');

  // Cycle market phase simulation periodically
  useEffect(() => {
    const phases: Array<'ACCUMULATION' | 'MANIPULATION' | 'EXPANSION'> = ['ACCUMULATION', 'MANIPULATION', 'EXPANSION'];
    let idx = 2;
    const interval = setInterval(() => {
      idx = (idx + 1) % phases.length;
      setMarketPhase(phases[idx]);
    }, 12000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d', { alpha: true });
    if (!ctx) return;

    let animationFrameId: number;
    let dpr = Math.min(window.devicePixelRatio || 1, 2);
    let width = window.innerWidth;
    let height = window.innerHeight;

    const setupCanvasResolution = () => {
      if (!canvas) return;
      width = window.innerWidth;
      height = window.innerHeight;
      canvas.width = Math.floor(width * dpr);
      canvas.height = Math.floor(height * dpr);
      canvas.style.width = `${width}px`;
      canvas.style.height = `${height}px`;
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.scale(dpr, dpr);
    };

    setupCanvasResolution();

    const isMobile = width < 768;
    const particleCount = isMobile ? 35 : 85;
    const particles: Particle[] = [];
    const goldPalette = ['#F59E0B', '#D4AF37', '#FDE68A', '#38BDF8', '#10B981'];

    for (let i = 0; i < particleCount; i++) {
      particles.push({
        x: Math.random() * width,
        y: Math.random() * height,
        size: Math.random() * 2.2 + 0.6,
        speedX: (Math.random() - 0.5) * 0.45,
        speedY: (Math.random() - 0.5) * 0.35 - 0.2,
        opacity: Math.random() * 0.65 + 0.25,
        twinkleSpeed: Math.random() * 0.02 + 0.005,
        color: goldPalette[Math.floor(Math.random() * goldPalette.length)],
        depth: Math.random() * 0.8 + 0.2
      });
    }

    // Institutional Order Blocks
    const orderBlocks: OrderBlockNode[] = [];
    const blockCount = isMobile ? 3 : 7;
    for (let i = 0; i < blockCount; i++) {
      orderBlocks.push({
        x: (width / (blockCount + 1)) * (i + 1) + (Math.random() * 60 - 30),
        y: height * 0.65 + (Math.random() * 180 - 90),
        width: Math.random() * 90 + 60,
        height: Math.random() * 35 + 18,
        opacity: Math.random() * 0.12 + 0.05,
        pulsePhase: Math.random() * Math.PI * 2,
        isBullish: i % 2 === 0
      });
    }

    const mouse = {
      x: -1000,
      y: -1000,
      radius: isMobile ? 0 : 160
    };

    const handleMouseMove = (e: MouseEvent) => {
      mouse.x = e.clientX;
      mouse.y = e.clientY;
    };

    const handleMouseLeave = () => {
      mouse.x = -1000;
      mouse.y = -1000;
    };

    const handleResize = () => {
      dpr = Math.min(window.devicePixelRatio || 1, 2);
      setupCanvasResolution();
    };

    window.addEventListener('resize', handleResize);
    if (!isMobile) {
      window.addEventListener('mousemove', handleMouseMove, { passive: true });
      window.addEventListener('mouseleave', handleMouseLeave);
    }

    let waveOffset = 0;
    let radarSweepAngle = 0;
    let frameCount = 0;
    let lastFpsUpdate = performance.now();

    const render = (currentTime: number) => {
      // Calculate dynamic FPS monitor
      frameCount++;
      if (currentTime - lastFpsUpdate >= 1000) {
        setFps(Math.round((frameCount * 1000) / (currentTime - lastFpsUpdate)));
        frameCount = 0;
        lastFpsUpdate = currentTime;
      }

      ctx.clearRect(0, 0, width, height);

      // =======================================================================
      // 1. INSTITUTIONAL CYBERNETIC DEPTH MATRIX (PERSPECTIVE GRID)
      // =======================================================================
      ctx.save();
      ctx.strokeStyle = 'rgba(212, 175, 55, 0.035)';
      ctx.lineWidth = 1;
      const gridSpacing = 44;
      const xStart = 0;
      for (let x = xStart; x < width; x += gridSpacing) {
        ctx.beginPath();
        ctx.moveTo(x, 0);
        ctx.lineTo(x, height);
        ctx.stroke();
      }
      for (let y = 0; y < height; y += gridSpacing) {
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(width, y);
        ctx.stroke();
      }
      ctx.restore();

      // =======================================================================
      // 2. RADAR SWEEP BEAM (HEDGE FUND SCANNER)
      // =======================================================================
      radarSweepAngle += 0.008;
      const radarCenterX = width * 0.85;
      const radarCenterY = height * 0.25;
      const radarRadius = isMobile ? 120 : 220;

      ctx.save();
      const sweepGradient = ctx.createRadialGradient(
        radarCenterX,
        radarCenterY,
        10,
        radarCenterX,
        radarCenterY,
        radarRadius
      );
      sweepGradient.addColorStop(0, 'rgba(212, 175, 55, 0.08)');
      sweepGradient.addColorStop(0.5, 'rgba(16, 185, 129, 0.03)');
      sweepGradient.addColorStop(1, 'transparent');

      ctx.beginPath();
      ctx.arc(radarCenterX, radarCenterY, radarRadius, 0, Math.PI * 2);
      ctx.fillStyle = sweepGradient;
      ctx.fill();

      // Radar Concentric Circles
      ctx.strokeStyle = 'rgba(212, 175, 55, 0.06)';
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.arc(radarCenterX, radarCenterY, radarRadius * 0.33, 0, Math.PI * 2);
      ctx.arc(radarCenterX, radarCenterY, radarRadius * 0.66, 0, Math.PI * 2);
      ctx.arc(radarCenterX, radarCenterY, radarRadius, 0, Math.PI * 2);
      ctx.stroke();

      // Radar Beam Vector
      ctx.beginPath();
      ctx.moveTo(radarCenterX, radarCenterY);
      ctx.lineTo(
        radarCenterX + Math.cos(radarSweepAngle) * radarRadius,
        radarCenterY + Math.sin(radarSweepAngle) * radarRadius
      );
      ctx.strokeStyle = 'rgba(212, 175, 55, 0.25)';
      ctx.stroke();
      ctx.restore();

      // =======================================================================
      // 3. SMC ORDER BLOCK PROJECTIONS
      // =======================================================================
      for (const ob of orderBlocks) {
        ob.pulsePhase += 0.02;
        const currentOpacity = ob.opacity + Math.sin(ob.pulsePhase) * 0.03;
        ctx.save();
        ctx.fillStyle = ob.isBullish
          ? `rgba(16, 185, 129, ${Math.max(0.01, currentOpacity)})`
          : `rgba(239, 68, 68, ${Math.max(0.01, currentOpacity)})`;
        ctx.strokeStyle = ob.isBullish
          ? `rgba(16, 185, 129, ${currentOpacity * 2.2})`
          : `rgba(239, 68, 68, ${currentOpacity * 2.2})`;
        ctx.lineWidth = 1;
        ctx.strokeRect(ob.x, ob.y, ob.width, ob.height);
        ctx.fillRect(ob.x, ob.y, ob.width, ob.height);

        // Terminal coordinate micro-label
        ctx.font = '9px monospace';
        ctx.fillStyle = ob.isBullish ? 'rgba(52, 211, 153, 0.4)' : 'rgba(248, 113, 113, 0.4)';
        ctx.fillText(
          ob.isBullish ? `+ZONE[buy] ${ob.width.toFixed(0)}` : `-ZONE[SELL] ${ob.width.toFixed(0)}`,
          ob.x + 4,
          ob.y + 12
        );
        ctx.restore();
      }

      // =======================================================================
      // 4. INSTITUTIONAL LIQUIDITY WAVE WITH VOLATILITY OSCILLATOR
      // =======================================================================
      waveOffset += 0.009;
      const waveBaseY = height * 0.72;

      // Primary Gold SMC Trend Vector
      ctx.beginPath();
      ctx.strokeStyle = 'rgba(212, 175, 55, 0.25)';
      ctx.lineWidth = 2.0;

      for (let x = 0; x <= width; x += 12) {
        const y =
          waveBaseY +
          Math.sin(x * 0.0035 + waveOffset) * 55 +
          Math.cos(x * 0.0018 - waveOffset * 1.2) * 32;
        if (x === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.stroke();

      // Institutional Price Wick Candlestick Vectors along the wave
      const wickSpacing = isMobile ? 90 : 50;
      for (let x = 40; x < width; x += wickSpacing) {
        const sampleY =
          waveBaseY +
          Math.sin(x * 0.0035 + waveOffset) * 55 +
          Math.cos(x * 0.0018 - waveOffset * 1.2) * 32;
        const wickHeight = 22 + Math.sin(x + waveOffset * 4) * 14;

        ctx.strokeStyle = 'rgba(212, 175, 55, 0.35)';
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(x, sampleY - wickHeight);
        ctx.lineTo(x, sampleY + wickHeight);
        ctx.stroke();

        ctx.fillStyle = sampleY % 2 > 1 ? '#10B981' : '#EF4444';
        ctx.globalAlpha = 0.45;
        ctx.fillRect(x - 2.5, sampleY - wickHeight * 0.4, 5, wickHeight * 0.8);
        ctx.globalAlpha = 1.0;
      }

      // Secondary High-Frequency Cyan Wave (Order Book Delta)
      ctx.beginPath();
      ctx.strokeStyle = 'rgba(56, 189, 248, 0.12)';
      ctx.lineWidth = 1.5;
      for (let x = 0; x <= width; x += 16) {
        const y = waveBaseY + 45 + Math.cos(x * 0.0042 - waveOffset * 0.9) * 38;
        if (x === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.stroke();

      // =======================================================================
      // 5. QUANTUM PARTICLES WITH KINETIC MOMENTUM & MOUSE REPULSION
      // =======================================================================
      for (let i = 0; i < particles.length; i++) {
        const p = particles[i];

        p.opacity += p.twinkleSpeed;
        if (p.opacity > 0.85 || p.opacity < 0.2) {
          p.twinkleSpeed = -p.twinkleSpeed;
        }

        const dx = mouse.x - p.x;
        const dy = mouse.y - p.y;
        const dist = Math.sqrt(dx * dx + dy * dy);

        if (dist < mouse.radius && !isMobile) {
          const force = (mouse.radius - dist) / mouse.radius;
          const forceDirectionX = dx / dist;
          const forceDirectionY = dy / dist;
          p.x -= forceDirectionX * force * 5.2 * p.depth;
          p.y -= forceDirectionY * force * 5.2 * p.depth;
        } else {
          p.x += p.speedX * p.depth;
          p.y += p.speedY * p.depth;
        }

        if (p.x < 0) p.x = width;
        if (p.x > width) p.x = 0;
        if (p.y < 0) p.y = height;
        if (p.y > height) p.y = 0;

        ctx.beginPath();
        ctx.arc(p.x, p.y, p.size * p.depth, 0, Math.PI * 2);
        ctx.fillStyle = p.color;
        ctx.globalAlpha = Math.max(0.1, Math.min(1, p.opacity));
        ctx.shadowBlur = 10 * p.depth;
        ctx.shadowColor = p.color;
        ctx.fill();
        ctx.shadowBlur = 0;
      }

      ctx.globalAlpha = 1.0;
      animationFrameId = requestAnimationFrame(render);
    };

    animationFrameId = requestAnimationFrame(render);

    return () => {
      cancelAnimationFrame(animationFrameId);
      window.removeEventListener('resize', handleResize);
      if (!isMobile) {
        window.removeEventListener('mousemove', handleMouseMove);
        window.removeEventListener('mouseleave', handleMouseLeave);
      }
    };
  }, []);

  return (
    <div className="min-h-screen bg-[#03060a] text-[#E2E8F0] relative overflow-x-hidden w-full font-sans selection:bg-[#D4AF37] selection:text-black antialiased">
      {/* ======================================================================= */}
      {/* TIER-1 INSTITUTIONAL TICKER HUD BAR                                     */}
      {/* ======================================================================= */}
      <aside
        aria-label="Institutional Market Status"
        className="relative z-50 w-full bg-slate-950/80 backdrop-blur-md border-b border-[#D4AF37]/20 px-3 sm:px-6 py-1.5 flex items-center justify-between text-[11px] font-mono tracking-wider select-none"
      >
        <div className="flex items-center space-x-3 sm:space-x-6 overflow-x-auto no-scrollbar">
          <div className="flex items-center space-x-1.5 text-emerald-400">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
            </span>
            <span className="font-semibold">ENGINE: ACTIVE</span>
          </div>
          <div className="hidden sm:flex items-center space-x-2 text-slate-400">
            <TrendingUp className="w-3.5 h-3.5 text-[#D4AF37]" />
            <span>ASSET: <strong className="text-amber-400">XAUUSD [GOLD]</strong></span>
          </div>
          <div className="flex items-center space-x-1.5 text-slate-400">
            <Zap className="w-3 h-3 text-cyan-400" />
            <span>REGIME: <strong className="text-cyan-300 font-bold">{marketPhase}</strong></span>
          </div>
        </div>

        <div className="flex items-center space-x-4 text-slate-400">
          <div className="hidden md:flex items-center space-x-1.5">
            <Cpu className="w-3 h-3 text-[#D4AF37]" />
            <span>CORE: <span className="text-slate-200">IQWAN_V3</span></span>
          </div>
          <div className="flex items-center space-x-1.5 text-amber-400/90 font-mono">
            <Activity className="w-3 h-3 animate-pulse" />
            <span>{fps} FPS</span>
          </div>
        </div>
      </aside>

      {/* ======================================================================= */}
      {/* BACKGROUND ARCHITECTURE: THE QUANTUM INSTITUTIONAL MATRIX FUSION        */}
      {/* ======================================================================= */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
        {/* Volumetric Stage Beams */}
        <div
          className="absolute -top-20 left-1/2 -translate-x-1/2 w-[90%] sm:w-[70%] h-[650px] opacity-30"
          style={{
            background:
              'conic-gradient(from 180deg at 50% 0%, rgba(245, 158, 11, 0.35) 0deg, rgba(212, 175, 55, 0.15) 60deg, transparent 90deg, transparent 270deg, rgba(212, 175, 55, 0.15) 300deg, rgba(245, 158, 11, 0.35) 360deg)',
            filter: 'blur(60px)'
          }}
        />

        {/* Ambient Top Spotlight Emas & Cyberpunk Cyan Flare */}
        <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-[850px] h-[400px] bg-amber-500/20 rounded-full blur-[180px] animate-pulse" />
        <div className="absolute top-1/4 -left-36 w-[600px] h-[600px] bg-amber-500/10 rounded-full blur-[190px]" />
        <div className="absolute top-1/3 -right-36 w-[650px] h-[650px] bg-sky-500/10 rounded-full blur-[190px]" />

        {/* Cyber Matrix Dot Grid Perspective Layer */}
        <div
          className="absolute inset-0 opacity-20"
          style={{
            backgroundImage:
              'radial-gradient(rgba(212, 175, 55, 0.3) 1px, transparent 1px), radial-gradient(rgba(255, 255, 255, 0.15) 1px, transparent 1px)',
            backgroundSize: '40px 40px, 20px 20px',
            backgroundPosition: '0 0, 10px 10px',
            maskImage: 'radial-gradient(ellipse 80% 65% at 50% 35%, #000 70%, transparent 100%)'
          }}
        />

        {/* Cinematic CRT Scanline Overlay */}
        <div
          className="absolute inset-0 opacity-[0.03] pointer-events-none"
          style={{
            backgroundImage: 'repeating-linear-gradient(0deg, #000, #000 1px, transparent 1px, transparent 2px)',
            backgroundSize: '100% 2px'
          }}
        />

        {/* Interactive Quantum Canvas */}
        <canvas ref={canvasRef} className="absolute inset-0 w-full h-full" />
      </div>

      {/* Main Navigation Component */}
      <Navbar onOpenAdmin={onOpenAdmin} />

      {/* Primary Dynamic Content Area */}
      <main id="main-content" className="relative z-10">
        {children}
      </main>

      {/* Institutional Community Footer */}
      <CommunityFooterSection
        communityLinks={communityLinks}
        onOpenAdmin={onOpenAdmin}
      />

      {/* Anti-Theft Security Toast Notification */}
      {securityToast.show && (
        <div
          id="anti-theft-toast"
          role="alert"
          aria-live="polite"
          className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[100] flex items-center space-x-3.5 px-5 py-3 rounded-2xl bg-[#080d1a]/95 border border-[#D4AF37]/60 shadow-[0_12px_40px_rgba(0,0,0,0.9),0_0_30px_rgba(212,175,55,0.3)] backdrop-blur-xl animate-in fade-in slide-in-from-bottom-4 duration-300 pointer-events-none"
        >
          <div className="relative">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-[#D4AF37]/30 to-amber-500/10 border border-[#D4AF37]/60 flex items-center justify-center text-[#D4AF37] flex-shrink-0 shadow-[0_0_15px_rgba(212,175,55,0.4)]">
              <ShieldCheck className="w-4 h-4" />
            </div>
            <span className="absolute -top-1 -right-1 flex h-2.5 w-2.5">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-500"></span>
            </span>
          </div>
          <div className="flex flex-col">
            <span className="text-[10px] font-mono text-[#D4AF37] uppercase tracking-wider font-semibold">
              IQWANENGINE DEFENSE SYSTEM
            </span>
            <p className="text-xs font-mono text-slate-100 tracking-wide font-medium whitespace-nowrap">
              {securityToast.message}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
