// Generated by IqwanEngine
import React, { useState, useEffect } from 'react';

export const LiveClock: React.FC = () => {
  const [mounted, setMounted] = useState(false);
  const [time, setTime] = useState(new Date());

  useEffect(() => {
    setMounted(true);
    const interval = setInterval(() => {
      setTime(new Date());
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  if (!mounted) {
    return (
      <div className="flex flex-col sm:flex-row gap-1 sm:gap-2 text-[10px] sm:text-xs font-mono font-medium text-slate-400">
        <span className="opacity-0">--:--:-- UTC</span>
        <span className="hidden sm:inline opacity-0">|</span>
        <span className="opacity-0">--:--:-- MYT</span>
      </div>
    );
  }

  // Format UTC Time
  const utcHours = String(time.getUTCHours()).padStart(2, '0');
  const utcMins = String(time.getUTCMinutes()).padStart(2, '0');
  const utcSecs = String(time.getUTCSeconds()).padStart(2, '0');

  // Format MYT (Malaysia Time - UTC+8)
  // Use Intl.DateTimeFormat with Asia/Kuala_Lumpur to handle correct MYT time dynamically
  const formatter = new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Asia/Kuala_Lumpur',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false
  });
  
  const mytTimeStr = formatter.format(time); // Will return "HH:MM:SS"

  return (
    <div className="flex flex-col sm:flex-row gap-1 sm:gap-2 text-[10px] sm:text-xs font-mono font-medium">
      <span className="text-slate-300 tracking-wider">
        {utcHours}:{utcMins}:{utcSecs} UTC
      </span>
      <span className="hidden sm:inline text-slate-600">|</span>
      <span className="text-amber-500 tracking-wider">
        {mytTimeStr} MYT
      </span>
    </div>
  );
};
