// Generated by IqwanEngine
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { LiveEventAlertData } from '../types';
import { MapPin, Calendar, Zap, X, MessageCircle, ChevronRight, Radio } from 'lucide-react';



/**
 * Robust date parser supporting DD/MM/YYYY, YYYY-MM-DD, and Malay/English month formats.
 * Returns unix epoch in milliseconds.
 */
export function parseEventTimestamp(dateStr: string): number {
  if (!dateStr || !dateStr.trim()) return 0;
  const trimmed = dateStr.trim();

  // Parse DD/MM/YYYY or DD-MM-YYYY
  const dmyMatch = trimmed.match(/^(\d{1,2})[\/\.-](\d{1,2})[\/\.-](\d{4})$/);
  if (dmyMatch) {
    const day = parseInt(dmyMatch[1], 10);
    const month = parseInt(dmyMatch[2], 10) - 1;
    const year = parseInt(dmyMatch[3], 10);
    return new Date(year, month, day, 23, 59, 59, 999).getTime();
  }

  // Parse YYYY-MM-DD
  const ymdMatch = trimmed.match(/^(\d{4})[\/\.-](\d{1,2})[\/\.-](\d{1,2})$/);
  if (ymdMatch) {
    const year = parseInt(ymdMatch[1], 10);
    const month = parseInt(ymdMatch[2], 10) - 1;
    const day = parseInt(ymdMatch[3], 10);
    return new Date(year, month, day, 23, 59, 59, 999).getTime();
  }

  // Malay & English month dictionary
  const months: Record<string, number> = {
    jan: 0, januari: 0, january: 0,
    feb: 1, februari: 1, february: 1,
    mac: 2, mar: 2, march: 2,
    apr: 3, april: 3,
    mei: 4, may: 4,
    jun: 5, june: 5,
    jul: 6, julai: 6, july: 6,
    ogo: 7, ogos: 7, aug: 7, august: 7,
    sep: 8, september: 8, sept: 8,
    okt: 9, oktober: 9, oct: 9, october: 9,
    nov: 10, november: 10,
    dis: 11, disember: 11, dec: 11, december: 11
  };

  const parts = trimmed.toLowerCase().split(/\s+/);
  if (parts.length >= 3) {
    const day = parseInt(parts[0], 10);
    const monthKey = parts[1];
    const year = parseInt(parts[2], 10);
    if (!isNaN(day) && !isNaN(year) && months[monthKey] !== undefined) {
      return new Date(year, months[monthKey], day, 23, 59, 59, 999).getTime();
    }
  }

  const parsed = Date.parse(trimmed);
  if (!isNaN(parsed)) {
    const d = new Date(parsed);
    d.setHours(23, 59, 59, 999);
    return d.getTime();
  }

  return 0;
}

/**
 * Checks if the event date has already passed.
 */
export function isEventExpired(dateStr: string): boolean {
  const timestamp = parseEventTimestamp(dateStr);
  if (timestamp === 0) return false;
  return Date.now() > timestamp;
}

const CMS_ENDPOINT = (import.meta as any).env.VITE_CMS_ALERTS_ENDPOINT || "https://script.google.com/macros/s/AKfycbyt0FScPyyQUuMrATR7h4WTrUMZT7AM8Qujvga9JNC6pXvZiPefBOil-g-AoxOKE4jOUA/exec";

export const LiveEventAlert: React.FC = () => {
  const [dismissedIds, setDismissedIds] = useState<string[]>([]);
  const [alerts, setAlerts] = useState<LiveEventAlertData[]>([]);

  const fetchAlerts = () => {
    fetch(`${CMS_ENDPOINT}?_t=${Date.now()}`, { cache: "no-store" })
      .then(res => res.json())
      .then(res => {
        if (res && res.success && Array.isArray(res.data)) {
          setAlerts(res.data);
        } else {
          setAlerts([]);
        }
      })
      .catch(() => setAlerts([]));
  };

  useEffect(() => {
    fetchAlerts();

    const handleUpdate = () => fetchAlerts();
    window.addEventListener('owlfx-cms-updated', handleUpdate);
    
    return () => window.removeEventListener('owlfx-cms-updated', handleUpdate);
  }, []);

  // Filter active alerts regardless of date
  const validAlerts = (alerts || []).filter(
    (item) => item && item.isActive
  );

  // Exclude dismissed cards
  const remainingAlerts = validAlerts.filter((item, index) => {
    const cardId = item.id ? String(item.id) : `alert-${index}-${item.date}`;
    return !dismissedIds.includes(cardId);
  });

  // Chronological sort: Furthest date in future at the TOP, nearest date at the BOTTOM
  const sortedAlerts = [...remainingAlerts].sort((a, b) => {
    const timeA = parseEventTimestamp(a.date);
    const timeB = parseEventTimestamp(b.date);
    return timeB - timeA;
  });

  if (sortedAlerts.length === 0) {
    return null;
  }

  const handleDismiss = (cardId: string) => {
    setDismissedIds((prev) => [...prev, cardId]);
  };

  return (
    <aside
      id="live-floating-event-alerts-stack"
      role="complementary"
      aria-label="Pengumuman Acara Langsung OWLFX"
      className="fixed bottom-4 right-4 sm:bottom-6 sm:right-6 z-50 max-w-[360px] w-[calc(100%-2rem)] flex flex-col gap-2.5 sm:gap-3 items-end pointer-events-none select-none"
    >
      <AnimatePresence mode="popLayout">
        {sortedAlerts.map((alert, index) => {
          const cardId = alert.id ? String(alert.id) : `alert-${index}-${alert.date}`;
          const titleText = alert.title || alert.eventName || 'OWLFX';
          const whatsappUrl = `http://wasap.my/+60102263677/(Website)Hai,%20saya%20nak%20join%20kelas%20${encodeURIComponent(titleText)}`;

          return (
            <motion.div
              key={cardId}
              layout
              initial={{ opacity: 0, y: 20, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9, transition: { duration: 0.2 } }}
              transition={{ type: 'spring', stiffness: 350, damping: 25 }}
              className="w-full rounded-2xl p-[1px] bg-amber-500/30 shadow-[0_0_25px_rgba(245,158,11,0.2)] overflow-hidden pointer-events-auto"
            >
              <div className="relative rounded-[15px] bg-slate-950/95 backdrop-blur-md p-3 sm:p-4 text-white overflow-hidden border border-amber-500/30">
                {/* Ambient Top Glow Horizon */}
                <div className="absolute top-0 left-0 right-0 h-[1.5px] bg-gradient-to-r from-transparent via-[#D4AF37] to-transparent shadow-[0_0_10px_#D4AF37]" />

                {/* Header: Live Status & Individual Dismiss Action */}
                <div className="flex items-center justify-between pb-2 border-b border-white/10">
                  <div className="flex items-center min-w-0 pr-2 space-x-2">
                    <span className="relative flex h-2 w-2 shrink-0">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-rose-500 opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-2 w-2 bg-rose-500 shadow-[0_0_6px_#f43f5e]"></span>
                    </span>
                    <div className="flex items-center space-x-1 font-mono text-[11px] font-bold text-amber-400 uppercase tracking-wider truncate">
                      <Radio className="w-3 h-3 shrink-0 text-amber-400" />
                      <span className="truncate">LIVE EVENT COMING</span>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={() => handleDismiss(cardId)}
                    className="p-1 -mr-1 rounded-md text-slate-400 hover:text-white hover:bg-white/10 transition-colors cursor-pointer shrink-0"
                    title="Tutup Notifikasi Acara Ini"
                    aria-label="Tutup Notifikasi"
                  >
                    <X className="w-3.5 h-3.5 hover:text-rose-400 transition-colors" />
                  </button>
                </div>

                {/* Dynamic Event Details */}
                <div className="pt-2.5 space-y-2">
                  {alert.image_url && (
                    <img
                      src={alert.image_url}
                      alt={titleText}
                      className="rounded-xl border border-amber-500/20 object-cover max-h-36 w-full"
                    />
                  )}
                  <div className="flex items-start justify-between gap-2">
                    <h4 className="font-extrabold text-xs sm:text-sm text-white leading-snug tracking-tight">
                      {titleText}
                    </h4>

                    {alert.quota && (
                      <div className="shrink-0 text-[10px] font-bold text-amber-300 bg-amber-500/15 px-2 py-0.5 rounded-full border border-amber-500/30 inline-flex items-center gap-1 font-mono shadow-[0_0_8px_rgba(245,158,11,0.2)]">
                        <Zap className="w-2.5 h-2.5 text-amber-400" />
                        <span className="uppercase tracking-wider">{alert.quota}</span>
                      </div>
                    )}
                  </div>

                  <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-slate-300 font-sans">
                    <div className="flex items-center gap-1.5 min-w-0">
                      <div className="p-0.5 rounded bg-amber-500/15 text-amber-400 shrink-0 border border-amber-500/30">
                        <MapPin className="w-3 h-3" />
                      </div>
                      <span className="truncate text-slate-300 font-medium">
                        {alert.location}
                        {alert.state ? ` • ${alert.state}` : ''}
                      </span>
                    </div>

                    <div className="flex items-center gap-1.5 font-mono text-[10.5px] text-slate-400">
                      <div className="p-0.5 rounded bg-sky-500/15 text-sky-400 shrink-0 border border-sky-500/30">
                        <Calendar className="w-3 h-3" />
                      </div>
                      <span>{alert.date}</span>
                    </div>
                  </div>
                </div>

                {/* WhatsApp CTA Button with Candlestick Trend Wave */}
                <div className="mt-3 pt-0.5">
                  <a
                    href={whatsappUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="group relative w-full h-10 sm:h-11 rounded-xl bg-gradient-to-r from-emerald-600 to-emerald-500 border border-emerald-400/50 hover:border-emerald-300 overflow-hidden flex items-center justify-between px-3 transition-all duration-300 shadow-[0_0_15px_rgba(16,185,129,0.3)] hover:shadow-[0_0_25px_rgba(16,185,129,0.5)] hover:scale-[1.01] active:scale-[0.99] cursor-pointer block select-none"
                  >
                    {/* Embedded Candlestick Bars & Trendline Wave */}
                    <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-55 transition-opacity">
                      <div className="absolute inset-0 flex items-end justify-between px-2 pb-0.5 gap-1">
                        {[35, 70, 45, 80, 50, 95, 40, 75, 55, 90, 60, 85].map((h, i) => (
                          <motion.div
                            key={i}
                            className="w-[2px] rounded-t-sm"
                            style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
                            animate={{
                              height: [
                                `${Math.max(15, h * 0.3)}%`,
                                `${Math.min(95, h * 0.95)}%`,
                                `${Math.max(20, h * 0.45)}%`
                              ]
                            }}
                            transition={{
                              repeat: Infinity,
                              duration: 1.5 + (i % 4) * 0.25,
                              ease: 'easeInOut',
                              repeatType: 'reverse',
                              delay: i * 0.05
                            }}
                          />
                        ))}
                      </div>

                      {/* Moving Market Line Wave */}
                      <svg
                        className="absolute inset-0 w-[200%] h-full stroke-emerald-400"
                        viewBox="0 0 500 50"
                        preserveAspectRatio="none"
                      >
                        <motion.path
                          d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
                          fill="none"
                          strokeWidth="1.8"
                          strokeLinecap="round"
                          strokeDasharray="4 2"
                          animate={{ x: [0, -250] }}
                          transition={{
                            repeat: Infinity,
                            duration: 4,
                            ease: 'linear'
                          }}
                        />
                      </svg>

                      <div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/60 to-slate-950/80" />
                    </div>

                    {/* Specular White Shimmer Ray */}
                    <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/20 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

                    {/* Button Content */}
                    <div className="relative z-10 flex items-center space-x-2">
                      <div className="p-1 rounded bg-slate-950/20 text-slate-950 shrink-0">
                        <MessageCircle className="w-3.5 h-3.5" />
                      </div>
                      <span className="font-mono text-[11px] sm:text-xs font-bold uppercase tracking-wider text-slate-950 transition-colors">
                        Booking via WhatsApp
                      </span>
                    </div>

                    <div className="relative z-10 text-slate-950 group-hover:translate-x-1 transition-transform">
                      <ChevronRight className="w-3.5 h-3.5" />
                    </div>
                  </a>
                </div>
              </div>
            </motion.div>
          );
        })}
      </AnimatePresence>
    </aside>
  );
};
