// Generated by IqwanEngine
import React, { useState, useEffect } from 'react';
import { Menu, X, Lock, GraduationCap } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { Link, useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';

interface NavbarProps {
  onOpenAdmin: () => void;
}

interface MovingNavbarButtonProps {
  id?: string;
  onClick?: () => void;
  href?: string;
  label: string;
  className?: string;
}

/**
 * High-Precision Institutional Moving Chart Navbar Button
 * Features:
 * 1. Looping moving candlestick oscillation inside button canvas
 * 2. High-voltage gold gradient border and shimmer flare
 * 3. Strictly NO 360° Rotating Zap/Star Pods
 */
function MovingNavbarButton({ id, onClick, href, label, className = '' }: MovingNavbarButtonProps) {
  const content = (
    <div
      id={id}
      onClick={onClick}
      className={`group relative overflow-hidden rounded-full bg-gradient-to-r from-amber-500 via-amber-400 to-amber-600 px-6 py-2.5 flex items-center justify-center shadow-[0_0_25px_rgba(245,158,11,0.3)] transition-all duration-300 hover:scale-[1.03] active:scale-[0.97] cursor-pointer select-none ${className}`}
    >
      {/* Dynamic Candlestick Bars Wave in Background */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-35 group-hover:opacity-65 transition-opacity">
        <div className="absolute inset-0 flex items-end justify-between px-3 pb-0.5 gap-1">
          {[35, 65, 45, 80, 55, 90, 40, 75, 50, 85, 60, 95].map((h, i) => (
            <motion.div
              key={i}
              className="w-[2px] rounded-t-sm"
              style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
              animate={{
                height: [
                  `${Math.max(15, h * 0.3)}%`,
                  `${Math.min(95, h * 0.95)}%`,
                  `${Math.max(20, h * 0.4)}%`
                ]
              }}
              transition={{
                repeat: Infinity,
                duration: 1.5 + (i % 4) * 0.2,
                ease: 'easeInOut',
                repeatType: 'reverse',
                delay: i * 0.05
              }}
            />
          ))}
        </div>

        {/* Dynamic Continuous Moving Market Line Wave */}
        <svg
          className="absolute inset-0 w-[200%] h-full stroke-white/80"
          viewBox="0 0 500 50"
          preserveAspectRatio="none"
        >
          <motion.path
            d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
            fill="none"
            strokeWidth="1.6"
            strokeLinecap="round"
            strokeDasharray="4 2"
            animate={{ x: [0, -250] }}
            transition={{
              repeat: Infinity,
              duration: 4,
              ease: 'linear'
            }}
          />
        </svg>

        {/* Gradient mask for readable text */}
        <div className="absolute inset-0 bg-gradient-to-r from-amber-500/80 via-amber-400/80 to-amber-600/80" />
      </div>

      {/* Button Label */}
      <span className="relative z-10 text-[10px] font-black uppercase tracking-wider text-slate-950 font-sans">
        {label}
      </span>

      {/* Specular Glare Shimmer Ray */}
      <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/40 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />
    </div>
  );

  if (href) {
    return (
      <a href={href} target="_blank" rel="noopener noreferrer" className="inline-block">
        {content}
      </a>
    );
  }

  return content;
}

export const Navbar: React.FC<NavbarProps> = ({
  onOpenAdmin,
}) => {
  const { language, setLanguage, t } = useLanguage();
  const [isScrolled, setIsScrolled] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 20) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const { pathname } = useLocation();

  const navLinks = [
    { name: t.nav.about, href: '/about-us' },
    { name: t.nav.groupSupport, href: '/group-support' },
    { name: t.nav.owlAlgo, href: '/owlalgo' },
    { name: t.nav.roadtour, href: '/roadtour' },
    { name: t.nav.ibDevelopment, href: '/ib-development' },
    { name: t.nav.education, href: '/education' },
    { name: t.nav.community, href: '/contact' },
  ];

  return (
    <header
      id="main-navbar-header"
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled
          ? 'py-2.5 backdrop-blur-md md:backdrop-blur-xl bg-[#060911]/90 border-b border-[#D4AF37]/20 shadow-[0_10px_30px_rgba(0,0,0,0.8)]'
          : 'py-3.5 backdrop-blur-sm md:backdrop-blur-md bg-transparent'
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between">

          {/* Brand Logo Anchor (Strictly Static - NO 360 Rotating Gyro) */}
          <Link
            id="brand-logo-link"
            to="/"
            className="flex items-center space-x-3 group cursor-pointer"
            onClick={() => setMobileMenuOpen(false)}
          >
            <div className="relative w-10 h-10 sm:w-11 sm:h-11 flex items-center justify-center shrink-0">
              <div className="absolute inset-0 rounded-full border border-amber-500/30 group-hover:border-amber-400 pointer-events-none transition-colors duration-300" />
              <picture className="w-full h-full block">
                <source srcSet="/OWLFXpng.webp" type="image/webp" />
                <img
                  src="/OWLFXpng.png"
                  alt="OWLFX Official Logo"
                  width="44"
                  height="44"
                  // @ts-ignore
                  fetchPriority="high"
                  loading="eager"
                  decoding="sync"
                  className="w-full h-full object-contain drop-shadow-[0_0_15px_rgba(212,175,55,0.3)] group-hover:scale-105 transition-transform duration-300"
                  onError={(e) => {
                    const target = e.currentTarget;
                    if (!target.src.endsWith('OWLFXpng.png')) {
                      target.src = '/OWLFXpng.png';
                    }
                  }}
                />
              </picture>
            </div>

            <div className="flex flex-col">
              <div className="flex items-center space-x-1.5">
                <span className="text-2xl font-extrabold tracking-tight text-white uppercase font-sans">
                  OWL<span className="text-amber-400">FX</span>
                </span>
                <span className="inline-block px-1.5 py-0.5 rounded text-[9px] font-mono font-bold bg-cyan-500/15 text-cyan-400 border border-cyan-500/30 tracking-wider shadow-[0_0_10px_rgba(6,182,212,0.2)]">
                  {t.nav.badge}
                </span>
              </div>
              <span className="text-[9px] tracking-[0.3em] uppercase font-mono text-slate-400 font-bold">
                {t.nav.sub}
              </span>
            </div>
          </Link>

          {/* Desktop Navigation Links */}
          <nav
            id="desktop-nav-menu"
            className="hidden lg:flex items-center space-x-1 xl:space-x-2 backdrop-blur-md md:backdrop-blur-xl bg-slate-950/70 p-1.5 rounded-full border border-white/10 shadow-inner"
          >
            {navLinks.map((item) => {
              const isEducation = item.href === '/education';
              const isActive = pathname === item.href;

              if (isEducation) {
                return (
                  <Link
                    key={item.name}
                    to={item.href}
                    className={`group relative overflow-hidden px-4 py-1.5 text-[10px] font-black uppercase tracking-[0.15em] rounded-full transition-all duration-300 cursor-pointer flex items-center space-x-1.5 ${
                      isActive
                        ? 'bg-gradient-to-r from-emerald-500 via-teal-400 to-cyan-500 text-slate-950 shadow-[0_0_20px_rgba(16,185,129,0.4)] border border-emerald-300/80 scale-105'
                        : 'bg-emerald-950/40 text-emerald-400 border border-emerald-500/30 hover:border-emerald-400 hover:text-white hover:bg-emerald-900/60 shadow-[0_0_12px_rgba(16,185,129,0.15)]'
                    }`}
                  >
                    <GraduationCap className={`w-3.5 h-3.5 shrink-0 ${isActive ? 'text-slate-950' : 'text-emerald-400 group-hover:text-cyan-300'}`} />
                    <span>{item.name}</span>
                  </Link>
                );
              }

              return (
                <Link
                  key={item.name}
                  to={item.href}
                  className={`px-4 py-1.5 text-[10px] font-bold uppercase tracking-[0.15em] rounded-full transition-all duration-300 cursor-pointer ${
                    isActive
                      ? 'text-amber-300 bg-amber-500/15 border border-amber-500/30 shadow-[0_0_15px_rgba(245,158,11,0.2)]'
                      : 'text-slate-400 hover:text-white hover:bg-white/5'
                  }`}
                >
                  {item.name}
                </Link>
              );
            })}
          </nav>

          {/* Right Action Bar */}
          <div className="hidden sm:flex items-center space-x-3">
            {/* Language Switcher */}
            <div
              id="language-switcher"
              className="flex items-center backdrop-blur-md md:backdrop-blur-xl bg-slate-950/70 p-1 rounded-full border border-white/10 text-[10px] font-bold"
            >
              <button
                id="language-switch-my"
                type="button"
                onClick={() => setLanguage('MY')}
                className={`px-3 py-1 rounded-full transition-all duration-300 cursor-pointer ${
                  language === 'MY'
                    ? 'bg-amber-400 text-slate-950 font-black shadow-[0_0_15px_rgba(245,158,11,0.4)]'
                    : 'text-slate-400 hover:text-white'
                }`}
                title="Bahasa Melayu"
              >
                MY
              </button>
              <button
                id="language-switch-en"
                type="button"
                onClick={() => setLanguage('EN')}
                className={`px-3 py-1 rounded-full transition-all duration-300 cursor-pointer ${
                  language === 'EN'
                    ? 'bg-amber-400 text-slate-950 font-black shadow-[0_0_15px_rgba(245,158,11,0.4)]'
                    : 'text-slate-400 hover:text-white'
                }`}
                title="English"
              >
                EN
              </button>
            </div>

            {/* Quick Action: Daftar VIP with Moving Chart Button */}
            <MovingNavbarButton
              id="navbar-cta-vip"
              href="/interested?action=register"
              label={t.nav.ctaVip}
            />

            {/* Admin CMS Portal Trigger (Strictly Static - NO 360 Rotating Pod) */}
            <button
              id="navbar-admin-trigger"
              type="button"
              onClick={onOpenAdmin}
              className="p-2.5 rounded-full backdrop-blur-md md:backdrop-blur-xl bg-white/5 hover:bg-white/10 text-slate-400 hover:text-[#D4AF37] border border-white/10 transition-all cursor-pointer group shadow-md flex items-center justify-center"
              title="Panel Pengurusan Kandungan (Admin CMS)"
            >
              <Lock className="w-4 h-4 group-hover:text-amber-400 transition-colors" />
            </button>
          </div>

          {/* Mobile menu trigger */}
          <div className="flex sm:hidden items-center space-x-2">
            <button
              id="mobile-language-toggle"
              type="button"
              onClick={() => setLanguage(language === 'MY' ? 'EN' : 'MY')}
              className="px-3 py-1 text-xs rounded-full bg-white/5 border border-white/10 font-mono text-slate-200 cursor-pointer"
            >
              {language === 'MY' ? '🇲🇾 MY' : '🇬🇧 EN'}
            </button>

            <button
              id="mobile-hamburger-btn"
              type="button"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="p-2 rounded-full bg-white/5 border border-white/10 text-slate-200 cursor-pointer"
              aria-label="Buka Menu"
            >
              {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </div>
        </div>

        {/* Mobile Navigation Drawer */}
        {mobileMenuOpen && (
          <div
            id="mobile-nav-drawer"
            className="sm:hidden mt-3 p-5 rounded-3xl backdrop-blur-md md:backdrop-blur-2xl bg-slate-950/95 border border-[#D4AF37]/40 shadow-2xl animate-in slide-in-from-top duration-200 overflow-hidden"
          >
            <div className="flex flex-col space-y-2">
              {navLinks.map((item) => {
                const isEducation = item.href === '/education';
                const isActive = pathname === item.href;

                if (isEducation) {
                  return (
                    <Link
                      key={item.name}
                      to={item.href}
                      onClick={() => setMobileMenuOpen(false)}
                      className={`text-left px-4 py-3 rounded-2xl text-xs font-black uppercase tracking-wider cursor-pointer flex items-center justify-between ${
                        isActive
                          ? 'bg-gradient-to-r from-emerald-500 via-teal-400 to-cyan-500 text-slate-950 shadow-[0_0_20px_rgba(16,185,129,0.35)]'
                          : 'bg-emerald-950/40 text-emerald-400 border border-emerald-500/30'
                      }`}
                    >
                      <div className="flex items-center space-x-2">
                        <GraduationCap className="w-4 h-4" />
                        <span>{item.name}</span>
                      </div>
                      <span className="text-[9px] font-mono font-bold px-2 py-0.5 rounded-full bg-emerald-950 text-emerald-300 border border-emerald-500/30">
                        AKADEMI ELIT
                      </span>
                    </Link>
                  );
                }

                return (
                  <Link
                    key={item.name}
                    to={item.href}
                    onClick={() => setMobileMenuOpen(false)}
                    className={`text-left px-3 py-2.5 rounded-xl text-xs font-semibold uppercase tracking-wider cursor-pointer ${
                      isActive ? 'text-amber-300 bg-amber-500/15 border border-amber-500/30' : 'text-slate-300 hover:text-amber-400 hover:bg-white/5'
                    }`}
                  >
                    {item.name}
                  </Link>
                );
              })}

              <div className="pt-3 border-t border-white/10 flex flex-col space-y-3">
                <MovingNavbarButton
                  id="mobile-cta-vip"
                  href="/interested?action=register"
                  label={t.nav.ctaVip}
                  className="w-full py-3"
                />

                <button
                  id="mobile-admin-btn"
                  type="button"
                  onClick={() => {
                    setMobileMenuOpen(false);
                    onOpenAdmin();
                  }}
                  className="w-full py-3 rounded-full text-center text-xs font-mono text-slate-300 hover:text-amber-400 bg-white/5 border border-white/10 flex items-center justify-center space-x-2 cursor-pointer"
                >
                  <Lock className="w-3.5 h-3.5" />
                  <span>{t.nav.adminCms}</span>
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </header>
  );
};
