// Generated by IqwanEngine
import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import {
  Cpu,
  CheckCircle,
  ExternalLink,
  ArrowRight,
  Star,
  TrendingUp,
  TrendingDown,
  X,
  Zap
} from 'lucide-react';
import { INITIAL_TESTIMONIALS } from '../data/initialData';
import { useLanguage } from '../context/LanguageContext';
import { useScrollReveal } from '../hooks/useScrollReveal';

interface OwlAlgoSectionProps {
  onOpenLightbox?: (images: { url: string; caption?: string; title?: string }[], startIndex?: number) => void;
}

interface AlgoMovingChartButtonProps {
  id?: string;
  onClick?: () => void;
  href?: string;
  label: string;
  icon: React.ReactNode;
  variant: 'emerald' | 'rose' | 'gold' | 'cyan';
  className?: string;
}

/**
 * Reusable Institutional Button with Embedded Moving Candlestick/Wave Chart (Calm Static Icon - Zero Spin)
 */
function AlgoMovingChartButton({
  id,
  onClick,
  href,
  label,
  icon,
  variant,
  className = ''
}: AlgoMovingChartButtonProps) {
  const isEmerald = variant === 'emerald';
  const isRose = variant === 'rose';
  const isGold = variant === 'gold';

  const strokeColor = isEmerald ? '#10B981' : isRose ? '#F43F5E' : isGold ? '#F59E0B' : '#06B6D4';

  const baseStyle = isEmerald
    ? 'bg-slate-950/90 border border-emerald-500/30 hover:border-emerald-400 text-emerald-400 hover:text-white shadow-[0_0_20px_rgba(16,185,129,0.15)] hover:shadow-[0_0_30px_rgba(16,185,129,0.35)]'
    : isRose
    ? 'bg-slate-950/90 border border-rose-500/30 hover:border-rose-400 text-rose-400 hover:text-white shadow-[0_0_20px_rgba(244,63,94,0.15)] hover:shadow-[0_0_30px_rgba(244,63,94,0.35)]'
    : isGold
    ? 'bg-gradient-to-r from-amber-500 via-amber-400 to-[#D4AF37] text-slate-950 font-black shadow-[0_0_25px_rgba(245,158,11,0.25)]'
    : 'bg-slate-900/90 border border-cyan-500/30 hover:border-cyan-400 text-cyan-300 hover:text-white shadow-[0_0_20px_rgba(6,182,212,0.15)]';

  const content = (
    <div
      id={id}
      onClick={onClick}
      className={`group relative overflow-hidden rounded-2xl px-6 py-4 flex items-center justify-center space-x-3 transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] cursor-pointer select-none ${baseStyle} ${className}`}
    >
      {/* Dynamic Candlestick Bars Wave in Background */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-60 transition-opacity">
        <div className="absolute inset-0 flex items-end justify-between px-3 pb-1 gap-1">
          {[40, 75, 50, 85, 60, 95, 35, 80, 50, 90, 60, 75, 45, 85].map((h, i) => (
            <motion.div
              key={i}
              className="w-[2px] rounded-t-sm"
              style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
              animate={{
                height: [
                  `${Math.max(15, h * 0.3)}%`,
                  `${Math.min(95, h * 0.95)}%`,
                  `${Math.max(20, h * 0.45)}%`
                ]
              }}
              transition={{
                repeat: Infinity,
                duration: 1.5 + (i % 4) * 0.25,
                ease: 'easeInOut',
                repeatType: 'reverse',
                delay: i * 0.05
              }}
            />
          ))}
        </div>

        {/* Dynamic Continuous Moving Market Line Wave */}
        <svg
          className="absolute inset-0 w-[200%] h-full stroke-current"
          style={{ color: strokeColor }}
          viewBox="0 0 500 50"
          preserveAspectRatio="none"
        >
          <motion.path
            d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
            fill="none"
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeDasharray="4 2"
            animate={{ x: [0, -250] }}
            transition={{
              repeat: Infinity,
              duration: 4,
              ease: 'linear'
            }}
          />
        </svg>

        <div
          className={`absolute inset-0 ${
            isGold
              ? 'bg-gradient-to-r from-amber-400/80 via-amber-300/60 to-amber-500/90'
              : 'bg-gradient-to-r from-slate-950 via-slate-950/70 to-slate-950/90'
          }`}
        />
      </div>

      {/* Shimmer Specular Light Sweep */}
      <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/25 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

      {/* Button Content with Sleek Static Icon (Zero Rotation) */}
      <div className="relative z-10 flex items-center justify-center transition-transform duration-300 group-hover:scale-110">
        {icon}
      </div>

      <span className="relative z-10 font-mono text-xs sm:text-sm font-bold uppercase tracking-wider drop-shadow-sm">
        {label}
      </span>
    </div>
  );

  if (href) {
    return (
      <a href={href} target="_blank" rel="noopener noreferrer" className="inline-block w-full">
        {content}
      </a>
    );
  }

  return content;
}

const RESULT_GROUP_IMAGES = [
  "https://owlfx.online/cdn/shop/files/IMG_0361.png?v=1782731631&width=900",
  "https://owlfx.online/cdn/shop/files/IMG_0362.png?v=1782731650&width=900",
  "https://owlfx.online/cdn/shop/files/IMG_0370.png?v=1782731700&width=900",
  "https://owlfx.online/cdn/shop/files/IMG_0372.png?v=1782731724&width=900",
  "https://owlfx.online/cdn/shop/files/IMG_0373.png?v=1782731753&width=900",
  "https://owlfx.online/cdn/shop/files/IMG_0371.png?v=1782732013&width=900",
  "https://owlfx.online/cdn/shop/files/IMG_0366.png?v=1782732117&width=900",
  "https://owlfx.online/cdn/shop/files/IMG_0369.png?v=1782732198&width=900"
];

const TESTIMONIAL_PERSONAL_IMAGES = [
  "https://brocepris.com/cdn/shop/files/4.jpg?v=1784299785&width=1400",
  "https://brocepris.com/cdn/shop/files/2.jpg?v=1784300142&width=1400",
  "https://brocepris.com/cdn/shop/files/WhatsApp_Image_2026-07-15_at_21.03.24.jpg?v=1784302292&width=1400",
  "https://brocepris.com/cdn/shop/files/WhatsApp_Image_2026-07-17_at_13.40.22.jpg?v=1784300185&width=1400"
];

const TIMEFRAME_CHART_IMAGES: Record<'M5' | 'M15' | 'M30' | 'H1', string> = {
  M5: 'https://i.imgur.com/6R4Xg5i.png',
  M15: 'https://i.imgur.com/pZbLzmL.png',
  M30: 'https://i.imgur.com/g0Rxl3l.png',
  H1: 'https://i.imgur.com/hlZSlrI.png',
};

const SETUP_MODAL_DATA = {
  buy: {
    kicker: '01',
    category: 'TRADING SETUP',
    title: 'Setup Buy',
    description: 'Daripada confirmation indicator kepada execution sebenar di MT5.',
    signalBadge: 'OWL ALGO • SIGNAL',
    signalImage: 'https://brocepris.com/cdn/shop/files/Buy_B.jpg?v=1784345290&width=1600',
    signalCaption: 'Setup dan confirmation yang dikenal pasti melalui Owl Algo.',
    entryBadge: 'MT5 ENTRY • REAL EXECUTION',
    entryImage: 'https://brocepris.com/cdn/shop/files/Buy_A.jpg?v=1784345325&width=1600',
    entryCaption: 'Execution entry sebenar selepas confirmation setup diperoleh.',
  },
  sell: {
    kicker: '02',
    category: 'TRADING SETUP',
    title: 'Setup Sell',
    description: 'Contoh bagaimana indicator membantu melihat setup dengan lebih tersusun dan objektif.',
    signalBadge: 'OWL ALGO • SIGNAL',
    signalImage: 'https://brocepris.com/cdn/shop/files/1b.jpg?v=1784345430&width=1600',
    signalCaption: 'Setup dan confirmation yang dikenal pasti melalui Owl Algo.',
    entryBadge: 'MT5 ENTRY • REAL EXECUTION',
    entryImage: 'https://brocepris.com/cdn/shop/files/WhatsApp_Image_2026-07-18_at_00.48.01.jpg?v=1784345451&width=1600',
    entryCaption: 'Execution entry sebenar selepas confirmation setup diperoleh.',
  },
};

export const OwlAlgoSection: React.FC<OwlAlgoSectionProps> = ({ onOpenLightbox }) => {
  const { t } = useLanguage();
  const [selectedTF, setSelectedTF] = useState<'M5' | 'M15' | 'M30' | 'H1'>('M15');
  const [modalSetup, setModalSetup] = useState<'buy' | 'sell' | null>(null);
  const [zoomedImage, setZoomedImage] = useState<{ url: string; title: string; caption: string } | null>(null);
  const containerRef = useScrollReveal();

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (zoomedImage) {
          setZoomedImage(null);
        } else if (modalSetup) {
          setModalSetup(null);
        }
      }
    };
    if (modalSetup || zoomedImage) {
      window.addEventListener('keydown', handleKeyDown);
    }
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [modalSetup, zoomedImage]);

  return (
    <section
      id="owl-algo"
      ref={containerRef}
      className="py-24 relative bg-[#06090E] border-t border-white/5 overflow-hidden selection:bg-[#D4AF37] selection:text-black"
    >
      {/* Ambient Volumetric Backlight */}
      <div className="absolute top-1/4 -left-32 w-[600px] h-[600px] bg-cyan-500/5 rounded-full blur-[170px] pointer-events-none -z-10" />
      <div className="absolute bottom-1/3 -right-32 w-[600px] h-[600px] bg-amber-500/5 rounded-full blur-[170px] pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Section Header with Sleek Pulsing Badge (Zero Spin) */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center space-x-2.5 px-4 py-1.5 rounded-full bg-[#D4AF37]/10 border border-[#D4AF37]/30 text-[#D4AF37] text-xs font-mono mb-4 shadow-[0_0_20px_rgba(212,175,55,0.15)]">
            <div className="flex items-center justify-center text-[#D4AF37]">
              <Cpu className="w-4 h-4 animate-pulse" />
            </div>
            <span className="font-bold tracking-wider uppercase">{t.algo.badge}</span>
          </div>

          <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight uppercase">
            {t.algo.title1}{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-amber-400 to-[#D4AF37] drop-shadow-[0_0_25px_rgba(245,158,11,0.3)]">
              {t.algo.title2}
            </span>
          </h2>
          <p className="mt-4 text-slate-400 text-sm sm:text-base leading-relaxed font-medium">
            {t.algo.description}
          </p>
        </div>

        {/* High-Tech Real Chart Display Container (Obsidian Glass) */}
        <div
          id="owl-algo-real-chart-container"
          className="rounded-3xl bg-[#080d19]/95 border border-white/10 shadow-[0_20px_50px_rgba(0,0,0,0.85)] overflow-hidden mb-10 relative"
        >
          {/* Top Bar / Timeframe Header */}
          <div className="flex flex-wrap items-center justify-between px-5 py-3.5 bg-[#0a1020] border-b border-white/10 text-xs font-mono gap-3">
            {/* Pair Label & Institutional Feed Status */}
            <div className="flex items-center space-x-2.5 py-1">
              <span className="flex h-2.5 w-2.5 relative">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-500 shadow-[0_0_8px_#10b981]"></span>
              </span>
              <div className="flex items-center space-x-2">
                <span className="text-white font-extrabold tracking-wide">XAUUSD (GOLD)</span>
                <span className="text-slate-600">•</span>
                <span className="text-cyan-400 text-[11px] font-bold tracking-wider">CHART VIEW ({selectedTF})</span>
              </div>
            </div>

            {/* Timeframe Selectors: [ M5 ], [ M15 ], [ M30 ], [ H1 ] */}
            <div className="flex items-center space-x-2 py-1">
              {(['M5', 'M15', 'M30', 'H1'] as const).map((tf) => (
                <button
                  key={tf}
                  id={`tf-btn-${tf.toLowerCase()}`}
                  type="button"
                  onClick={() => setSelectedTF(tf)}
                  className={`px-3.5 py-1.5 rounded-xl text-xs font-mono font-black transition-all cursor-pointer ${
                    selectedTF === tf
                      ? 'bg-gradient-to-r from-amber-400 via-[#D4AF37] to-cyan-400 text-slate-950 shadow-[0_0_18px_rgba(212,175,55,0.4)] scale-105'
                      : 'text-slate-300 bg-slate-900/80 border border-white/10 hover:border-cyan-400/80 hover:text-cyan-300'
                  }`}
                >
                  {tf}
                </button>
              ))}
            </div>

            {/* TradingView Script Direct Link */}
            <div className="flex items-center space-x-3 py-1 text-slate-300">
              <a
                id="tradingview-script-link-btn"
                href="https://www.tradingview.com/script/2ZIMV08M-OWLALGO/"
                target="_blank"
                rel="noopener noreferrer"
                className="group flex items-center space-x-2 px-4 py-1.5 rounded-xl bg-[#2563EB]/20 hover:bg-[#2563EB]/30 border border-[#2563EB]/40 text-[#60A5FA] hover:text-white font-bold text-xs shadow-[0_0_15px_rgba(37,99,235,0.25)] transition-all cursor-pointer"
              >
                <span>{t.algo.btnScript}</span>
                <ExternalLink className="w-3.5 h-3.5 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform duration-300" />
              </a>
            </div>
          </div>

          {/* Chart Image Display */}
          <div className="relative w-full bg-[#050811] p-3 sm:p-6 flex items-center justify-center min-h-[320px] sm:min-h-[440px] select-none">
            <img
              key={selectedTF}
              id={`chart-image-${selectedTF.toLowerCase()}`}
              src={TIMEFRAME_CHART_IMAGES[selectedTF]}
              alt={`Owl Algo Chart ${selectedTF}`}
              loading="lazy"
              decoding="async"
              referrerPolicy="no-referrer"
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
              }}
              onAuxClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
              }}
              onContextMenu={(e) => e.preventDefault()}
              onDragStart={(e) => e.preventDefault()}
              className="w-full h-auto max-h-[520px] object-contain rounded-2xl transition-all duration-300 shadow-2xl border border-slate-800/80 select-none cursor-default"
            />
          </div>

          {/* Bottom Chart Status Bar */}
          <div className="flex flex-wrap items-center justify-between px-5 py-3 bg-[#080d19] border-t border-white/5 text-[11px] font-mono text-slate-400 gap-2">
            <div className="flex items-center space-x-2.5">
              <span className="text-[#D4AF37] font-bold">OWL ALGO INDICATOR</span>
              <span>•</span>
              <span className="text-emerald-400 font-bold">LIVE SETUP: {selectedTF} CONFIRMED</span>
            </div>
            <div className="text-cyan-400 font-medium text-[10px] sm:text-[11px]">
              TRADINGVIEW PROPRIETARY ALGORITHM
            </div>
          </div>
        </div>

        {/* Dual Action Buttons with Moving Candlestick Wave: Lihat Setup Buy & Setup Sell */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 mb-16 max-w-4xl mx-auto">
          <AlgoMovingChartButton
            id="btn-view-setup-buy"
            onClick={() => setModalSetup('buy')}
            label="LIHAT SETUP BUY"
            icon={<TrendingUp className="w-5 h-5 text-emerald-400" />}
            variant="emerald"
          />

          <AlgoMovingChartButton
            id="btn-view-setup-sell"
            onClick={() => setModalSetup('sell')}
            label="LIHAT SETUP SELL"
            icon={<TrendingDown className="w-5 h-5 text-rose-400" />}
            variant="rose"
          />
        </div>

        {/* Dual Infinite Horizontal Testimonial Loop */}
        <div className="w-full max-w-full overflow-hidden relative py-6 mb-16 space-y-8">
          {/* BARIS 1: RESULT GROUP SUPPORT OWLFX */}
          <div className="space-y-3">
            <div className="flex items-center space-x-2.5 px-3.5 py-1.5 rounded-full bg-cyan-950/60 border border-cyan-500/30 text-cyan-400 text-xs font-mono w-fit shadow-[0_0_15px_rgba(6,182,212,0.2)]">
              <span className="h-2 w-2 rounded-full bg-cyan-400 animate-pulse shadow-[0_0_8px_#22d3ee]"></span>
              <span className="font-bold tracking-wider">HASIL SETUP &amp; RESULT GROUP VIP</span>
            </div>

            <div className="w-full max-w-full overflow-hidden relative py-2">
              <div className="pointer-events-none absolute inset-y-0 left-0 w-16 sm:w-32 bg-gradient-to-r from-[#06090E] to-transparent z-10" />
              <div className="pointer-events-none absolute inset-y-0 right-0 w-16 sm:w-32 bg-gradient-to-l from-[#06090E] to-transparent z-10" />

              <div className="animate-marquee-left flex items-center space-x-4 sm:space-x-6 hover:[animation-play-state:paused]">
                {RESULT_GROUP_IMAGES.map((imgUrl, idx) => (
                  <div
                    key={`row1-item-${idx}`}
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      onOpenLightbox?.(
                        RESULT_GROUP_IMAGES.map((u, i) => ({
                          url: u,
                          title: `Hasil Setup & Result Group VIP #${i + 1}`,
                          caption: 'Pengesahan hasil posisi dan perkongsian setup ahli komuniti OWLFX.'
                        })),
                        idx
                      );
                    }}
                    onAuxClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                    }}
                    className="shrink-0 rounded-2xl border border-cyan-500/20 hover:border-cyan-400/80 bg-slate-950/90 shadow-xl overflow-hidden group cursor-pointer transition-all duration-300"
                  >
                    <img
                      src={imgUrl}
                      alt={`Hasil Setup Group VIP ${idx + 1}`}
                      loading="lazy"
                      decoding="async"
                      referrerPolicy="no-referrer"
                      onContextMenu={(e) => e.preventDefault()}
                      onDragStart={(e) => e.preventDefault()}
                      className="bc-feedback-image h-[260px] sm:h-[300px] lg:h-[380px] w-auto max-w-none object-contain rounded-2xl transition-transform duration-500 group-hover:scale-[1.02] select-none"
                    />
                  </div>
                ))}

                {RESULT_GROUP_IMAGES.map((imgUrl, idx) => (
                  <div
                    key={`row1-clone-${idx}`}
                    aria-hidden="true"
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      onOpenLightbox?.(
                        RESULT_GROUP_IMAGES.map((u, i) => ({
                          url: u,
                          title: `Hasil Setup & Result Group VIP #${i + 1}`,
                          caption: 'Pengesahan hasil posisi dan perkongsian setup ahli komuniti OWLFX.'
                        })),
                        idx
                      );
                    }}
                    onAuxClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                    }}
                    className="shrink-0 rounded-2xl border border-cyan-500/20 hover:border-cyan-400/80 bg-slate-950/90 shadow-xl overflow-hidden group cursor-pointer transition-all duration-300"
                  >
                    <img
                      src={imgUrl}
                      alt=""
                      loading="lazy"
                      referrerPolicy="no-referrer"
                      onContextMenu={(e) => e.preventDefault()}
                      onDragStart={(e) => e.preventDefault()}
                      className="bc-feedback-image h-[260px] sm:h-[300px] lg:h-[380px] w-auto max-w-none object-contain rounded-2xl transition-transform duration-500 group-hover:scale-[1.02] select-none"
                    />
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* BARIS 2: TESTIMONI PERSONAL & KOMUNITI */}
          <div className="space-y-3">
            <div className="flex items-center space-x-2.5 px-3.5 py-1.5 rounded-full bg-amber-950/60 border border-[#D4AF37]/30 text-[#D4AF37] text-xs font-mono w-fit shadow-[0_0_15px_rgba(212,175,55,0.2)]">
              <span className="h-2 w-2 rounded-full bg-[#F59E0B] animate-pulse shadow-[0_0_8px_#f59e0b]"></span>
              <span className="font-bold tracking-wider">MAKLUM BALAS &amp; TESTIMONI TRADER</span>
            </div>

            <div className="w-full max-w-full overflow-hidden relative py-2">
              <div className="pointer-events-none absolute inset-y-0 left-0 w-16 sm:w-32 bg-gradient-to-r from-[#06090E] to-transparent z-10" />
              <div className="pointer-events-none absolute inset-y-0 right-0 w-16 sm:w-32 bg-gradient-to-l from-[#06090E] to-transparent z-10" />

              <div className="animate-marquee-right flex items-center space-x-4 sm:space-x-6 hover:[animation-play-state:paused]">
                {[...TESTIMONIAL_PERSONAL_IMAGES, ...TESTIMONIAL_PERSONAL_IMAGES].map((imgUrl, idx) => (
                  <div
                    key={`row2-item-${idx}`}
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      onOpenLightbox?.(
                        TESTIMONIAL_PERSONAL_IMAGES.map((u, i) => ({
                          url: u,
                          title: `Maklum Balas & Testimoni #${i + 1}`,
                          caption: 'Perbualan WhatsApp dan maklum balas jujur komuniti trader OWLFX.'
                        })),
                        idx % TESTIMONIAL_PERSONAL_IMAGES.length
                      );
                    }}
                    onAuxClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                    }}
                    className="shrink-0 rounded-2xl border border-white/10 hover:border-amber-400/60 bg-slate-950/90 shadow-xl overflow-hidden group cursor-pointer transition-all duration-300"
                  >
                    <img
                      src={imgUrl}
                      alt={`Maklum Balas Trader ${(idx % TESTIMONIAL_PERSONAL_IMAGES.length) + 1}`}
                      loading="lazy"
                      decoding="async"
                      referrerPolicy="no-referrer"
                      onContextMenu={(e) => e.preventDefault()}
                      onDragStart={(e) => e.preventDefault()}
                      className="bc-feedback-image h-[260px] sm:h-[300px] lg:h-[380px] w-auto max-w-none object-contain rounded-2xl transition-transform duration-500 group-hover:scale-[1.02] select-none"
                    />
                  </div>
                ))}

                {[...TESTIMONIAL_PERSONAL_IMAGES, ...TESTIMONIAL_PERSONAL_IMAGES].map((imgUrl, idx) => (
                  <div
                    key={`row2-clone-${idx}`}
                    aria-hidden="true"
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      onOpenLightbox?.(
                        TESTIMONIAL_PERSONAL_IMAGES.map((u, i) => ({
                          url: u,
                          title: `Maklum Balas & Testimoni #${i + 1}`,
                          caption: 'Perbualan WhatsApp dan maklum balas jujur komuniti trader OWLFX.'
                        })),
                        idx % TESTIMONIAL_PERSONAL_IMAGES.length
                      );
                    }}
                    onAuxClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                    }}
                    className="shrink-0 rounded-2xl border border-white/10 hover:border-amber-400/60 bg-slate-950/90 shadow-xl overflow-hidden group cursor-pointer transition-all duration-300"
                  >
                    <img
                      src={imgUrl}
                      alt=""
                      loading="lazy"
                      referrerPolicy="no-referrer"
                      onContextMenu={(e) => e.preventDefault()}
                      onDragStart={(e) => e.preventDefault()}
                      className="bc-feedback-image h-[260px] sm:h-[300px] lg:h-[380px] w-auto max-w-none object-contain rounded-2xl transition-transform duration-500 group-hover:scale-[1.02] select-none"
                    />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Valetax MIB Account Activation CTA Box */}
        <div className="p-8 sm:p-10 rounded-3xl bg-gradient-to-br from-[#080d1a] via-[#10172d] to-[#080d1a] border border-[#D4AF37]/50 shadow-[0_20px_50px_rgba(0,0,0,0.85)] flex flex-col lg:flex-row items-center justify-between gap-8 mb-16 relative overflow-hidden">

          <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-[#D4AF37]/80 to-transparent" />

          <div className="max-w-2xl">
            <div className="flex items-center space-x-2 text-[#D4AF37] font-mono text-xs font-bold mb-3">
              <Zap className="w-4 h-4 text-[#F59E0B]" />
              <span>{t.algo.ctaBadge}</span>
            </div>
            <h3 className="text-2xl sm:text-3xl font-black text-white mb-3 uppercase tracking-tight">
              {t.algo.ctaTitle}
            </h3>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed mb-6 font-medium">
              {t.algo.ctaDesc}
            </p>
            <ul className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs text-slate-300 font-mono">
              <li className="flex items-center space-x-2">
                <CheckCircle className="w-4 h-4 text-[#10B981] shrink-0" />
                <span>{t.algo.ctaFeature1}</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle className="w-4 h-4 text-[#10B981] shrink-0" />
                <span>{t.algo.ctaFeature2}</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle className="w-4 h-4 text-[#10B981] shrink-0" />
                <span>{t.algo.ctaFeature3}</span>
              </li>
            </ul>
          </div>

          <div className="w-full lg:w-80 shrink-0 space-y-4">
            <AlgoMovingChartButton
              id="algo-cta-tradingview-btn"
              href="https://www.tradingview.com/script/2ZIMV08M-OWLALGO/"
              label={t.algo.btnScript}
              icon={<ExternalLink className="w-4 h-4 text-[#60A5FA]" />}
              variant="cyan"
            />

            <AlgoMovingChartButton
              id="algo-cta-valetax-btn"
              href="/my/register"
              label={t.algo.ctaButton}
              icon={<ArrowRight className="w-4 h-4 text-slate-950" />}
              variant="gold"
            />
          </div>
        </div>

        {/* Trader Testimonials & Feedback Grid */}
        <div className="rounded-3xl bg-[#080d19]/90 border border-white/10 p-6 sm:p-10 shadow-2xl">
          <div className="flex items-center justify-between mb-8">
            <div>
              <span className="text-xs font-mono text-[#D4AF37] font-bold uppercase tracking-wider">SUARA KOMUNITI TRADER</span>
              <h3 className="text-xl sm:text-2xl font-black text-white tracking-tight">Hasil & Maklum Balas Trader Sebenar</h3>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {INITIAL_TESTIMONIALS.slice(0, 2).map((testi) => (
              <div
                key={testi.id}
                className="p-6 rounded-2xl bg-slate-950/80 border border-white/5 hover:border-[#D4AF37]/40 transition-all flex flex-col justify-between shadow-lg"
              >
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <div className="flex items-center space-x-3">
                      <img
                        src={testi.avatar}
                        alt={testi.name}
                        className="w-12 h-12 rounded-full object-cover border border-[#D4AF37]/40 shadow-md"
                      />
                      <div>
                        <div className="flex items-center space-x-1.5">
                          <span className="text-sm font-bold text-white">{testi.name}</span>
                          {testi.verifiedBadge && (
                            <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-950 text-emerald-400 border border-emerald-500/30 font-mono font-bold">
                              TERSAH
                            </span>
                          )}
                        </div>
                        <span className="text-xs text-slate-400 font-mono">{testi.role} • {testi.location}</span>
                      </div>
                    </div>

                    <div className="text-right font-mono">
                      <span className="text-[10px] text-slate-400 block uppercase">HASIL DIJANA</span>
                      <span className="text-xs font-black text-emerald-400">{testi.profit}</span>
                    </div>
                  </div>

                  <p className="text-xs sm:text-sm text-slate-300 leading-relaxed italic font-medium">
                    "{testi.comment}"
                  </p>
                </div>

                <div className="flex items-center space-x-1.5 mt-5 pt-4 border-t border-white/5">
                  {[...Array(testi.rating)].map((_, i) => (
                    <div key={i} className="flex items-center justify-center">
                      <Star className="w-3.5 h-3.5 fill-[#F59E0B] text-[#F59E0B]" />
                    </div>
                  ))}
                  <span className="text-xs font-mono text-slate-400 ml-2">5.0 Star Rating</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Comparison Modal (Setup Buy / Setup Sell) */}
      {modalSetup && (
        <div
          id="setup-comparison-modal-backdrop"
          className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/85 backdrop-blur-md overflow-y-auto animate-in fade-in duration-200"
          onClick={() => setModalSetup(null)}
        >
          <div
            id="setup-comparison-modal-content"
            className="relative w-full max-w-5xl bg-[#080d19] border border-white/10 rounded-3xl shadow-[0_20px_50px_rgba(0,0,0,0.9)] overflow-hidden my-auto max-h-[92vh] flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-[#0a1020] flex-shrink-0">
              <div className="flex items-center space-x-3">
                <span
                  className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-mono font-bold uppercase tracking-wider ${
                    modalSetup === 'buy'
                      ? 'bg-emerald-950/80 border border-emerald-500/40 text-emerald-400'
                      : 'bg-rose-950/80 border border-rose-500/40 text-rose-400'
                  }`}
                >
                  {SETUP_MODAL_DATA[modalSetup].category} • {SETUP_MODAL_DATA[modalSetup].kicker}
                </span>
                <h3 className="text-lg sm:text-xl font-black text-white tracking-tight flex items-center space-x-2">
                  <span>{SETUP_MODAL_DATA[modalSetup].title}</span>
                  {modalSetup === 'buy' ? (
                    <TrendingUp className="w-5 h-5 text-emerald-400 inline" />
                  ) : (
                    <TrendingDown className="w-5 h-5 text-rose-400 inline" />
                  )}
                </h3>
              </div>

              <button
                id="btn-close-setup-modal"
                type="button"
                onClick={() => setModalSetup(null)}
                className="p-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white transition-colors cursor-pointer border border-white/10"
                aria-label="Tutup Modal"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Subheader */}
            <div className="px-6 py-3 bg-[#060911] border-b border-white/5 text-xs sm:text-sm text-slate-300 font-mono flex items-center justify-between flex-wrap gap-2 flex-shrink-0">
              <span>{SETUP_MODAL_DATA[modalSetup].description}</span>
              <div className="flex items-center space-x-2">
                <button
                  type="button"
                  onClick={() => setModalSetup(modalSetup === 'buy' ? 'sell' : 'buy')}
                  className="text-xs text-cyan-400 hover:text-cyan-300 underline font-semibold cursor-pointer"
                >
                  {modalSetup === 'buy' ? 'Lihat Setup Sell →' : '← Lihat Setup Buy'}
                </button>
              </div>
            </div>

            {/* Modal Body */}
            <div className="p-4 sm:p-6 max-h-[85vh] overflow-y-auto flex flex-col md:grid md:grid-cols-2 gap-5 bg-[#050811]">
              {/* Card 1: Owl Algo Signal */}
              <div className="flex flex-col p-4 sm:p-5 bg-slate-950/80 border border-white/10 rounded-2xl overflow-hidden shadow-xl">
                <div className="mb-3 sm:mb-4 relative z-10 flex items-center justify-between px-4 py-2.5 bg-[#0d1424] border border-white/5 rounded-xl flex-shrink-0">
                  <div className="flex items-center space-x-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-cyan-400 shadow-[0_0_8px_rgba(6,182,212,0.6)]" />
                    <span className="text-xs font-mono font-bold text-cyan-400 tracking-wide">
                      {SETUP_MODAL_DATA[modalSetup].signalBadge}
                    </span>
                  </div>
                  <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded bg-cyan-950/70 text-cyan-300 border border-cyan-500/30">
                    TRADINGVIEW
                  </span>
                </div>

                <div
                  className="w-full relative flex items-center justify-center bg-slate-900/40 rounded-xl p-2 sm:p-3 border border-white/5 h-[340px] sm:h-[420px] md:h-[480px] overflow-hidden group cursor-pointer"
                  onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    setZoomedImage({
                      url: SETUP_MODAL_DATA[modalSetup].signalImage,
                      title: `${SETUP_MODAL_DATA[modalSetup].title} • ${SETUP_MODAL_DATA[modalSetup].signalBadge}`,
                      caption: SETUP_MODAL_DATA[modalSetup].signalCaption,
                    });
                  }}
                  title="Klik untuk besarkan paparan penuh"
                >
                  <img
                    src={SETUP_MODAL_DATA[modalSetup].signalImage}
                    alt={`${SETUP_MODAL_DATA[modalSetup].title} Signal`}
                    referrerPolicy="no-referrer"
                    className="w-auto h-full max-h-full max-w-full object-contain cursor-zoom-in rounded-lg shadow-md transition-transform duration-300 hover:scale-[1.02] select-none"
                  />
                  <span className="bg-black/70 text-slate-200 text-[10px] px-2.5 py-1 rounded-lg backdrop-blur-sm pointer-events-none absolute bottom-3 right-3 border border-white/10 flex items-center space-x-1 shadow-md font-mono">
                    <span>🔍 Zoom Paparan HD</span>
                  </span>
                </div>

                <div className="mt-3 sm:mt-4 p-3.5 rounded-xl bg-[#080d19] border border-white/5 text-xs text-slate-300 font-mono leading-relaxed">
                  {SETUP_MODAL_DATA[modalSetup].signalCaption}
                </div>
              </div>

              {/* Card 2: MT5 Entry Real Execution */}
              <div className="flex flex-col p-4 sm:p-5 bg-slate-950/80 border border-white/10 rounded-2xl overflow-hidden shadow-xl">
                <div className="mb-3 sm:mb-4 relative z-10 flex items-center justify-between px-4 py-2.5 bg-[#0d1424] border border-white/5 rounded-xl flex-shrink-0">
                  <div className="flex items-center space-x-2">
                    <span
                      className={`w-2.5 h-2.5 rounded-full ${
                        modalSetup === 'buy'
                          ? 'bg-emerald-400 shadow-[0_0_8px_rgba(16,185,129,0.6)]'
                          : 'bg-rose-400 shadow-[0_0_8px_rgba(244,63,94,0.6)]'
                      }`}
                    />
                    <span
                      className={`text-xs font-mono font-bold tracking-wide ${
                        modalSetup === 'buy' ? 'text-emerald-400' : 'text-rose-400'
                      }`}
                    >
                      {SETUP_MODAL_DATA[modalSetup].entryBadge}
                    </span>
                  </div>
                  <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded bg-slate-900 text-slate-300 border border-white/10">
                    METATRADER 5
                  </span>
                </div>

                <div
                  className="w-full relative flex items-center justify-center bg-slate-900/40 rounded-xl p-2 sm:p-3 border border-white/5 h-[340px] sm:h-[420px] md:h-[480px] overflow-hidden group cursor-pointer"
                  onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    setZoomedImage({
                      url: SETUP_MODAL_DATA[modalSetup].entryImage,
                      title: `${SETUP_MODAL_DATA[modalSetup].title} • ${SETUP_MODAL_DATA[modalSetup].entryBadge}`,
                      caption: SETUP_MODAL_DATA[modalSetup].entryCaption,
                    });
                  }}
                  title="Klik untuk besarkan paparan penuh"
                >
                  <img
                    src={SETUP_MODAL_DATA[modalSetup].entryImage}
                    alt={`${SETUP_MODAL_DATA[modalSetup].title} MT5 Entry`}
                    referrerPolicy="no-referrer"
                    className="w-auto h-full max-h-full max-w-full object-contain cursor-zoom-in rounded-lg shadow-md transition-transform duration-300 hover:scale-[1.02] select-none"
                  />
                  <span className="bg-black/70 text-slate-200 text-[10px] px-2.5 py-1 rounded-lg backdrop-blur-sm pointer-events-none absolute bottom-3 right-3 border border-white/10 flex items-center space-x-1 shadow-md font-mono">
                    <span>🔍 Zoom Paparan HD</span>
                  </span>
                </div>

                <div className="mt-3 sm:mt-4 p-3.5 rounded-xl bg-[#080d19] border border-white/5 text-xs text-slate-300 font-mono leading-relaxed">
                  {SETUP_MODAL_DATA[modalSetup].entryCaption}
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="flex items-center justify-between px-6 py-4 bg-[#0a1020] border-t border-white/10 flex-shrink-0">
              <span className="text-[11px] font-mono text-slate-400">
                Tekan <kbd className="px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-300 text-[10px]">ESC</kbd> atau klik di luar untuk tutup
              </span>
              <button
                type="button"
                onClick={() => setModalSetup(null)}
                className="px-5 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 hover:text-white text-xs font-mono font-bold transition-all cursor-pointer border border-white/10"
              >
                Tutup
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Fullscreen Lightbox Zoom Modal */}
      {zoomedImage && (
        <div
          id="lightbox-zoom-modal-backdrop"
          className="fixed inset-0 z-[100] bg-black/95 backdrop-blur-2xl flex flex-col items-center justify-center p-3 sm:p-6 select-none animate-in fade-in duration-200"
          onClick={() => setZoomedImage(null)}
        >
          <div className="absolute top-5 right-5 z-20 flex items-center space-x-2">
            <button
              id="btn-close-zoom-modal"
              type="button"
              onClick={() => setZoomedImage(null)}
              className="flex items-center space-x-2 px-4 py-2 rounded-xl bg-slate-900/90 hover:bg-slate-800 text-slate-200 hover:text-white border border-white/20 shadow-2xl transition-all cursor-pointer group"
              aria-label="Tutup Paparan Zum"
            >
              <span className="text-xs font-mono font-bold tracking-wider text-[#D4AF37]">Tutup [ESC]</span>
              <X className="w-5 h-5 group-hover:rotate-90 transition-transform duration-200 text-rose-400" />
            </button>
          </div>

          {zoomedImage.title && (
            <div className="absolute top-5 left-5 z-20 hidden sm:flex items-center space-x-2 px-4 py-2 rounded-xl bg-slate-900/80 border border-white/10 text-xs font-mono text-slate-300 pointer-events-none shadow-xl">
              <span className="w-2 h-2 rounded-full bg-[#D4AF37] animate-pulse" />
              <span className="font-bold text-white tracking-wide">{zoomedImage.title}</span>
            </div>
          )}

          <div
            className="relative flex items-center justify-center max-w-full max-h-full my-auto p-2"
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
            }}
          >
            <img
              src={zoomedImage.url}
              alt={zoomedImage.title}
              referrerPolicy="no-referrer"
              className="max-w-[95vw] max-h-[88vh] object-contain rounded-2xl shadow-[0_0_60px_rgba(0,0,0,0.9)] border border-white/15 select-none cursor-default"
            />
          </div>

          {zoomedImage.caption && (
            <div className="absolute bottom-5 left-1/2 -translate-x-1/2 z-20 max-w-2xl px-5 py-3 rounded-2xl bg-slate-950/90 border border-white/10 backdrop-blur-md pointer-events-none text-center shadow-2xl">
              <p className="text-xs font-mono text-slate-300 leading-relaxed">
                {zoomedImage.caption}
              </p>
            </div>
          )}
        </div>
      )}
    </section>
  );
};
