// Generated by IqwanEngine
import React, { useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import { RoadtourStateData } from '../types';
import {
  MapPin,
  Calendar,
  Users,
  ZoomIn,
  Clock,
  ArrowRight,
  Compass,
  Edit3,
  Trash2,
  Plus,
  X,
  Save,
  CheckCircle2,
  LogOut,
  Lock,
  Activity,
  Sparkles
} from 'lucide-react';
import { ShimmerImage } from './ShimmerImage';

interface RoadtourSectionProps {
  statesData: RoadtourStateData[];
  onOpenLightbox: (images: { url: string; caption?: string; title?: string }[], index: number) => void;
  isAdmin?: boolean;
  onUpdateStatesData?: (newStates: RoadtourStateData[]) => void;
  onOpenAdminLogin?: () => void;
  onAdminSignOut?: () => void;
}

interface MovingChartButtonProps {
  id?: string;
  onClick?: () => void;
  href?: string;
  label: string;
  icon?: React.ReactNode;
  variant?: 'gold' | 'cyan' | 'slate';
  className?: string;
}

/**
 * Visual Vector Renderer for 14 Malaysian State Flags
 */
const StateFlagGraphic: React.FC<{ code: string; className?: string }> = ({ code, className = '' }) => {
  const normalizedCode = code?.toUpperCase() || 'MY';

  switch (normalizedCode) {
    case 'KEL': // Kelantan: Red background with white crescent, star, spears and daggers
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect width="120" height="80" fill="#D32F2F" />
          <circle cx="60" cy="40" r="16" fill="#FFFFFF" />
          <circle cx="65" cy="40" r="14" fill="#D32F2F" />
          <polygon points="68,40 73,42 78,40 75,45 77,50 72,47 67,50 69,45" fill="#FFFFFF" />
        </svg>
      );
    case 'TRG': // Terengganu: Black with white border and white crescent & star
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect width="120" height="80" fill="#FFFFFF" />
          <rect x="10" y="10" width="100" height="60" fill="#111827" />
          <circle cx="55" cy="40" r="14" fill="#FFFFFF" />
          <circle cx="60" cy="40" r="12" fill="#111827" />
          <polygon points="68,40 72,41 75,39 74,43 77,46 72,45 69,48 70,44" fill="#FFFFFF" />
        </svg>
      );
    case 'PHG': // Pahang: White top half, Black bottom half
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect x="0" y="0" width="120" height="40" fill="#FFFFFF" />
          <rect x="0" y="40" width="120" height="40" fill="#111827" />
        </svg>
      );
    case 'JHR': // Johor: Navy Blue with red canton and white crescent & star
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect width="120" height="80" fill="#0B1E48" />
          <rect width="60" height="40" fill="#C62828" />
          <circle cx="28" cy="20" r="11" fill="#FFFFFF" />
          <circle cx="32" cy="20" r="9.5" fill="#C62828" />
          <polygon points="38,20 41,21 44,19 42,23 45,26 40,24 37,27 38,23" fill="#FFFFFF" />
        </svg>
      );
    case 'MLK': // Melaka: Blue/Red horizontal, yellow crescent & star on white canton
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect x="0" y="0" width="120" height="40" fill="#1D4ED8" />
          <rect x="0" y="40" width="120" height="40" fill="#DC2626" />
          <rect width="60" height="40" fill="#FFFFFF" />
          <circle cx="28" cy="20" r="10" fill="#FACC15" />
          <circle cx="32" cy="20" r="8.5" fill="#FFFFFF" />
          <polygon points="38,20 40,21 43,19 41,23 43,26 39,24 36,26 37,22" fill="#FACC15" />
        </svg>
      );
    case 'NSN': // Negeri Sembilan: Yellow field with red/black diagonal canton
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect width="120" height="80" fill="#EAB308" />
          <polygon points="0,0 60,0 60,40" fill="#DC2626" />
          <polygon points="0,0 60,40 0,40" fill="#111827" />
        </svg>
      );
    case 'SGR': // Selangor: 4 alternating red & yellow quarters with crescent and star
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect x="0" y="0" width="60" height="40" fill="#DC2626" />
          <rect x="60" y="0" width="60" height="40" fill="#FACC15" />
          <rect x="0" y="40" width="60" height="40" fill="#FACC15" />
          <rect x="60" y="40" width="60" height="40" fill="#DC2626" />
          <circle cx="28" cy="20" r="10" fill="#FFFFFF" />
          <circle cx="32" cy="20" r="8.5" fill="#DC2626" />
          <polygon points="38,20 41,21 43,19 42,23 45,25 40,24 38,27 38,22" fill="#FFFFFF" />
        </svg>
      );
    case 'PRK': // Perak: White top, Yellow middle, Black bottom
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect x="0" y="0" width="120" height="26.6" fill="#FFFFFF" />
          <rect x="0" y="26.6" width="120" height="26.6" fill="#EAB308" />
          <rect x="0" y="53.2" width="120" height="26.8" fill="#111827" />
        </svg>
      );
    case 'KDH': // Kedah: Red background with yellow crest in canton
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect width="120" height="80" fill="#B91C1C" />
          <circle cx="35" cy="30" r="16" fill="none" stroke="#EAB308" strokeWidth="3" />
          <circle cx="35" cy="30" r="10" fill="#15803D" />
          <path d="M 28 35 Q 35 20, 42 35" fill="none" stroke="#EAB308" strokeWidth="3" />
        </svg>
      );
    case 'PNG': // Pulau Pinang: Blue/White/Yellow vertical tricolour with betel nut tree
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect x="0" y="0" width="40" height="80" fill="#2563EB" />
          <rect x="40" y="0" width="40" height="80" fill="#FFFFFF" />
          <rect x="80" y="0" width="40" height="80" fill="#EAB308" />
          <circle cx="60" cy="40" r="10" fill="#15803D" opacity="0.8" />
        </svg>
      );
    case 'PLS': // Perlis: Yellow top half, Blue bottom half
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect x="0" y="0" width="120" height="40" fill="#EAB308" />
          <rect x="0" y="40" width="120" height="40" fill="#1D4ED8" />
        </svg>
      );
    case 'SBH': // Sabah: Blue/White/Red tricolour with Kinabalu mountain on canton
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect x="0" y="0" width="120" height="26.6" fill="#38BDF8" />
          <rect x="0" y="26.6" width="120" height="26.6" fill="#FFFFFF" />
          <rect x="0" y="53.2" width="120" height="26.8" fill="#B91C1C" />
          <rect x="0" y="0" width="60" height="40" fill="#0284C7" />
          <polygon points="10,36 28,14 42,26 55,36" fill="#0369A1" />
        </svg>
      );
    case 'SWK': // Sarawak: Yellow with red/black cross lines and 9-pointed star
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect width="120" height="80" fill="#FACC15" />
          <polygon points="0,0 120,80 120,60 0,0" fill="#DC2626" />
          <polygon points="0,20 120,80 120,80 0,40" fill="#111827" />
          <circle cx="60" cy="40" r="8" fill="#FACC15" />
        </svg>
      );
    case 'WPKL': // Kuala Lumpur / Putrajaya / Labuan: Blue/Red stripes with yellow star & crescent
    case 'KUL':
    default:
      return (
        <svg viewBox="0 0 120 80" className={`w-full h-full object-cover ${className}`} preserveAspectRatio="none">
          <rect x="0" y="0" width="120" height="18" fill="#1E3A8A" />
          <rect x="0" y="18" width="120" height="12" fill="#FFFFFF" />
          <rect x="0" y="30" width="120" height="20" fill="#DC2626" />
          <rect x="0" y="50" width="120" height="12" fill="#FFFFFF" />
          <rect x="0" y="62" width="120" height="18" fill="#1E3A8A" />
          <circle cx="60" cy="40" r="10" fill="#FACC15" />
          <circle cx="63" cy="40" r="8.5" fill="#DC2626" />
          <polygon points="69,40 71,41 74,39 72,43 75,46 70,44 68,47 69,42" fill="#FACC15" />
        </svg>
      );
  }
};

/**
 * Reusable Overpower Institutional Button with Embedded Moving Candlestick/Wave Chart
 * (Strictly Static Non-Rotating Vector Icons)
 */
function MovingChartButton({
  id,
  onClick,
  href,
  label,
  icon,
  variant = 'gold',
  className = ''
}: MovingChartButtonProps) {
  const isGold = variant === 'gold';
  const isCyan = variant === 'cyan';

  const baseBorder = isGold
    ? 'border-amber-400/40 hover:border-[#D4AF37]'
    : isCyan
    ? 'border-cyan-400/40 hover:border-cyan-300'
    : 'border-white/10 hover:border-[#D4AF37]/50';

  const strokeColor = isGold ? '#F59E0B' : isCyan ? '#06B6D4' : '#D4AF37';

  const content = (
    <div
      id={id}
      className={`group relative overflow-hidden rounded-2xl bg-slate-950/90 border ${baseBorder} px-5 py-3 flex items-center justify-between gap-3 shadow-[0_10px_25px_rgba(0,0,0,0.6)] transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] select-none cursor-pointer ${className}`}
      onClick={onClick}
    >
      {/* Dynamic Candlestick Bars Wave in Background */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-60 transition-opacity">
        <div className="absolute inset-0 flex items-end justify-between px-2 pb-1 gap-1">
          {[40, 70, 45, 85, 50, 95, 35, 75, 60, 90, 50, 80].map((h, i) => (
            <motion.div
              key={i}
              className="w-[2px] rounded-t-sm"
              style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
              animate={{
                height: [
                  `${Math.max(15, h * 0.3)}%`,
                  `${Math.min(95, h * 0.95)}%`,
                  `${Math.max(20, h * 0.4)}%`
                ]
              }}
              transition={{
                repeat: Infinity,
                duration: 1.6 + (i % 4) * 0.25,
                ease: 'easeInOut',
                repeatType: 'reverse',
                delay: i * 0.05
              }}
            />
          ))}
        </div>

        {/* Dynamic Continuous Moving Market Line Wave */}
        <svg
          className="absolute inset-0 w-[200%] h-full stroke-current"
          style={{ color: strokeColor }}
          viewBox="0 0 500 50"
          preserveAspectRatio="none"
        >
          <motion.path
            d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
            fill="none"
            strokeWidth="1.6"
            strokeLinecap="round"
            strokeDasharray="4 2"
            animate={{ x: [0, -250] }}
            transition={{
              repeat: Infinity,
              duration: 4.2,
              ease: 'linear'
            }}
          />
        </svg>

        <div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/60 to-slate-950/80" />
      </div>

      {/* Button Content with Static Icon */}
      <div className="relative z-10 flex items-center space-x-2.5">
        {icon && (
          <div className="text-[#D4AF37]">
            {icon}
          </div>
        )}
        <span className="font-mono text-xs font-bold uppercase tracking-wider text-slate-200 group-hover:text-white transition-colors">
          {label}
        </span>
      </div>

      <div className="relative z-10 text-[#D4AF37] group-hover:translate-x-1 transition-transform">
        <ArrowRight className="w-3.5 h-3.5" />
      </div>

      {/* Specular Glare Shimmer Ray */}
      <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/20 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />
    </div>
  );

  if (href) {
    return (
      <a href={href} target="_blank" rel="noopener noreferrer" className="inline-block w-full sm:w-auto">
        {content}
      </a>
    );
  }

  return content;
}

export const RoadtourSection: React.FC<RoadtourSectionProps> = ({
  statesData,
  onOpenLightbox,
  isAdmin = false,
  onUpdateStatesData,
  onOpenAdminLogin,
  onAdminSignOut,
}) => {
  const [selectedStateId, setSelectedStateId] = useState<string>(() => {
    return statesData && statesData.length > 0 ? statesData[0].id : 'kuala-lumpur';
  });
  const [selectedZone, setSelectedZone] = useState<string>('Semua');

  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editHotel, setEditHotel] = useState('');
  const [editDate, setEditDate] = useState('');
  const [editAttendees, setEditAttendees] = useState('');
  const [editStatus, setEditStatus] = useState<'completed' | 'upcoming' | 'coming_soon'>('upcoming');
  const [editHighlight, setEditHighlight] = useState('');

  const [isAddImageModalOpen, setIsAddImageModalOpen] = useState(false);
  const [newImageUrl, setNewImageUrl] = useState('');
  const [newImageCaption, setNewImageCaption] = useState('');

  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  const currentState = useMemo(() => {
    if (!statesData || statesData.length === 0) return undefined;
    return (
      statesData.find(
        (s) =>
          s.id.toLowerCase() === selectedStateId.toLowerCase() ||
          s.name.toLowerCase() === selectedStateId.toLowerCase() ||
          s.code.toLowerCase() === selectedStateId.toLowerCase()
      ) || statesData[0]
    );
  }, [statesData, selectedStateId]);

  const zones = ['Semua', 'Pantai Timur', 'Selatan', 'Utara', 'Tengah', 'Borneo'];

  const filteredStates = selectedZone === 'Semua'
    ? statesData
    : statesData.filter((s) => s.zone === selectedZone);

  const handleImageClick = (index: number) => {
    if (!currentState?.gallery || currentState.gallery.length === 0) return;
    const formatted = currentState.gallery.map((g) => ({
      url: g.url,
      caption: `[Jelajah ${currentState.name}] ${g.caption}`,
      title: `${currentState.name} Roadtour Album`
    }));
    onOpenLightbox(formatted, index);
  };

  const handleOpenEditModal = () => {
    if (!currentState) return;
    setEditHotel(currentState.hotel || '');
    setEditDate(currentState.date || '');
    setEditAttendees(String(currentState.attendees || ''));
    setEditStatus(currentState.status || 'upcoming');
    setEditHighlight(currentState.highlight || '');
    setIsEditModalOpen(true);
  };

  const handleSaveStateInfo = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editHotel.trim()) {
      showToast('Sila masukkan nama dewan atau hotel.');
      return;
    }

    if (!onUpdateStatesData || !currentState) return;

    const targetId = currentState.id.toLowerCase();
    const targetName = currentState.name.toLowerCase();

    const updated = statesData.map((st) => {
      if (st.id.toLowerCase() === targetId || st.name.toLowerCase() === targetName) {
        return {
          ...st,
          hotel: editHotel.trim(),
          date: editDate.trim() || st.date,
          attendees: editAttendees.trim() || st.attendees,
          status: editStatus,
          highlight: editHighlight.trim() || st.highlight
        };
      }
      return st;
    });

    onUpdateStatesData(updated);
    setIsEditModalOpen(false);
    showToast(`Maklumat acara Roadtour ${currentState.name} berjaya dikemaskini!`);
  };

  const handleDeleteImage = (index: number) => {
    if (!currentState || !onUpdateStatesData) return;

    const currentGallery = currentState.gallery || [];
    if (index < 0 || index >= currentGallery.length) return;

    const targetId = currentState.id.toLowerCase();
    const targetName = currentState.name.toLowerCase();

    const updatedGallery = currentGallery.filter((_, i) => i !== index);

    const updatedStates = statesData.map((st) => {
      if (st.id.toLowerCase() === targetId || st.name.toLowerCase() === targetName) {
        return {
          ...st,
          gallery: updatedGallery
        };
      }
      return st;
    });

    onUpdateStatesData(updatedStates);
    showToast(`Gambar berjaya dipadam daripada album ${currentState.name}.`);
  };

  const handleSaveNewImage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newImageUrl.trim()) {
      showToast('Sila masukkan pautan URL imej yang sah.');
      return;
    }

    if (!onUpdateStatesData || !currentState) return;

    const newPhoto = {
      url: newImageUrl.trim(),
      caption: newImageCaption.trim() || `Dokumentasi Rasmi Jelajah ${currentState.name}`
    };

    const targetId = currentState.id.toLowerCase();
    const targetName = currentState.name.toLowerCase();

    const updatedStates = statesData.map((st) => {
      if (st.id.toLowerCase() === targetId || st.name.toLowerCase() === targetName) {
        return {
          ...st,
          gallery: [...(st.gallery || []), newPhoto]
        };
      }
      return st;
    });

    onUpdateStatesData(updatedStates);
    setNewImageUrl('');
    setNewImageCaption('');
    setIsAddImageModalOpen(false);
    showToast(`Gambar baharu berjaya dimuat naik ke album ${currentState.name}!`);
  };

  return (
    <section id="roadtour" className="py-24 relative bg-[#060911] border-t border-white/5 overflow-hidden selection:bg-[#D4AF37] selection:text-black">
      {/* Institutional Ambient Glow Elements */}
      <div className="absolute top-1/4 -left-20 w-96 h-96 bg-amber-500/5 rounded-full blur-[140px] pointer-events-none -z-10" />
      <div className="absolute bottom-1/4 -right-20 w-96 h-96 bg-cyan-500/5 rounded-full blur-[140px] pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Floating In-Section Toast */}
        {toastMessage && (
          <div className="fixed top-20 right-6 z-50 p-4 rounded-2xl bg-slate-950/95 border border-[#D4AF37]/50 shadow-2xl backdrop-blur-xl flex items-center space-x-3 text-xs font-mono text-[#D4AF37] animate-in fade-in slide-in-from-top-4">
            <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
            <span className="text-slate-100 font-medium">{toastMessage}</span>
          </div>
        )}

        {/* Admin Bar Indicator */}
        {isAdmin && (
          <div className="mb-8 p-4 rounded-2xl bg-gradient-to-r from-amber-500/15 via-[#D4AF37]/10 to-slate-900 border border-[#D4AF37]/40 flex flex-wrap items-center justify-between gap-3 shadow-lg backdrop-blur-xl">
            <div className="flex items-center space-x-3">
              <span className="flex h-2.5 w-2.5 relative">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-500 shadow-[0_0_8px_#10b981]"></span>
              </span>
              <span className="text-xs font-mono font-bold text-[#D4AF37] tracking-wider uppercase">
                Mod Pentadbir Aktif • Roadtour Dynamic CMS
              </span>
            </div>

            <div className="flex items-center space-x-2">
              {onOpenAdminLogin && (
                <button
                  type="button"
                  onClick={onOpenAdminLogin}
                  className="px-3 py-1.5 rounded-xl bg-slate-900/90 hover:bg-slate-800 text-slate-300 border border-white/10 text-xs font-mono transition-colors cursor-pointer"
                >
                  Buka Portal Penuh CMS
                </button>
              )}
              {onAdminSignOut && (
                <button
                  type="button"
                  onClick={onAdminSignOut}
                  className="px-3 py-1.5 rounded-xl bg-rose-950/80 hover:bg-rose-900 text-rose-300 border border-rose-500/40 text-xs font-mono font-bold flex items-center space-x-1.5 transition-colors cursor-pointer"
                >
                  <LogOut className="w-3.5 h-3.5" />
                  <span>Log Keluar</span>
                </button>
              )}
            </div>
          </div>
        )}

        {/* Section Header with Strictly Static Compass Icon */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-12">
          <div>
            <div className="inline-flex items-center space-x-2.5 px-3.5 py-1.5 rounded-full bg-[#D4AF37]/10 border border-[#D4AF37]/30 text-[#D4AF37] text-xs font-mono mb-4 shadow-[0_0_15px_rgba(212,175,55,0.15)]">
              <Compass className="w-4 h-4 text-[#D4AF37]" />
              <span className="font-bold tracking-wider">NATIONWIDE PHYSICAL EXPEDITION</span>
            </div>

            <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight uppercase">
              Roadtour Jelajah <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-amber-400 to-[#D4AF37] drop-shadow-[0_0_20px_rgba(212,175,55,0.3)]">Komuniti OWLFX</span>
            </h2>
            <p className="mt-3 text-slate-400 text-sm sm:text-base max-w-2xl font-medium">
              Meliputi 14 negeri di seluruh Malaysia. Membawa pendidikan dagangan bertaraf institusi,
              bedah carta secara langsung, dan agihan faedah komuniti terus ke dewan seminar di negeri anda.
            </p>
          </div>

          {/* Zone Filter Pill Bar */}
          <div className="mt-6 md:mt-0 flex items-center flex-wrap gap-1.5 p-1.5 rounded-2xl bg-slate-900/80 border border-white/10 font-mono text-xs backdrop-blur-xl">
            {zones.map((zone) => (
              <button
                key={zone}
                type="button"
                onClick={() => setSelectedZone(zone)}
                className={`px-3.5 py-1.5 rounded-xl transition-all font-semibold cursor-pointer ${
                  selectedZone === zone
                    ? 'bg-[#D4AF37] text-slate-950 shadow-[0_0_15px_rgba(212,175,55,0.4)]'
                    : 'text-slate-400 hover:text-white hover:bg-white/5'
                }`}
              >
                {zone}
              </button>
            ))}
          </div>
        </div>

        {/* 14-State Selector Grid with Embedded Billowing State Flag Backgrounds */}
        <div className="mb-12">
          <div className="text-xs font-mono text-slate-400 mb-3 flex items-center justify-between">
            <span className="tracking-wider">PILIH NEGERI ROADTOUR UNTUK MEMBUKA ALBUM KHAS:</span>
            <div className="flex items-center space-x-3">
              <span className="text-[#D4AF37] font-bold">{filteredStates.length} Negeri Tersedia</span>
              {!isAdmin && onOpenAdminLogin && (
                <button
                  type="button"
                  onClick={onOpenAdminLogin}
                  className="text-[11px] text-slate-500 hover:text-[#D4AF37] font-mono flex items-center space-x-1 transition-colors cursor-pointer"
                  title="Akses Pentadbir Roadtour"
                >
                  <Lock className="w-3 h-3" />
                  <span>Admin Access</span>
                </button>
              )}
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-7 gap-3">
            {filteredStates.map((st) => {
              const isSelected = st.id === selectedStateId;
              return (
                <button
                  key={st.id}
                  id={`roadtour-state-btn-${st.id}`}
                  type="button"
                  onClick={() => setSelectedStateId(st.id)}
                  className={`group roadtour-state-card relative p-3.5 rounded-2xl text-left transition-all duration-300 border overflow-hidden cursor-pointer select-none min-h-[90px] flex flex-col justify-between ${
                    isSelected
                      ? 'bg-slate-950/90 border-[#D4AF37] shadow-[0_0_25px_rgba(212,175,55,0.35)] scale-[1.02]'
                      : 'bg-[#080d1a]/85 border-white/10 hover:border-[#D4AF37]/50'
                  }`}
                >
                  {/* Billowing State Flag Background Animation */}
                  <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-25 group-hover:opacity-45 transition-opacity duration-500">
                    <motion.div
                      className="w-[125%] h-[125%] -left-[10%] -top-[10%] relative"
                      animate={{
                        x: [0, 4, 0, -4, 0],
                        skewY: [0, 1.2, 0, -1.2, 0],
                        scaleY: [1, 1.03, 0.98, 1]
                      }}
                      transition={{
                        repeat: Infinity,
                        duration: 5 + (st.name.length % 3),
                        ease: 'easeInOut'
                      }}
                    >
                      <StateFlagGraphic code={st.code} />

                      {/* Realistic Cloth Ripple Lighting Overlay */}
                      <div className="absolute inset-0 bg-gradient-to-r from-black/40 via-white/15 to-black/60 mix-blend-overlay" />
                    </motion.div>
                  </div>

                  {/* Dark Radial Mask to Guarantee 100% Typography Readability */}
                  <div className="absolute inset-0 bg-gradient-to-t from-[#060911]/95 via-[#060911]/80 to-[#060911]/60 pointer-events-none" />

                  {/* Top Laser Line Indicator */}
                  {isSelected && (
                    <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-amber-300 via-[#D4AF37] to-amber-500 shadow-[0_0_8px_#D4AF37]" />
                  )}

                  {/* Card Header Content */}
                  <div className="relative z-10 flex items-center justify-between mb-1.5">
                    <span
                      className={`text-xs font-mono font-bold px-1.5 py-0.5 rounded-md transition-colors ${
                        isSelected
                          ? 'bg-[#D4AF37]/25 text-[#D4AF37] border border-[#D4AF37]/40'
                          : 'bg-slate-900/80 text-slate-300 border border-white/5 group-hover:text-[#D4AF37]'
                      }`}
                    >
                      {st.code}
                    </span>
                    <span
                      className={`h-2 w-2 rounded-full ${
                        st.status === 'completed'
                          ? 'bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.8)]'
                          : st.status === 'upcoming'
                          ? 'bg-[#D4AF37] shadow-[0_0_8px_rgba(212,175,55,0.9)]'
                          : 'bg-slate-600'
                      }`}
                      title={st.status}
                    />
                  </div>

                  {/* State Name & Zone Tag */}
                  <div className="relative z-10">
                    <div className="font-bold text-sm text-white truncate group-hover:text-amber-300 transition-colors">
                      {st.name}
                    </div>
                    <div className="text-[10px] text-slate-400 font-mono truncate">
                      {st.zone}
                    </div>
                  </div>
                </button>
              );
            })}
          </div>
        </div>

        {/* Selected State Special Album Display */}
        {currentState && (
          <div
            id={`roadtour-album-${currentState.id}`}
            key={currentState.id}
            className="rounded-3xl bg-[#080c17]/95 backdrop-blur-2xl border border-white/10 p-6 sm:p-10 shadow-[0_20px_50px_rgba(0,0,0,0.8)] relative overflow-hidden"
          >
            {/* Top Atmospheric Flag Horizon Background */}
            <div className="absolute top-0 right-0 w-96 h-96 opacity-15 pointer-events-none overflow-hidden blur-[1px]">
              <motion.div
                className="w-[130%] h-[130%] relative -right-10 -top-10"
                animate={{
                  x: [0, 6, 0, -6, 0],
                  skewY: [0, 2, 0, -2, 0]
                }}
                transition={{
                  repeat: Infinity,
                  duration: 7,
                  ease: 'easeInOut'
                }}
              >
                <StateFlagGraphic code={currentState.code} />
                <div className="absolute inset-0 bg-gradient-to-l from-transparent via-[#080c17]/80 to-[#080c17]" />
              </motion.div>
            </div>

            <div className="absolute -top-20 -right-20 w-80 h-80 bg-[#D4AF37]/10 rounded-full blur-[120px] pointer-events-none" />

            {/* State Info Card Header */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start pb-8 border-b border-white/10 mb-8 relative z-10">
              <div className="lg:col-span-7 space-y-4">
                <div className="flex flex-wrap items-center gap-2.5">
                  <span className="px-3 py-1 rounded-full text-xs font-mono font-bold bg-[#D4AF37]/15 text-amber-400 border border-[#D4AF37]/30">
                    JELAJAH NEGERI {currentState.name.toUpperCase()}
                  </span>
                  <span
                    className={`px-3 py-1 rounded-full text-xs font-mono font-bold ${
                      currentState.status === 'completed'
                        ? 'bg-emerald-950/80 text-emerald-400 border border-emerald-500/30'
                        : currentState.status === 'upcoming'
                        ? 'bg-blue-950/80 text-sky-400 border border-sky-500/30'
                        : 'bg-slate-800 text-slate-400 border border-white/10'
                    }`}
                  >
                    {currentState.status === 'completed'
                      ? '✓ SELESAI DILAKSANAKAN'
                      : currentState.status === 'upcoming'
                      ? '⏳ AKAN BERLANGSUNG (PENDAFTARAN DIBUKA)'
                      : 'AKAN DATANG'}
                  </span>
                </div>

                {/* State Hotel & Dynamic Moving Chart Button for Edit */}
                <div className="flex flex-wrap items-center justify-between gap-4">
                  <h3 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
                    {currentState.hotel}
                  </h3>

                  {isAdmin && (
                    <MovingChartButton
                      id={`edit-info-state-btn-${currentState.id}`}
                      onClick={handleOpenEditModal}
                      label="Edit Info Negeri"
                      icon={<Edit3 className="w-3.5 h-3.5" />}
                      variant="gold"
                    />
                  )}
                </div>

                <p className="text-sm text-slate-400 leading-relaxed font-medium">
                  {currentState.highlight}
                </p>

                {/* Event Highlights Metadata (Strictly Static Icons) */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-3">
                  <div className="p-3.5 rounded-2xl bg-slate-900/80 border border-white/5 flex items-center space-x-3">
                    <div className="p-2 rounded-xl bg-amber-500/10 text-[#D4AF37]">
                      <Calendar className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-[10px] text-slate-400 font-mono uppercase">Tarikh Acara</div>
                      <div className="text-xs font-bold text-white font-mono">{currentState.date}</div>
                    </div>
                  </div>

                  <div className="p-3.5 rounded-2xl bg-slate-900/80 border border-white/5 flex items-center space-x-3">
                    <div className="p-2 rounded-xl bg-cyan-500/10 text-cyan-400">
                      <Users className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-[10px] text-slate-400 font-mono uppercase">Kehadiran</div>
                      <div className="text-xs font-bold text-white font-mono">{currentState.attendees}</div>
                    </div>
                  </div>

                  <div className="p-3.5 rounded-2xl bg-slate-900/80 border border-white/5 flex items-center space-x-3">
                    <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-400">
                      <MapPin className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-[10px] text-slate-400 font-mono uppercase">Lokasi Dewan</div>
                      <div className="text-xs font-bold text-white font-mono truncate">{currentState.name}</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* State Cover Box */}
              <div className="lg:col-span-5">
                <div
                  className="relative h-60 sm:h-64 rounded-3xl overflow-hidden border border-white/10 shadow-2xl group cursor-pointer"
                  onClick={() => handleImageClick(0)}
                >
                  <ShimmerImage
                    src={currentState.coverImage}
                    alt={currentState.name}
                    priority={true}
                    loading="eager"
                    fallbackSrc="https://i.imgur.com/aCQ6hLX.jpg"
                    containerClassName="relative w-full h-full"
                    imageClassName="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                    badgeLabel={`JELAJAH ${currentState.name.toUpperCase()}`}
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/20 to-transparent pointer-events-none" />
                  <div className="absolute bottom-4 left-4 right-4 flex items-center justify-between z-20 pointer-events-none">
                    <div>
                      <span className="text-[10px] font-mono text-amber-400 uppercase tracking-widest block font-bold">DOKUMENTASI RASMI</span>
                      <span className="text-sm font-bold text-white font-mono">{currentState.hotel}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Gallery Grid */}
            <div className="relative z-10">
              <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
                <div className="flex items-center space-x-2">
                  <h4 className="text-base font-bold text-white tracking-wide">
                    Album Liputan & Foto Acara ({currentState.name})
                  </h4>
                  <span className="text-xs font-mono text-[#D4AF37]">
                    • {currentState.gallery?.length || 0} Foto
                  </span>
                </div>

                <div className="flex items-center space-x-3">
                  {isAdmin && (
                    <MovingChartButton
                      onClick={() => setIsAddImageModalOpen(true)}
                      label="Tambah Gambar"
                      icon={<Plus className="w-3.5 h-3.5 text-[#D4AF37]" />}
                      variant="gold"
                    />
                  )}
                  <span className="text-xs text-slate-400 font-mono hidden sm:inline">
                    Klik gambar untuk zum skrin penuh (Lightbox HD)
                  </span>
                </div>
              </div>

              {currentState.gallery && currentState.gallery.length > 0 ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
                  {currentState.gallery.map((img, idx) => (
                    <div
                      key={`${currentState.id}-${idx}-${img.url}`}
                      id={`gallery-item-${currentState.id}-${idx}`}
                      onClick={() => handleImageClick(idx)}
                      className="group relative h-52 rounded-2xl overflow-hidden bg-slate-900 border border-white/10 hover:border-[#D4AF37] transition-all cursor-pointer shadow-lg"
                    >
                      <ShimmerImage
                        src={img.url}
                        alt={img.caption || `Foto ${currentState.name}`}
                        loading="lazy"
                        fallbackSrc="https://drive.google.com/file/d/1tm2SG-Y3tJya5AjgYDkOipVLD3VyxZRX/view?usp=drive_link"
                        containerClassName="relative w-full h-full"
                        imageClassName="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
                        badgeLabel={`OWLFX ${currentState.code}`}
                      />

                      {isAdmin && (
                        <button
                          type="button"
                          id={`delete-img-btn-${currentState.id}-${idx}`}
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDeleteImage(idx);
                          }}
                          className="absolute top-2 right-2 z-30 p-2 rounded-xl bg-rose-950/90 text-rose-400 hover:bg-rose-900 hover:text-white border border-rose-500/50 shadow-lg transition-all active:scale-90 cursor-pointer"
                          title="Padam Gambar Ini"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      )}

                      <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-transparent to-transparent opacity-80 group-hover:opacity-95 transition-opacity pointer-events-none" />

                      <div className="absolute bottom-3 left-3 right-3 z-20 pointer-events-none">
                        <p className="text-xs text-slate-200 line-clamp-2 font-medium">
                          {img.caption}
                        </p>
                      </div>

                      <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-black/40 z-20">
                        <div className="p-3 rounded-full bg-[#D4AF37] text-slate-950 shadow-xl">
                          <ZoomIn className="w-5 h-5" />
                        </div>
                      </div>
                    </div>
                  ))}

                  {/* Add New Image Card Button */}
                  {isAdmin && (
                    <button
                      type="button"
                      id={`add-gallery-img-card-${currentState.id}`}
                      onClick={() => setIsAddImageModalOpen(true)}
                      className="group relative h-52 rounded-2xl border-2 border-dashed border-[#D4AF37]/40 hover:border-[#D4AF37] bg-slate-900/40 hover:bg-[#D4AF37]/10 flex flex-col items-center justify-center text-center p-4 transition-all duration-300 cursor-pointer shadow-md"
                    >
                      <div className="w-12 h-12 rounded-2xl bg-[#D4AF37]/20 border border-[#D4AF37]/40 flex items-center justify-center text-[#D4AF37] mb-2">
                        <Plus className="w-5 h-5" />
                      </div>
                      <span className="text-xs font-bold text-white font-mono">
                        Tambah Gambar Baharu
                      </span>
                      <span className="text-[10px] text-slate-400 font-mono mt-1">
                        + Pautan CDN ke {currentState.name}
                      </span>
                    </button>
                  )}
                </div>
              ) : (
                /* Empty Placeholder with Moving Chart CTA */
                <div className="p-10 rounded-3xl bg-slate-900/40 border border-white/5 border-dashed text-center flex flex-col items-center justify-center">
                  <div className="p-3 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-[#D4AF37] mb-4">
                    <Clock className="w-8 h-8" />
                  </div>

                  <h4 className="text-lg font-bold text-white mb-1">
                    Album Liputan {currentState.name} Sedang Disiapkan
                  </h4>
                  <p className="text-xs sm:text-sm text-slate-400 max-w-md mb-6 font-medium">
                    Siri jelajah bagi negeri {currentState.name} dijadualkan pada {currentState.date}.
                    Pendaftaran kerusi VIP sedang dibuka sekarang sebelum kuota dewan penuh.
                  </p>

                  <div className="flex flex-wrap items-center justify-center gap-4">
                    <MovingChartButton
                      id="roadtour-reserve-btn"
                      href="/my/register"
                      label="Tempah Kerusi VIP Negeri Ini"
                      icon={<Sparkles className="w-4 h-4" />}
                      variant="gold"
                      className="px-6 py-3"
                    />

                    {isAdmin && (
                      <MovingChartButton
                        onClick={() => setIsAddImageModalOpen(true)}
                        label="Muat Naik Foto Pertama"
                        icon={<Plus className="w-4 h-4" />}
                        variant="slate"
                        className="px-6 py-3"
                      />
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Modal 1: Edit State Info */}
        {isEditModalOpen && currentState && (
          <div
            id="edit-roadtour-modal-backdrop"
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-md p-4 sm:p-6 overflow-y-auto animate-in fade-in duration-200 select-none"
            onClick={() => setIsEditModalOpen(false)}
          >
            <div
              id="edit-roadtour-modal"
              className="relative max-w-lg w-full rounded-3xl bg-[#080d19] border border-[#D4AF37]/50 shadow-[0_0_50px_rgba(0,0,0,0.9),0_0_20px_rgba(212,175,55,0.2)] p-6 sm:p-8 overflow-hidden my-8"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between pb-4 border-b border-white/10 mb-5">
                <div className="flex items-center space-x-3">
                  <div className="p-2 rounded-xl bg-[#D4AF37]/15 text-[#D4AF37] border border-[#D4AF37]/40">
                    <Edit3 className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="text-base font-black text-white font-mono">
                      Kemaskini Acara Roadtour
                    </h3>
                    <p className="text-xs text-slate-400 font-mono">
                      Jelajah Komuniti • Negeri {currentState.name}
                    </p>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => setIsEditModalOpen(false)}
                  className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors cursor-pointer"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              <form onSubmit={handleSaveStateInfo} className="space-y-4">
                <div>
                  <label className="block text-xs font-mono text-slate-400 mb-1">
                    Nama Negeri (Readonly):
                  </label>
                  <input
                    type="text"
                    readOnly
                    value={currentState.name}
                    className="w-full bg-slate-950/70 border border-white/10 rounded-xl px-3.5 py-2.5 text-xs text-slate-400 font-mono cursor-not-allowed opacity-80"
                  />
                </div>

                <div>
                  <label className="block text-xs font-mono text-slate-400 mb-1">
                    Lokasi / Nama Dewan / Hotel *:
                  </label>
                  <input
                    type="text"
                    required
                    value={editHotel}
                    onChange={(e) => setEditHotel(e.target.value)}
                    placeholder="cth: Hotel Grand Riverview, Kota Bharu"
                    className="w-full bg-slate-950 border border-white/10 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-600 focus:outline-none focus:border-[#D4AF37] font-mono"
                  />
                </div>

                <div>
                  <label className="block text-xs font-mono text-slate-400 mb-1">
                    Tarikh Acara:
                  </label>
                  <input
                    type="text"
                    required
                    value={editDate}
                    onChange={(e) => setEditDate(e.target.value)}
                    placeholder="cth: 15 Oktober 2026"
                    className="w-full bg-slate-950 border border-white/10 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-600 focus:outline-none focus:border-[#D4AF37] font-mono"
                  />
                </div>

                <div>
                  <label className="block text-xs font-mono text-slate-400 mb-1">
                    Anggaran Kehadiran Peserta:
                  </label>
                  <input
                    type="text"
                    required
                    value={editAttendees}
                    onChange={(e) => setEditAttendees(e.target.value)}
                    placeholder="cth: 350 Peserta"
                    className="w-full bg-slate-950 border border-white/10 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-600 focus:outline-none focus:border-[#D4AF37] font-mono"
                  />
                </div>

                <div>
                  <label className="block text-xs font-mono text-slate-400 mb-1">
                    Status Acara:
                  </label>
                  <select
                    value={editStatus}
                    onChange={(e) => setEditStatus(e.target.value as RoadtourStateData['status'])}
                    className="w-full bg-slate-950 border border-white/10 rounded-xl px-3.5 py-2.5 text-xs text-white font-mono focus:outline-none focus:border-[#D4AF37]"
                  >
                    <option value="coming_soon">Akan Datang</option>
                    <option value="upcoming">Pendaftaran Dibuka</option>
                    <option value="completed">Selesai</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-mono text-slate-400 mb-1">
                    Keterangan Sesi / Sorotan Utama:
                  </label>
                  <textarea
                    rows={2}
                    value={editHighlight}
                    onChange={(e) => setEditHighlight(e.target.value)}
                    placeholder="Keterangan ringkas mengenai sesi..."
                    className="w-full bg-slate-950 border border-white/10 rounded-xl px-3.5 py-2 text-xs text-white placeholder-slate-600 focus:outline-none focus:border-[#D4AF37]"
                  />
                </div>

                <div className="pt-3 flex items-center justify-end space-x-3">
                  <button
                    type="button"
                    onClick={() => setIsEditModalOpen(false)}
                    className="px-4 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-300 font-mono text-xs transition-colors cursor-pointer"
                  >
                    Batal
                  </button>
                  <button
                    type="submit"
                    className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-300 via-[#D4AF37] to-amber-500 text-slate-950 font-extrabold font-mono text-xs shadow-lg hover:brightness-110 active:scale-95 transition-all flex items-center space-x-1.5 cursor-pointer"
                  >
                    <Save className="w-3.5 h-3.5" />
                    <span>Simpan Perubahan</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* Modal 2: Add New Image */}
        {isAddImageModalOpen && currentState && (
          <div
            id="add-image-modal-backdrop"
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-md p-4 sm:p-6 overflow-y-auto animate-in fade-in duration-200 select-none"
            onClick={() => setIsAddImageModalOpen(false)}
          >
            <div
              id="add-image-modal"
              className="relative max-w-md w-full rounded-3xl bg-[#080d19] border border-[#D4AF37]/50 shadow-[0_0_50px_rgba(0,0,0,0.9),0_0_20px_rgba(212,175,55,0.2)] p-6 sm:p-8 overflow-hidden my-8"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between pb-4 border-b border-white/10 mb-5">
                <div className="flex items-center space-x-3">
                  <div className="p-2 rounded-xl bg-[#D4AF37]/15 text-[#D4AF37] border border-[#D4AF37]/40">
                    <Plus className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="text-base font-black text-white font-mono">
                      Tambah Gambar Baharu
                    </h3>
                    <p className="text-xs text-slate-400 font-mono">
                      Album Negeri {currentState.name}
                    </p>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => setIsAddImageModalOpen(false)}
                  className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors cursor-pointer"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              <form onSubmit={handleSaveNewImage} className="space-y-4">
                <div>
                  <label className="block text-xs font-mono text-slate-400 mb-1">
                    Pautan Imej (URL Langsung Imgur / CDN / Foto) *:
                  </label>
                  <input
                    type="url"
                    required
                    value={newImageUrl}
                    onChange={(e) => setNewImageUrl(e.target.value)}
                    placeholder="https://i.imgur.com/... atau URL foto HD"
                    className="w-full bg-slate-950 border border-white/10 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-600 focus:outline-none focus:border-[#D4AF37] font-mono"
                  />
                </div>

                <div>
                  <label className="block text-xs font-mono text-slate-400 mb-1">
                    Kapsyen Gambar / Keterangan Sesi:
                  </label>
                  <input
                    type="text"
                    value={newImageCaption}
                    onChange={(e) => setNewImageCaption(e.target.value)}
                    placeholder="cth: Sesi live chart analysis bersama 200+ trader"
                    className="w-full bg-slate-950 border border-white/10 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-600 focus:outline-none focus:border-[#D4AF37] font-mono"
                  />
                </div>

                {newImageUrl && (
                  <div className="rounded-xl overflow-hidden border border-white/10 bg-slate-950 p-2">
                    <p className="text-[10px] font-mono text-slate-400 mb-1">Pratonton Imej:</p>
                    <img
                      src={newImageUrl}
                      alt="Preview"
                      className="h-32 w-full object-cover rounded-lg"
                      onError={(e) => {
                        (e.target as HTMLElement).style.display = 'none';
                      }}
                    />
                  </div>
                )}

                <div className="pt-3 flex items-center justify-end space-x-3">
                  <button
                    type="button"
                    onClick={() => setIsAddImageModalOpen(false)}
                    className="px-4 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-300 font-mono text-xs transition-colors cursor-pointer"
                  >
                    Batal
                  </button>
                  <button
                    type="submit"
                    className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-300 via-[#D4AF37] to-amber-500 text-slate-950 font-extrabold font-mono text-xs shadow-lg hover:brightness-110 active:scale-95 transition-all flex items-center space-x-1.5 cursor-pointer"
                  >
                    <Save className="w-3.5 h-3.5" />
                    <span>Muat Naik / Simpan</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

      </div>
    </section>
  );
};
