// Generated by IqwanEngine
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { INITIAL_SETUP_PROOFS } from '../data/initialData';
import { Target, DollarSign, BarChart2, Image as ImageIcon, ZoomIn, ArrowUpRight, Check, Calculator, TrendingUp } from 'lucide-react';
import { useScrollReveal } from '../hooks/useScrollReveal';

interface VipSignalSectionProps {
  onOpenLightbox: (images: { url: string; caption?: string; title?: string }[], index: number) => void;
}

interface VipMovingButtonProps {
  id?: string;
  href?: string;
  onClick?: () => void;
  label: string;
  className?: string;
}

/**
 * Reusable Overpower Institutional Button with Embedded Moving Candlestick/Wave Chart
 * (Strictly Static Non-Rotating Vector Icons)
 */
function VipMovingButton({ id, href, onClick, label, className = '' }: VipMovingButtonProps) {
  const content = (
    <div
      id={id}
      onClick={onClick}
      className={`group relative overflow-hidden rounded-xl bg-gradient-to-r from-amber-500 via-amber-400 to-[#D4AF37] px-5 py-3 flex items-center justify-center space-x-2 text-slate-950 font-black text-xs uppercase tracking-wider shadow-[0_0_20px_rgba(245,158,11,0.25)] hover:shadow-[0_0_30px_rgba(245,158,11,0.45)] transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] cursor-pointer select-none ${className}`}
    >
      {/* Dynamic Candlestick Bars Wave in Background */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-60 transition-opacity">
        <div className="absolute inset-0 flex items-end justify-between px-2 pb-0.5 gap-1">
          {[35, 70, 45, 80, 50, 95, 40, 75, 55, 90, 60, 85].map((h, i) => (
            <motion.div
              key={i}
              className="w-[2px] rounded-t-sm"
              style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
              animate={{
                height: [
                  `${Math.max(15, h * 0.3)}%`,
                  `${Math.min(95, h * 0.95)}%`,
                  `${Math.max(20, h * 0.45)}%`
                ]
              }}
              transition={{
                repeat: Infinity,
                duration: 1.5 + (i % 4) * 0.25,
                ease: 'easeInOut',
                repeatType: 'reverse',
                delay: i * 0.05
              }}
            />
          ))}
        </div>

        {/* Dynamic Continuous Moving Market Line Wave */}
        <svg
          className="absolute inset-0 w-[200%] h-full stroke-slate-950/70"
          viewBox="0 0 500 50"
          preserveAspectRatio="none"
        >
          <motion.path
            d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
            fill="none"
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeDasharray="4 2"
            animate={{ x: [0, -250] }}
            transition={{
              repeat: Infinity,
              duration: 4,
              ease: 'linear'
            }}
          />
        </svg>

        <div className="absolute inset-0 bg-gradient-to-r from-amber-400/80 via-amber-300/60 to-amber-500/90" />
      </div>

      {/* Shimmer Specular Light Sweep */}
      <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/30 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

      <span className="relative z-10 drop-shadow-sm font-sans font-extrabold">{label}</span>
      <ArrowUpRight className="relative z-10 w-4 h-4 text-slate-950 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
    </div>
  );

  if (href) {
    return (
      <a href={href} target="_blank" rel="noopener noreferrer" className="inline-block w-full sm:w-auto">
        {content}
      </a>
    );
  }

  return content;
}

export const VipSignalSection: React.FC<VipSignalSectionProps> = ({
  onOpenLightbox,
}) => {
  const [activeTab, setActiveTab] = useState<'provide' | 'rebate' | 'track' | 'proof'>('provide');
  const containerRef = useScrollReveal({ dependencies: [activeTab] });

  // Interactive Self-Rebate Calculator State
  const [tradedLots, setTradedLots] = useState<number>(40);
  const [rebatePerLot, setRebatePerLot] = useState<number>(10);

  const monthlyRebateUSD = tradedLots * rebatePerLot;
  const monthlyRebateMYR = monthlyRebateUSD * 4.45;
  const monthlyRebateIDR = monthlyRebateUSD * 15600;

  const handleProofClick = (index: number) => {
    const formatted = INITIAL_SETUP_PROOFS.map((item) => ({
      url: item.imageUrl,
      caption: `[${item.pair} ${item.type}] ${item.gainPips} (R:R ${item.rrRatio}) — ${item.chartDescription}`,
      title: `${item.pair} Setup Proof`
    }));
    onOpenLightbox(formatted, index);
  };

  return (
    <section id="vip-signal" ref={containerRef} className="py-24 relative bg-[#06090e] border-t border-white/5 overflow-hidden selection:bg-[#D4AF37] selection:text-black">
      {/* Ambient Lighting Background */}
      <div className="absolute top-1/4 -left-32 w-[600px] h-[600px] bg-blue-600/5 rounded-full blur-[160px] pointer-events-none -z-10" />
      <div className="absolute bottom-1/4 -right-32 w-[600px] h-[600px] bg-amber-500/5 rounded-full blur-[160px] pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Section Header (Static Clean Non-Spinning Presentation) */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 reveal-on-scroll">
          <div>
            <div className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-[#2563EB]/15 border border-[#2563EB]/30 text-[#60A5FA] text-xs font-mono mb-4 shadow-[0_0_15px_rgba(37,99,235,0.15)]">
              <Target className="w-3.5 h-3.5 text-[#60A5FA]" />
              <span className="font-bold tracking-wider uppercase">VIP SIGNAL, SUPPORT & CASH REBATE</span>
            </div>
            <h2 className="text-3xl sm:text-5xl font-black text-white tracking-tight uppercase">
              Sistem Isyarat Kuantitatif & <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-amber-400 to-[#D4AF37] drop-shadow-[0_0_25px_rgba(245,158,11,0.3)]">Self-Rebate</span>
            </h2>
            <p className="mt-3 text-slate-400 text-sm sm:text-base max-w-2xl font-medium leading-relaxed">
              Platform menyeluruh yang direka untuk memaksimumkan keuntungan dagangan anda melalui
              setup kebarangkalian tinggi dan pemulangan tunai bagi setiap transaksi.
            </p>
          </div>

          <div className="mt-6 md:mt-0 w-full md:w-auto">
            <VipMovingButton
              id="vip-signal-unlock-btn"
              href="/my/register"
              label="Buka Akses Percuma Valetax"
            />
          </div>
        </div>

        {/* 4 Interactive Tab Selectors (Strictly Static Non-Rotating Icons) */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 mb-8 reveal-on-scroll reveal-delay-1">
          <button
            type="button"
            id="vip-tab-provide"
            onClick={() => setActiveTab('provide')}
            className={`group p-4 sm:p-5 rounded-2xl text-left transition-all duration-300 border backdrop-blur-xl cursor-pointer select-none ${
              activeTab === 'provide'
                ? 'border-amber-400/80 bg-gradient-to-b from-amber-500/15 via-[#0d1424] to-[#080d19] shadow-[0_10px_25px_rgba(245,158,11,0.15)] scale-[1.02]'
                : 'bg-slate-900/60 border-white/5 hover:border-white/20 hover:bg-slate-900/90'
            }`}
          >
            <div className="flex items-center space-x-3">
              <div className={`w-11 h-11 rounded-xl flex items-center justify-center transition-all duration-300 shrink-0 ${activeTab === 'provide' ? 'bg-amber-500 text-slate-950 font-bold shadow-[0_0_15px_rgba(245,158,11,0.4)]' : 'bg-slate-800/60 text-slate-400 group-hover:text-amber-400 group-hover:bg-amber-500/10'}`}>
                <Target className="w-5 h-5" />
              </div>
              <div className="min-w-0">
                <span className={`block text-[10px] font-mono tracking-widest uppercase font-bold ${activeTab === 'provide' ? 'text-amber-400' : 'text-slate-500'}`}>MODUL 01</span>
                <span className="text-xs sm:text-sm font-bold text-white group-hover:text-amber-200 transition-colors truncate block">Apa Kami Provide</span>
              </div>
            </div>
          </button>

          <button
            type="button"
            id="vip-tab-rebate"
            onClick={() => setActiveTab('rebate')}
            className={`group p-4 sm:p-5 rounded-2xl text-left transition-all duration-300 border backdrop-blur-xl cursor-pointer select-none ${
              activeTab === 'rebate'
                ? 'border-amber-400/80 bg-gradient-to-b from-amber-500/15 via-[#0d1424] to-[#080d19] shadow-[0_10px_25px_rgba(245,158,11,0.15)] scale-[1.02]'
                : 'bg-slate-900/60 border-white/5 hover:border-white/20 hover:bg-slate-900/90'
            }`}
          >
            <div className="flex items-center space-x-3">
              <div className={`w-11 h-11 rounded-xl flex items-center justify-center transition-all duration-300 shrink-0 ${activeTab === 'rebate' ? 'bg-amber-500 text-slate-950 font-bold shadow-[0_0_15px_rgba(245,158,11,0.4)]' : 'bg-slate-800/60 text-slate-400 group-hover:text-amber-400 group-hover:bg-amber-500/10'}`}>
                <DollarSign className="w-5 h-5" />
              </div>
              <div className="min-w-0">
                <span className={`block text-[10px] font-mono tracking-widest uppercase font-bold ${activeTab === 'rebate' ? 'text-amber-400' : 'text-slate-500'}`}>MODUL 02</span>
                <span className="text-xs sm:text-sm font-bold text-white group-hover:text-amber-200 transition-colors truncate block">Self-Rebate System</span>
              </div>
            </div>
          </button>

          <button
            type="button"
            id="vip-tab-track"
            onClick={() => setActiveTab('track')}
            className={`group p-4 sm:p-5 rounded-2xl text-left transition-all duration-300 border backdrop-blur-xl cursor-pointer select-none ${
              activeTab === 'track'
                ? 'border-amber-400/80 bg-gradient-to-b from-amber-500/15 via-[#0d1424] to-[#080d19] shadow-[0_10px_25px_rgba(245,158,11,0.15)] scale-[1.02]'
                : 'bg-slate-900/60 border-white/5 hover:border-white/20 hover:bg-slate-900/90'
            }`}
          >
            <div className="flex items-center space-x-3">
              <div className={`w-11 h-11 rounded-xl flex items-center justify-center transition-all duration-300 shrink-0 ${activeTab === 'track' ? 'bg-amber-500 text-slate-950 font-bold shadow-[0_0_15px_rgba(245,158,11,0.4)]' : 'bg-slate-800/60 text-slate-400 group-hover:text-amber-400 group-hover:bg-amber-500/10'}`}>
                <BarChart2 className="w-5 h-5" />
              </div>
              <div className="min-w-0">
                <span className={`block text-[10px] font-mono tracking-widest uppercase font-bold ${activeTab === 'track' ? 'text-amber-400' : 'text-slate-500'}`}>MODUL 03</span>
                <span className="text-xs sm:text-sm font-bold text-white group-hover:text-amber-200 transition-colors truncate block">Track Record & Data</span>
              </div>
            </div>
          </button>

          <button
            type="button"
            id="vip-tab-proof"
            onClick={() => setActiveTab('proof')}
            className={`group p-4 sm:p-5 rounded-2xl text-left transition-all duration-300 border backdrop-blur-xl cursor-pointer select-none ${
              activeTab === 'proof'
                ? 'border-amber-400/80 bg-gradient-to-b from-amber-500/15 via-[#0d1424] to-[#080d19] shadow-[0_10px_25px_rgba(245,158,11,0.15)] scale-[1.02]'
                : 'bg-slate-900/60 border-white/5 hover:border-white/20 hover:bg-slate-900/90'
            }`}
          >
            <div className="flex items-center space-x-3">
              <div className={`w-11 h-11 rounded-xl flex items-center justify-center transition-all duration-300 shrink-0 ${activeTab === 'proof' ? 'bg-amber-500 text-slate-950 font-bold shadow-[0_0_15px_rgba(245,158,11,0.4)]' : 'bg-slate-800/60 text-slate-400 group-hover:text-amber-400 group-hover:bg-amber-500/10'}`}>
                <ImageIcon className="w-5 h-5" />
              </div>
              <div className="min-w-0">
                <span className={`block text-[10px] font-mono tracking-widest uppercase font-bold ${activeTab === 'proof' ? 'text-amber-400' : 'text-slate-500'}`}>MODUL 04</span>
                <span className="text-xs sm:text-sm font-bold text-white group-hover:text-amber-200 transition-colors truncate block">Galeri Bukti Setup</span>
              </div>
            </div>
          </button>
        </div>

        {/* Tab Content Display Container */}
        <div className="rounded-3xl backdrop-blur-2xl bg-[#080d19]/90 border border-white/10 p-6 sm:p-10 relative min-h-[420px] shadow-[0_20px_50px_rgba(0,0,0,0.85)] reveal-on-scroll reveal-delay-2 overflow-hidden">

          {/* TAB 1: APA YANG KAMI PROVIDE */}
          {activeTab === 'provide' && (
            <div className="animate-in fade-in duration-300">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {/* Card 01 */}
                <div className="relative group bg-[#0d1424]/70 backdrop-blur-xl border border-white/5 hover:border-amber-400/50 rounded-2xl p-6 sm:p-8 transition-all duration-300 shadow-xl flex flex-col justify-between">
                  <div>
                    <div className="w-10 h-10 rounded-xl bg-amber-500/15 border border-amber-500/30 text-amber-400 flex items-center justify-center font-mono font-bold mb-5 shadow-[0_0_15px_rgba(245,158,11,0.15)]">
                      01
                    </div>
                    <h4 className="text-xl font-bold text-white mb-3">Daily Institutional Setups</h4>
                    <p className="text-sm text-slate-400 leading-relaxed mb-6 font-medium">
                      Setiap pagi sebelum pembukaan sesi London dan New York, pasukan kuantitatif OWLFX memuat naik
                      analisis terperinci zon pesanan institusi (Gold, Currencies, Index).
                    </p>
                  </div>
                  <ul className="space-y-3 text-xs font-mono pt-4 border-t border-white/5">
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Entry Precise Limit / Market Order</span>
                    </li>
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Stop Loss Maksimum 25 Pips (Gold)</span>
                    </li>
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Pelan Skala TP1, TP2, & TP3 Dinamik</span>
                    </li>
                  </ul>
                </div>

                {/* Card 02 */}
                <div className="relative group bg-[#0d1424]/70 backdrop-blur-xl border border-white/5 hover:border-cyan-400/50 rounded-2xl p-6 sm:p-8 transition-all duration-300 shadow-xl flex flex-col justify-between">
                  <div>
                    <div className="w-10 h-10 rounded-xl bg-cyan-500/15 border border-cyan-500/30 text-cyan-400 flex items-center justify-center font-mono font-bold mb-5 shadow-[0_0_15px_rgba(6,182,212,0.15)]">
                      02
                    </div>
                    <h4 className="text-xl font-bold text-white mb-3">Risk Management Blueprint</h4>
                    <p className="text-sm text-slate-400 leading-relaxed mb-6 font-medium">
                      Kunci kelangsungan akaun dagangan ialah nisbah risiko yang terkawal. Kami membekalkan kalkulator
                      saiz lot automatik dan panduan modal untuk mengelakkan 'margin call'.
                    </p>
                  </div>
                  <ul className="space-y-3 text-xs font-mono pt-4 border-t border-white/5">
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Risiko terhad 1% - 2% setiap posisi</span>
                    </li>
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Prosedur Breakeven selepas TP1</span>
                    </li>
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Perlindungan drawdown pasaran</span>
                    </li>
                  </ul>
                </div>

                {/* Card 03 */}
                <div className="relative group bg-[#0d1424]/70 backdrop-blur-xl border border-white/5 hover:border-emerald-400/50 rounded-2xl p-6 sm:p-8 transition-all duration-300 shadow-xl flex flex-col justify-between">
                  <div>
                    <div className="w-10 h-10 rounded-xl bg-emerald-500/15 border border-emerald-500/30 text-emerald-400 flex items-center justify-center font-mono font-bold mb-5 shadow-[0_0_15px_rgba(16,185,129,0.15)]">
                      03
                    </div>
                    <h4 className="text-xl font-bold text-white mb-3">High-Probability Zone</h4>
                    <p className="text-sm text-slate-400 leading-relaxed mb-6 font-medium">
                      Pengesanan zon Order Block dan Liquidity Sweep yang hanya diambil apabila algoritma OWL ALGO
                      menunjukkan persetujuan pelbagai kerangka masa.
                    </p>
                  </div>
                  <ul className="space-y-3 text-xs font-mono pt-4 border-t border-white/5">
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Penapisan zon palsu (Fakeout filter)</span>
                    </li>
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Konfluens penunjuk volum kuantitatif</span>
                    </li>
                    <li className="flex items-center space-x-2.5 text-slate-300">
                      <div className="p-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/40 shrink-0">
                        <Check className="w-3 h-3 text-emerald-400" />
                      </div>
                      <span>Peringatan terus ke Telegram VIP</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: SELF-REBATE SYSTEM */}
          {activeTab === 'rebate' && (
            <div className="animate-in fade-in duration-300">
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
                <div className="lg:col-span-6 space-y-4">
                  <span className="inline-block px-3.5 py-1 rounded-full bg-[#D4AF37]/15 text-[#D4AF37] border border-[#D4AF37]/35 text-xs font-mono font-bold tracking-wider uppercase">
                    100% PULANGAN REBAT TUNAI TELUS
                  </span>
                  <h3 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
                    Setiap Lot Yang Anda Dagangkan Membawa Pulangan Tunai
                  </h3>
                  <p className="text-sm text-slate-300 leading-relaxed font-medium">
                    Berbeza dengan model IB konvensional di mana komisen disimpan oleh pengantara, sistem Valetax MIB
                    di bawah naungan OWLFX membolehkan anda menikmati rebat pulangan tunai terus ke dompet akaun anda.
                    Menang atau kalah dagangan anda, rebat tetap dikira dan boleh dikeluarkan bila-bila masa!
                  </p>

                  <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-2.5 font-mono text-xs backdrop-blur-md">
                    <div className="flex justify-between text-slate-300">
                      <span>Model Pembayaran:</span>
                      <span className="text-[#D4AF37] font-bold">Harian / Serta-merta (Instant Payout)</span>
                    </div>
                    <div className="flex justify-between text-slate-300">
                      <span>Kadar Rebat Standard:</span>
                      <span className="text-white font-bold">Hingga $10 - $15 / Lot Pusingan</span>
                    </div>
                    <div className="flex justify-between text-slate-300">
                      <span>Integrasi Akaun:</span>
                      <span className="text-[#06B6D4] font-bold">Akaun Valetax</span>
                    </div>
                  </div>
                </div>

                {/* Interactive Rebate Calculator */}
                <div className="lg:col-span-6 p-6 sm:p-8 rounded-3xl backdrop-blur-xl bg-slate-950/70 border border-[#D4AF37]/35 shadow-2xl">
                  <div className="flex items-center justify-between pb-4 border-b border-white/10 mb-5">
                    <div className="flex items-center space-x-2 text-white font-bold text-sm">
                      <Calculator className="w-4 h-4 text-[#D4AF37]" />
                      <span>Kalkulator Anggaran Rebat Tunai Anda</span>
                    </div>
                    <span className="text-[10px] font-mono text-[#D4AF37] font-bold tracking-[0.2em] uppercase">LIVE SIMULATOR</span>
                  </div>

                  {/* Slider Control */}
                  <div className="space-y-4 mb-6">
                    <div>
                      <div className="flex justify-between text-xs font-mono text-slate-300 mb-2">
                        <span>Anggaran Volum Dagangan Sebulan:</span>
                        <span className="text-lg font-bold text-white font-mono">{tradedLots} Lots</span>
                      </div>
                      <input
                        type="range"
                        min="5"
                        max="250"
                        step="5"
                        value={tradedLots}
                        onChange={(e) => setTradedLots(Number(e.target.value))}
                        className="w-full accent-[#D4AF37] h-2 bg-white/10 rounded-lg cursor-pointer"
                      />
                      <div className="flex justify-between text-[10px] font-mono text-slate-500 mt-1">
                        <span>5 Lots</span>
                        <span>100 Lots</span>
                        <span>250+ Lots</span>
                      </div>
                    </div>

                    {/* Rebate rate toggle */}
                    <div className="flex items-center justify-between text-xs font-mono flex-wrap gap-2">
                      <span className="text-slate-400">Peringkat Rebat Lot:</span>
                      <div className="flex space-x-1.5">
                        {[8, 10, 12, 15].map((rate) => (
                          <button
                            key={rate}
                            type="button"
                            onClick={() => setRebatePerLot(rate)}
                            className={`px-3 py-1 rounded-full text-[11px] transition-all cursor-pointer font-bold ${
                              rebatePerLot === rate
                                ? 'bg-[#D4AF37] text-slate-950 shadow-[0_0_10px_rgba(212,175,55,0.3)]'
                                : 'bg-white/5 text-slate-300 hover:bg-white/10 border border-white/10'
                            }`}
                          >
                            ${rate}/lot
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Output Display Cards */}
                  <div className="grid grid-cols-2 gap-3 pt-3 border-t border-white/10">
                    <div className="p-4 rounded-2xl bg-white/5 border border-white/5">
                      <span className="text-[10px] font-mono text-slate-400 block tracking-wider uppercase">ANGGARAN REBAT (USD)</span>
                      <span className="text-xl sm:text-2xl font-black font-mono text-emerald-400">
                        ${monthlyRebateUSD.toLocaleString()}
                      </span>
                      <span className="text-[10px] text-slate-500 block mt-0.5">Dikreditkan bulanan</span>
                    </div>

                    <div className="p-4 rounded-2xl bg-white/5 border border-white/5">
                      <span className="text-[10px] font-mono text-slate-400 block tracking-wider uppercase">NILAI RINGGIT (MYR)</span>
                      <span className="text-xl sm:text-2xl font-black font-mono text-[#D4AF37]">
                        RM {Math.round(monthlyRebateMYR).toLocaleString()}
                      </span>
                      <span className="text-[10px] text-slate-500 block mt-0.5 font-mono">
                        ≈ Rp {(monthlyRebateIDR / 1000000).toFixed(1)} Juta
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: TRACK RECORD & RESULTS */}
          {activeTab === 'track' && (
            <div className="animate-in fade-in duration-300">
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5 text-center">
                  <span className="text-[10px] sm:text-[11px] font-mono text-slate-400 uppercase">Purata Winrate YTD</span>
                  <div className="text-2xl sm:text-3xl font-black font-mono text-emerald-400 mt-1">82.4%</div>
                  <span className="text-[10px] text-slate-500 font-mono">Daripada 1,420+ Posisi</span>
                </div>
                <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5 text-center">
                  <span className="text-[10px] sm:text-[11px] font-mono text-slate-400 uppercase">Risk : Reward Ratio</span>
                  <div className="text-2xl sm:text-3xl font-black font-mono text-[#D4AF37] mt-1">1 : 3.4</div>
                  <span className="text-[10px] text-slate-500 font-mono">Disiplin Stop Loss Ketat</span>
                </div>
                <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5 text-center">
                  <span className="text-[10px] sm:text-[11px] font-mono text-slate-400 uppercase">Max Drawdown</span>
                  <div className="text-2xl sm:text-3xl font-black font-mono text-sky-400 mt-1">4.2%</div>
                  <span className="text-[10px] text-slate-500 font-mono">Pengurusan Modal Teguh</span>
                </div>
                <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5 text-center">
                  <span className="text-[10px] sm:text-[11px] font-mono text-slate-400 uppercase">Jumlah Pips Dijana</span>
                  <div className="text-2xl sm:text-3xl font-black font-mono text-white mt-1">+14,850</div>
                  <span className="text-[10px] text-slate-500 font-mono">Bagi Q1 2026</span>
                </div>
              </div>

              {/* Monthly Visual Progress Breakdown */}
              <div className="p-5 sm:p-6 rounded-2xl bg-slate-900/90 border border-white/5">
                <div className="flex items-center justify-between mb-4">
                  <h4 className="text-sm font-bold text-white flex items-center space-x-2">
                    <TrendingUp className="w-4 h-4 text-[#D4AF37]" />
                    <span>Laporan Prestasi Bulanan 2026 (Audit Terbuka)</span>
                  </h4>
                  <span className="text-xs font-mono text-[#10B981] font-bold">100% DISAHKAN</span>
                </div>

                <div className="space-y-4 font-mono text-xs">
                  <div>
                    <div className="flex justify-between text-slate-300 mb-1.5">
                      <span>Januari 2026 — Winrate 84.1%</span>
                      <span className="text-emerald-400 font-bold">+3,940 Pips (+$48,200)</span>
                    </div>
                    <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                      <div className="bg-gradient-to-r from-[#D4AF37] to-emerald-400 h-2 rounded-full" style={{ width: '84%' }}></div>
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between text-slate-300 mb-1.5">
                      <span>Februari 2026 — Winrate 81.8%</span>
                      <span className="text-emerald-400 font-bold">+4,210 Pips (+$56,400)</span>
                    </div>
                    <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                      <div className="bg-gradient-to-r from-[#D4AF37] to-emerald-400 h-2 rounded-full" style={{ width: '82%' }}></div>
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between text-slate-300 mb-1.5">
                      <span>Mac 2026 (Semasa) — Winrate 83.0%</span>
                      <span className="text-emerald-400 font-bold">+6,700 Pips (+$74,900)</span>
                    </div>
                    <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                      <div className="bg-gradient-to-r from-[#D4AF37] to-emerald-400 h-2 rounded-full" style={{ width: '83%' }}></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 4: GALERI BUKTI & SETUP MT4/MT5 */}
          {activeTab === 'proof' && (
            <div className="animate-in fade-in duration-300">
              <div className="flex items-center justify-between mb-4">
                <p className="text-xs text-slate-300">
                  Klik mana-mana tangkap layar setup untuk paparan pembesar skrin penuh (Lightbox HD).
                </p>
                <span className="text-xs font-mono text-[#D4AF37]">4 Setup Terkini</span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {INITIAL_SETUP_PROOFS.map((proof, idx) => (
                  <div
                    key={proof.id}
                    id={`proof-card-${proof.id}`}
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      handleProofClick(idx);
                    }}
                    onAuxClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                    }}
                    className="group relative rounded-2xl overflow-hidden bg-slate-900 border border-white/10 hover:border-[#D4AF37] transition-all cursor-pointer shadow-lg"
                  >
                    <div className="relative h-44 w-full overflow-hidden">
                      <img
                        src={proof.imageUrl}
                        alt={proof.pair}
                        referrerPolicy="no-referrer"
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          handleProofClick(idx);
                        }}
                        onAuxClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                        }}
                        onContextMenu={(e) => e.preventDefault()}
                        onDragStart={(e) => e.preventDefault()}
                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500 select-none"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent pointer-events-none"></div>

                      <div className="absolute top-2 left-2 flex items-center space-x-1.5 pointer-events-none">
                        <span
                          className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold ${
                            proof.type === 'BUY'
                              ? 'bg-emerald-500/90 text-slate-950'
                              : 'bg-rose-500/90 text-white'
                          }`}
                        >
                          {proof.type}
                        </span>
                        <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-black/70 text-white border border-white/10">
                          {proof.pair}
                        </span>
                      </div>

                      <div className="absolute bottom-2 left-2 right-2 flex items-center justify-between text-xs font-mono pointer-events-none">
                        <span className="font-bold text-emerald-400">{proof.gainPips}</span>
                        <span className="text-slate-300 font-medium">RR {proof.rrRatio}</span>
                      </div>

                      <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center pointer-events-none">
                        <div className="p-2 rounded-full bg-[#D4AF37] text-slate-950 shadow-xl">
                          <ZoomIn className="w-5 h-5" />
                        </div>
                      </div>
                    </div>

                    <div className="p-3 text-[11px] text-slate-400 font-mono line-clamp-2">
                      {proof.chartDescription}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

      </div>
    </section>
  );
};
