// Generated by IqwanEngine
import React, { useState, useEffect, lazy, Suspense } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate, useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Region, RoadtourStateData, IBRegionData, CommunityLinks, LiveEventAlertData } from './types';
import { INITIAL_ROADTOUR_STATES, IB_REGIONS_DATA, INITIAL_COMMUNITY_LINKS, INITIAL_LIVE_EVENT_ALERTS } from './data/initialData';
import { Layout } from './components/Layout';

// Lazy Loaded Sections
const HomePage = lazy(() => import('./components/HomePage').then(m => ({ default: m.HomePage })));
const AboutSection = lazy(() => import('./components/AboutSection').then(m => ({ default: m.AboutSection })));
const VipSignalSection = lazy(() => import('./components/VipSignalSection').then(m => ({ default: m.VipSignalSection })));
const OwlAlgoSection = lazy(() => import('./components/OwlAlgoSection').then(m => ({ default: m.OwlAlgoSection })));
const RoadtourSection = lazy(() => import('./components/RoadtourSection').then(m => ({ default: m.RoadtourSection })));
const IBDevelopmentSection = lazy(() => import('./components/IBDevelopmentSection').then(m => ({ default: m.IBDevelopmentSection })));
const BasicEducationSection = lazy(() => import('./components/BasicEducationSection').then(m => ({ default: m.BasicEducationSection })));

import { LightboxModal } from './components/LightboxModal';
import { RegistrationModal, RegistrationTabType } from './components/RegistrationModal';
import { AdminCMSModal } from './components/AdminCMSModal';
import { LiveEventAlert } from './components/LiveEventAlert';
import { ArrowRight, MessageCircle, Send, Shield } from 'lucide-react';
import ScrollToTop from './components/common/ScrollToTop';

/**
 * Loading Fallback for Suspense
 */
function SectionLoading() {
  return (
    <div className="min-h-[60vh] w-full flex items-center justify-center">
      <div className="flex flex-col items-center space-y-4">
        <div className="w-12 h-12 rounded-full border-2 border-amber-500/20 border-t-amber-500 animate-spin" />
        <span className="text-xs font-mono text-amber-500/60 uppercase tracking-widest animate-pulse">
          OWLFX ARCHITECTURE LOADING...
        </span>
      </div>
    </div>
  );
}

interface ContactMovingButtonProps {
  id?: string;
  href: string;
  label: string;
  subLabel?: string;
  icon: React.ReactNode;
  variant: 'emerald' | 'cyan';
  className?: string;
}

/**
 * Reusable Overpower Institutional Contact Button with Embedded Moving Candlestick Wave
 * Strictly NO 360° Rotating Pods
 */
function ContactMovingButton({
  id,
  href,
  label,
  subLabel,
  icon,
  variant,
  className = ''
}: ContactMovingButtonProps) {
  const isEmerald = variant === 'emerald';
  const strokeColor = isEmerald ? '#10B981' : '#06B6D4';

  const baseStyle = isEmerald
    ? 'bg-slate-950/90 border border-emerald-500/40 hover:border-emerald-400 text-emerald-400 hover:text-white shadow-[0_0_25px_rgba(16,185,129,0.18)] hover:shadow-[0_0_35px_rgba(16,185,129,0.38)]'
    : 'bg-slate-950/90 border border-cyan-500/40 hover:border-cyan-400 text-cyan-300 hover:text-white shadow-[0_0_25px_rgba(6,182,212,0.18)] hover:shadow-[0_0_35px_rgba(6,182,212,0.38)]';

  return (
    <a
      id={id}
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className={`group relative overflow-hidden rounded-2xl px-6 py-4 flex items-center justify-between gap-4 transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] select-none cursor-pointer ${baseStyle} ${className}`}
    >
      {/* Dynamic Candlestick Bars Wave in Background */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30 group-hover:opacity-55 transition-opacity">
        <div className="absolute inset-0 flex items-end justify-between px-3 pb-1 gap-1">
          {[40, 75, 45, 85, 55, 95, 35, 80, 50, 90, 60, 75, 45, 85].map((h, i) => (
            <motion.div
              key={i}
              className="w-[2px] rounded-t-sm"
              style={{ backgroundColor: i % 2 === 0 ? '#10B981' : '#EF4444' }}
              animate={{
                height: [
                  `${Math.max(15, h * 0.3)}%`,
                  `${Math.min(95, h * 0.95)}%`,
                  `${Math.max(20, h * 0.45)}%`
                ]
              }}
              transition={{
                repeat: Infinity,
                duration: 1.5 + (i % 4) * 0.25,
                ease: 'easeInOut',
                repeatType: 'reverse',
                delay: i * 0.05
              }}
            />
          ))}
        </div>

        {/* Dynamic Continuous Moving Market Line Wave */}
        <svg
          className="absolute inset-0 w-[200%] h-full stroke-current"
          style={{ color: strokeColor }}
          viewBox="0 0 500 50"
          preserveAspectRatio="none"
        >
          <motion.path
            d="M 0 30 Q 30 10, 60 25 T 120 20 T 180 35 T 240 15 T 300 30 T 360 10 T 420 25 T 480 20 T 540 30"
            fill="none"
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeDasharray="4 2"
            animate={{ x: [0, -250] }}
            transition={{
              repeat: Infinity,
              duration: 4,
              ease: 'linear'
            }}
          />
        </svg>

        <div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/70 to-slate-950/90" />
      </div>

      {/* Shimmer Specular Light Sweep */}
      <div className="absolute inset-0 -translate-x-full group-hover:translate-x-full duration-1000 bg-gradient-to-r from-transparent via-white/20 to-transparent transform skew-x-12 transition-transform ease-out pointer-events-none" />

      {/* Content Side with Static Icon */}
      <div className="relative z-10 flex items-center space-x-3.5">
        <div className="p-2.5 rounded-xl bg-white/5 border border-white/10 shrink-0">
          {icon}
        </div>
        <div className="text-left">
          <div className="font-mono text-xs sm:text-sm font-bold tracking-wider uppercase drop-shadow-sm">
            {label}
          </div>
          {subLabel && (
            <div className="text-[10px] sm:text-[11px] font-mono text-slate-400 font-medium">
              {subLabel}
            </div>
          )}
        </div>
      </div>

      <div className="relative z-10 shrink-0">
        <ArrowRight className="w-5 h-5 group-hover:translate-x-1.5 transition-transform duration-300" />
      </div>
    </a>
  );
}

export default function App() {
  const [securityToast, setSecurityToast] = useState<{ show: boolean; message: string }>({
    show: false,
    message: '',
  });

  useEffect(() => {
    let toastTimer: ReturnType<typeof setTimeout>;

    const triggerSecurityNotice = (msg: string) => {
      setSecurityToast({ show: true, message: msg });
      clearTimeout(toastTimer);
      toastTimer = setTimeout(() => {
        setSecurityToast({ show: false, message: '' });
      }, 2400);
    };

    const handleContextMenu = (e: MouseEvent) => {
      e.preventDefault();
      triggerSecurityNotice('Perlindungan Media & Hak Cipta OWLFX Aktif. Klik kanan disekat.');
    };

    const handleDragStart = (e: DragEvent) => {
      e.preventDefault();
      triggerSecurityNotice('Perlindungan Kandungan: Penarikan imej (drag-and-drop) disekat.');
    };

    const handleKeyDown = (e: KeyboardEvent) => {
      const isMac = navigator.platform.toUpperCase().indexOf('MAC') >= 0;
      const ctrlOrCmd = isMac ? e.metaKey : e.ctrlKey;

      if (e.key === 'F12') {
        e.preventDefault();
        e.stopPropagation();
        triggerSecurityNotice('Pintasan pembangun disekat untuk melindungi integriti platform.');
        return;
      }

      if (ctrlOrCmd && e.shiftKey && (e.key === 'I' || e.key === 'i' || e.key === 'J' || e.key === 'j' || e.key === 'C' || e.key === 'c')) {
        e.preventDefault();
        e.stopPropagation();
        triggerSecurityNotice('Pemeriksaan elemen (Inspect Element) disekat.');
        return;
      }

      if (ctrlOrCmd && (e.key === 'u' || e.key === 'U')) {
        e.preventDefault();
        e.stopPropagation();
        triggerSecurityNotice('Paparan kod sumber disekat.');
        return;
      }

      if (ctrlOrCmd && (e.key === 's' || e.key === 'S')) {
        e.preventDefault();
        e.stopPropagation();
        triggerSecurityNotice('Penyimpanan halaman secara luar talian disekat.');
        return;
      }
    };

    window.addEventListener('contextmenu', handleContextMenu);
    window.addEventListener('dragstart', handleDragStart);
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      window.removeEventListener('contextmenu', handleContextMenu);
      window.removeEventListener('dragstart', handleDragStart);
      window.removeEventListener('keydown', handleKeyDown);
      clearTimeout(toastTimer);
    };
  }, []);

  const [currentRegion] = useState<Region>(() => {
    const saved = localStorage.getItem('owlfx_region');
    return (saved === 'ID' ? 'ID' : 'MY') as Region;
  });

  const [statesData, setStatesData] = useState<RoadtourStateData[]>(() => {
    const saved = localStorage.getItem('owlfx_roadtour_states');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse saved roadtour states', e);
      }
    }
    return INITIAL_ROADTOUR_STATES;
  });

  const [ibData, setIBData] = useState<Record<'MY' | 'ID', IBRegionData>>(() => {
    const saved = localStorage.getItem('owlfx_ib_data');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse saved ib data', e);
      }
    }
    return IB_REGIONS_DATA;
  });

  const [communityLinks, setCommunityLinks] = useState<CommunityLinks>(() => {
    const saved = localStorage.getItem('owlfx_community_links');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse saved community links', e);
      }
    }
    return INITIAL_COMMUNITY_LINKS;
  });

  const [eventAlerts, setEventAlerts] = useState<LiveEventAlertData[]>(() => {
    const saved = localStorage.getItem('owlfx_live_event_alerts');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed) && parsed.length > 0) {
          return parsed;
        }
      } catch (e) {
        console.error('Failed to parse saved live event alerts', e);
      }
    }
    const singleSaved = localStorage.getItem('owlfx_live_event_alert');
    if (singleSaved) {
      try {
        const parsedSingle = JSON.parse(singleSaved);
        if (parsedSingle && parsedSingle.eventName) {
          return [{ id: parsedSingle.id || `alert-${Date.now()}`, ...parsedSingle }];
        }
      } catch (e) {
        // ignore
      }
    }
    return INITIAL_LIVE_EVENT_ALERTS;
  });

  const [lightboxOpen, setLightboxOpen] = useState(false);
  const [lightboxImages, setLightboxImages] = useState<{ url: string; caption?: string; title?: string }[]>([]);
  const [lightboxIndex, setLightboxIndex] = useState(0);

  const [regModalOpen, setRegModalOpen] = useState(false);
  const [regModalTab] = useState<RegistrationTabType>('my-community');

  const [adminModalOpen, setAdminModalOpen] = useState(false);
  const [isAdminAuthenticated, setIsAdminAuthenticated] = useState<boolean>(() => {
    const token = sessionStorage.getItem('owlfx_admin_auth') || localStorage.getItem('owlfx_admin_auth');
    return !!token;
  });

  const handleAdminLoginSuccess = (token: string) => {
    setIsAdminAuthenticated(true);
    sessionStorage.setItem('owlfx_admin_auth', token);
    localStorage.setItem('owlfx_admin_auth', token);
    setSecurityToast({
      show: true,
      message: 'Hi IqwanEngine. Sesi Pentadbir OWLFX telah disahkan dengan selamat.',
    });
  };

  const handleAdminSignOut = () => {
    setIsAdminAuthenticated(false);
    sessionStorage.clear();
    localStorage.removeItem('owlfx_admin_auth');
    setSecurityToast({
      show: true,
      message: 'Sesi Pentadbir telah dilog keluar dan cache dipadamkan.',
    });
  };

  const handleUpdateStatesData = (newStates: RoadtourStateData[]) => {
    setStatesData(newStates);
    localStorage.setItem('owlfx_roadtour_states', JSON.stringify(newStates));
  };

  const handleUpdateIBData = (newIBData: Record<'MY' | 'ID', IBRegionData>) => {
    setIBData(newIBData);
    localStorage.setItem('owlfx_ib_data', JSON.stringify(newIBData));
  };

  const handleUpdateCommunityLinks = (newLinks: CommunityLinks) => {
    setCommunityLinks(newLinks);
    localStorage.setItem('owlfx_community_links', JSON.stringify(newLinks));
  };

  const handleUpdateEventAlerts = (newEventAlerts: LiveEventAlertData[]) => {
    setEventAlerts(newEventAlerts);
    localStorage.setItem('owlfx_live_event_alerts', JSON.stringify(newEventAlerts));
  };

  const handleResetDefaults = () => {
    if (window.confirm('Adakah anda pasti ingin memulihkan semua data galeri dan pautan ke tetapan asal?')) {
      setStatesData(INITIAL_ROADTOUR_STATES);
      setIBData(IB_REGIONS_DATA);
      setCommunityLinks(INITIAL_COMMUNITY_LINKS);
      setEventAlerts(INITIAL_LIVE_EVENT_ALERTS);
      localStorage.removeItem('owlfx_roadtour_states');
      localStorage.removeItem('owlfx_ib_data');
      localStorage.removeItem('owlfx_community_links');
      localStorage.removeItem('owlfx_live_event_alerts');
      localStorage.removeItem('owlfx_live_event_alert');
    }
  };

  const handleOpenLightbox = (images: { url: string; caption?: string; title?: string }[], index: number = 0) => {
    setLightboxImages(images);
    setLightboxIndex(index);
    setLightboxOpen(true);
  };

  return (
    <Router>
      <ScrollToTop />
      <Layout
        onOpenAdmin={() => setAdminModalOpen(true)}
        communityLinks={communityLinks}
        securityToast={securityToast}
      >
        <Suspense fallback={<SectionLoading />}>
          <Routes>
            <Route path="/" element={<HomePage />} />
            <Route path="/about-us" element={<AboutSection />} />
            <Route
              path="/ib-development"
              element={
                <IBDevelopmentSection
                  currentRegion={currentRegion}
                  ibData={ibData}
                  onOpenLightbox={handleOpenLightbox}
                />
              }
            />
            <Route
              path="/owlalgo"
              element={
                <OwlAlgoSection
                  onOpenLightbox={handleOpenLightbox}
                />
              }
            />
            <Route
              path="/roadtour"
              element={
                <RoadtourSection
                  statesData={statesData}
                  onOpenLightbox={handleOpenLightbox}
                  isAdmin={isAdminAuthenticated}
                  onUpdateStatesData={handleUpdateStatesData}
                  onOpenAdminLogin={() => setAdminModalOpen(true)}
                  onAdminSignOut={handleAdminSignOut}
                />
              }
            />
            <Route
              path="/group-support"
              element={
                <VipSignalSection
                  onOpenLightbox={handleOpenLightbox}
                />
              }
            />
            <Route path="/education" element={<BasicEducationSection />} />
            <Route
              path="/contact"
              element={
                <section className="py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto relative overflow-hidden selection:bg-[#D4AF37] selection:text-black">
                  {/* Ambient Backlight Elements */}
                  <div className="absolute top-1/4 -left-32 w-[500px] h-[500px] bg-emerald-500/5 rounded-full blur-[160px] pointer-events-none -z-10" />
                  <div className="absolute bottom-1/4 -right-32 w-[500px] h-[500px] bg-cyan-500/5 rounded-full blur-[160px] pointer-events-none -z-10" />

                  <div className="text-center max-w-3xl mx-auto mb-16">
                    <div className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-[#D4AF37]/10 border border-[#D4AF37]/30 text-[#D4AF37] text-xs font-mono mb-4 shadow-[0_0_15px_rgba(212,175,55,0.15)]">
                      <Shield className="w-3.5 h-3.5 text-[#D4AF37]" />
                      <span className="font-bold tracking-wider uppercase">OFFICIAL INSTITUTIONAL DESK</span>
                    </div>

                    <h1 className="text-3xl sm:text-5xl font-black text-white tracking-tight uppercase">
                      Hubungi <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-200 via-amber-400 to-[#D4AF37] drop-shadow-[0_0_25px_rgba(245,158,11,0.3)]">Admin</span> OWLFX
                    </h1>
                    <p className="mt-4 text-slate-400 text-sm sm:text-base leading-relaxed font-medium">
                      Sertai saluran rasmi komuniti trader atau hubungi admin kami terus untuk sebarang pertanyaan berkaitan pendaftaran, sistem rebat, dan integrasi penunjuk algoritma.
                    </p>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12 max-w-5xl mx-auto">
                    {/* Card 1: WhatsApp Careline */}
                    <div className="p-7 sm:p-9 rounded-3xl bg-[#0A101D]/80 backdrop-blur-2xl border border-white/10 hover:border-emerald-400/50 shadow-[0_20px_50px_rgba(0,0,0,0.85)] transition-all flex flex-col justify-between relative overflow-hidden">
                      <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-emerald-400/60 to-transparent" />

                      <div>
                        <div className="flex items-center justify-between mb-5">
                          <div className="p-3.5 rounded-2xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/30">
                            <MessageCircle className="w-6 h-6" />
                          </div>
                          <span className="text-[10px] font-mono font-bold px-3 py-1 rounded-full bg-emerald-950/80 border border-emerald-500/30 text-emerald-400 uppercase tracking-widest">
                            MEJA PANTAS (24/7)
                          </span>
                        </div>

                        <h2 className="text-xl sm:text-2xl font-black text-white mb-3 tracking-tight">Sokongan WhatsApp Careline</h2>
                        <p className="text-slate-400 text-xs sm:text-sm leading-relaxed mb-6 font-medium">
                          Pasukan operasi kami sedia membantu anda dengan pengesahan akaun MIB Valetax, bantuan teknikal TradingView, atau pendaftaran program IB Development.
                        </p>
                      </div>

                      <ContactMovingButton
                        id="contact-whatsapp-careline-btn"
                        href="http://wasap.my/+60102263677/(Website)Hai,%20saya%20nak%20tahu%20lebih%20mendalam%20tentang%20OWLFX"
                        label="WhatsApp Careline"
                        subLabel="Respon Pantas Pegawai Khidmat"
                        icon={<MessageCircle className="w-5 h-5 text-emerald-400" />}
                        variant="emerald"
                      />
                    </div>

                    {/* Card 2: Telegram Channel */}
                    <div className="p-7 sm:p-9 rounded-3xl bg-[#0A101D]/80 backdrop-blur-2xl border border-white/10 hover:border-cyan-400/50 shadow-[0_20px_50px_rgba(0,0,0,0.85)] transition-all flex flex-col justify-between relative overflow-hidden">
                      <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-cyan-400/60 to-transparent" />

                      <div>
                        <div className="flex items-center justify-between mb-5">
                          <div className="p-3.5 rounded-2xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/30">
                            <Send className="w-6 h-6" />
                          </div>
                          <span className="text-[10px] font-mono font-bold px-3 py-1 rounded-full bg-cyan-950/80 border border-cyan-500/30 text-cyan-400 uppercase tracking-widest">
                            SIARAN LANGSUNG
                          </span>
                        </div>

                        <h2 className="text-xl sm:text-2xl font-black text-white mb-3 tracking-tight">Saluran Komuniti Telegram</h2>
                        <p className="text-slate-400 text-xs sm:text-sm leading-relaxed mb-6 font-medium">
                          Sertai saluran awam rasmi untuk menerima analisis struktur pasaran harian, zon kecairan harga Gold (XAUUSD), dan hebahan aktiviti jelajah seminar kebangsaan.
                        </p>
                      </div>

                      <ContactMovingButton
                        id="contact-telegram-channel-btn"
                        href="https://t.me/OWLfxPublicChannel"
                        label="Sertai Saluran Telegram"
                        subLabel="Kemaskini Harian & Analisis Percuma"
                        icon={<Send className="w-5 h-5 text-cyan-300" />}
                        variant="cyan"
                      />
                    </div>
                  </div>
                </section>
              }
            />
            <Route path="*" element={<Navigate to="/" replace />} />
          </Routes>
        </Suspense>
      </Layout>

      {/* Modals & Floating Elements */}
      <LightboxModal
        isOpen={lightboxOpen}
        onClose={() => setLightboxOpen(false)}
        images={lightboxImages}
        currentIndex={lightboxIndex}
        onNavigate={(newIdx) => setLightboxIndex(newIdx)}
      />

      <RegistrationModal
        isOpen={regModalOpen}
        onClose={() => setRegModalOpen(false)}
        defaultTab={regModalTab}
      />

      <AdminCMSModal
        isOpen={adminModalOpen}
        onClose={() => setAdminModalOpen(false)}
        statesData={statesData}
        onUpdateStatesData={handleUpdateStatesData}
        ibData={ibData}
        onUpdateIBData={handleUpdateIBData}
        communityLinks={communityLinks}
        onUpdateCommunityLinks={handleUpdateCommunityLinks}
        onResetDefaults={handleResetDefaults}
        isAdminAuthenticated={isAdminAuthenticated}
        onLoginSuccess={handleAdminLoginSuccess}
        onSignOut={handleAdminSignOut}
        eventAlerts={eventAlerts}
        onUpdateEventAlerts={handleUpdateEventAlerts}
      />

      <LiveEventAlert alerts={eventAlerts} />
    </Router>
  );
}
